package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for add_demag_boundary_corr kernel
var addDemagBoundaryCorrCode cu.Function

// Stores the arguments for add_demag_boundary_corr kernel invocation
type addDemagBoundaryCorrArgsT struct {
	argBx unsafe.Pointer
	argBy unsafe.Pointer
	argBz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argMs unsafe.Pointer
	argMsMul float32
	argPhi unsafe.Pointer
	argTargetIdx unsafe.Pointer
	argSourceIdx unsafe.Pointer
	argTensor unsafe.Pointer
	argStencilCount int
	argNTarget int
	argptr [14]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for add_demag_boundary_corr kernel invocation
var addDemagBoundaryCorrArgs addDemagBoundaryCorrArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addDemagBoundaryCorrArgs.argptr[0] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argBx)
	addDemagBoundaryCorrArgs.argptr[1] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argBy)
	addDemagBoundaryCorrArgs.argptr[2] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argBz)
	addDemagBoundaryCorrArgs.argptr[3] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argMx)
	addDemagBoundaryCorrArgs.argptr[4] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argMy)
	addDemagBoundaryCorrArgs.argptr[5] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argMz)
	addDemagBoundaryCorrArgs.argptr[6] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argMs)
	addDemagBoundaryCorrArgs.argptr[7] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argMsMul)
	addDemagBoundaryCorrArgs.argptr[8] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argPhi)
	addDemagBoundaryCorrArgs.argptr[9] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argTargetIdx)
	addDemagBoundaryCorrArgs.argptr[10] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argSourceIdx)
	addDemagBoundaryCorrArgs.argptr[11] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argTensor)
	addDemagBoundaryCorrArgs.argptr[12] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argStencilCount)
	addDemagBoundaryCorrArgs.argptr[13] = unsafe.Pointer(&addDemagBoundaryCorrArgs.argNTarget)
	}

// Wrapper for add_demag_boundary_corr CUDA kernel, asynchronous.
func kAddDemagBoundaryCorrAsync(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, phi unsafe.Pointer, targetIdx unsafe.Pointer, sourceIdx unsafe.Pointer, tensor unsafe.Pointer, stencilCount int, nTarget int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("add_demag_boundary_corr")
	}

	addDemagBoundaryCorrArgs.Lock()
	defer addDemagBoundaryCorrArgs.Unlock()

	if addDemagBoundaryCorrCode == 0 {
		addDemagBoundaryCorrCode = fatbinLoad(addDemagBoundaryCorrMap, "add_demag_boundary_corr")
	}

	addDemagBoundaryCorrArgs.argBx = Bx
	addDemagBoundaryCorrArgs.argBy = By
	addDemagBoundaryCorrArgs.argBz = Bz
	addDemagBoundaryCorrArgs.argMx = mx
	addDemagBoundaryCorrArgs.argMy = my
	addDemagBoundaryCorrArgs.argMz = mz
	addDemagBoundaryCorrArgs.argMs = Ms_
	addDemagBoundaryCorrArgs.argMsMul = Ms_mul
	addDemagBoundaryCorrArgs.argPhi = phi
	addDemagBoundaryCorrArgs.argTargetIdx = targetIdx
	addDemagBoundaryCorrArgs.argSourceIdx = sourceIdx
	addDemagBoundaryCorrArgs.argTensor = tensor
	addDemagBoundaryCorrArgs.argStencilCount = stencilCount
	addDemagBoundaryCorrArgs.argNTarget = nTarget
	
	args := addDemagBoundaryCorrArgs.argptr[:]
	cu.LaunchKernel(addDemagBoundaryCorrCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("add_demag_boundary_corr")
	}
}

// maps compute capability on PTX code for add_demag_boundary_corr kernel.
var addDemagBoundaryCorrMap = map[int]string{
	0: "",
	52: addDemagBoundaryCorrPtx52,
}

// add_demag_boundary_corr PTX code for various compute capabilities.
const (
	addDemagBoundaryCorrPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	add_demag_boundary_corr

.visible .entry add_demag_boundary_corr(
	.param .u64 add_demag_boundary_corr_param_0,
	.param .u64 add_demag_boundary_corr_param_1,
	.param .u64 add_demag_boundary_corr_param_2,
	.param .u64 add_demag_boundary_corr_param_3,
	.param .u64 add_demag_boundary_corr_param_4,
	.param .u64 add_demag_boundary_corr_param_5,
	.param .u64 add_demag_boundary_corr_param_6,
	.param .f32 add_demag_boundary_corr_param_7,
	.param .u64 add_demag_boundary_corr_param_8,
	.param .u64 add_demag_boundary_corr_param_9,
	.param .u64 add_demag_boundary_corr_param_10,
	.param .u64 add_demag_boundary_corr_param_11,
	.param .u32 add_demag_boundary_corr_param_12,
	.param .u32 add_demag_boundary_corr_param_13
)
{
	.reg .pred 	%p<39>;
	.reg .f32 	%f<272>;
	.reg .b32 	%r<46>;
	.reg .b64 	%rd<96>;


	ld.param.u64 	%rd19, [add_demag_boundary_corr_param_0];
	ld.param.u64 	%rd20, [add_demag_boundary_corr_param_1];
	ld.param.u64 	%rd21, [add_demag_boundary_corr_param_2];
	ld.param.u64 	%rd24, [add_demag_boundary_corr_param_3];
	ld.param.u64 	%rd25, [add_demag_boundary_corr_param_4];
	ld.param.u64 	%rd26, [add_demag_boundary_corr_param_5];
	ld.param.u64 	%rd22, [add_demag_boundary_corr_param_6];
	ld.param.f32 	%f79, [add_demag_boundary_corr_param_7];
	ld.param.u64 	%rd27, [add_demag_boundary_corr_param_8];
	ld.param.u64 	%rd23, [add_demag_boundary_corr_param_9];
	ld.param.u64 	%rd28, [add_demag_boundary_corr_param_10];
	ld.param.u64 	%rd29, [add_demag_boundary_corr_param_11];
	ld.param.u32 	%r18, [add_demag_boundary_corr_param_12];
	ld.param.u32 	%r19, [add_demag_boundary_corr_param_13];
	cvta.to.global.u64 	%rd1, %rd29;
	cvta.to.global.u64 	%rd2, %rd22;
	cvta.to.global.u64 	%rd3, %rd26;
	cvta.to.global.u64 	%rd4, %rd25;
	cvta.to.global.u64 	%rd5, %rd24;
	cvta.to.global.u64 	%rd6, %rd28;
	cvta.to.global.u64 	%rd7, %rd27;
	mov.u32 	%r20, %ntid.x;
	mov.u32 	%r21, %ctaid.x;
	mov.u32 	%r22, %tid.x;
	mad.lo.s32 	%r1, %r21, %r20, %r22;
	setp.ge.s32 	%p1, %r1, %r19;
	@%p1 bra 	$L__BB0_41;

	cvta.to.global.u64 	%rd30, %rd23;
	mul.wide.s32 	%rd31, %r1, 4;
	add.s64 	%rd32, %rd30, %rd31;
	ld.global.nc.u32 	%r23, [%rd32];
	cvt.s64.s32 	%rd8, %r23;
	setp.lt.s32 	%p2, %r23, 0;
	@%p2 bra 	$L__BB0_41;

	shl.b64 	%rd33, %rd8, 2;
	add.s64 	%rd34, %rd7, %rd33;
	ld.global.nc.f32 	%f80, [%rd34];
	setp.le.f32 	%p3, %f80, 0f00000000;
	@%p3 bra 	$L__BB0_41;

	mul.lo.s32 	%r2, %r1, %r18;
	setp.lt.s32 	%p4, %r18, 1;
	mov.f32 	%f269, 0f00000000;
	mov.f32 	%f270, %f269;
	mov.f32 	%f271, %f269;
	@%p4 bra 	$L__BB0_40;

	setp.eq.s64 	%p5, %rd22, 0;
	and.b32  	%r3, %r18, 1;
	@%p5 bra 	$L__BB0_24;

	setp.eq.s32 	%p6, %r18, 1;
	mov.f32 	%f271, 0f00000000;
	mov.u32 	%r42, 0;
	mov.f32 	%f270, %f271;
	mov.f32 	%f269, %f271;
	@%p6 bra 	$L__BB0_18;

	sub.s32 	%r41, %r18, %r3;
	mov.f32 	%f271, 0f00000000;
	mov.u32 	%r42, 0;

$L__BB0_7:
	add.s32 	%r26, %r42, %r2;
	mul.wide.s32 	%rd35, %r26, 4;
	add.s64 	%rd9, %rd6, %rd35;
	ld.global.nc.u32 	%r27, [%rd9];
	cvt.s64.s32 	%rd10, %r27;
	setp.lt.s32 	%p7, %r27, 0;
	mul.lo.s32 	%r28, %r26, 6;
	mul.wide.s32 	%rd36, %r28, 4;
	add.s64 	%rd11, %rd1, %rd36;
	@%p7 bra 	$L__BB0_12;

	shl.b64 	%rd37, %rd10, 2;
	add.s64 	%rd38, %rd7, %rd37;
	ld.global.nc.f32 	%f4, [%rd38];
	setp.le.f32 	%p8, %f4, 0f00000000;
	@%p8 bra 	$L__BB0_12;

	add.s64 	%rd40, %rd5, %rd37;
	ld.global.nc.f32 	%f5, [%rd40];
	add.s64 	%rd41, %rd4, %rd37;
	ld.global.nc.f32 	%f6, [%rd41];
	mul.f32 	%f91, %f6, %f6;
	fma.rn.f32 	%f92, %f5, %f5, %f91;
	add.s64 	%rd42, %rd3, %rd37;
	ld.global.nc.f32 	%f7, [%rd42];
	fma.rn.f32 	%f93, %f7, %f7, %f92;
	setp.eq.f32 	%p9, %f93, 0f00000000;
	@%p9 bra 	$L__BB0_12;

	add.s64 	%rd44, %rd2, %rd37;
	ld.global.nc.f32 	%f94, [%rd44];
	mul.f32 	%f8, %f94, %f79;
	setp.eq.f32 	%p10, %f8, 0f00000000;
	@%p10 bra 	$L__BB0_12;

	mul.f32 	%f95, %f4, %f8;
	mul.f32 	%f96, %f5, %f95;
	mul.f32 	%f97, %f6, %f95;
	mul.f32 	%f98, %f7, %f95;
	ld.global.nc.f32 	%f99, [%rd11];
	ld.global.nc.f32 	%f100, [%rd11+4];
	mul.f32 	%f101, %f97, %f100;
	fma.rn.f32 	%f102, %f96, %f99, %f101;
	ld.global.nc.f32 	%f103, [%rd11+8];
	fma.rn.f32 	%f104, %f98, %f103, %f102;
	add.f32 	%f269, %f269, %f104;
	ld.global.nc.f32 	%f105, [%rd11+12];
	mul.f32 	%f106, %f97, %f105;
	fma.rn.f32 	%f107, %f96, %f100, %f106;
	ld.global.nc.f32 	%f108, [%rd11+16];
	fma.rn.f32 	%f109, %f98, %f108, %f107;
	add.f32 	%f270, %f270, %f109;
	mul.f32 	%f110, %f97, %f108;
	fma.rn.f32 	%f111, %f96, %f103, %f110;
	ld.global.nc.f32 	%f112, [%rd11+20];
	fma.rn.f32 	%f113, %f98, %f112, %f111;
	add.f32 	%f271, %f271, %f113;

$L__BB0_12:
	ld.global.nc.u32 	%r29, [%rd9+4];
	cvt.s64.s32 	%rd12, %r29;
	setp.lt.s32 	%p11, %r29, 0;
	@%p11 bra 	$L__BB0_17;

	shl.b64 	%rd45, %rd12, 2;
	add.s64 	%rd46, %rd7, %rd45;
	ld.global.nc.f32 	%f15, [%rd46];
	setp.le.f32 	%p12, %f15, 0f00000000;
	@%p12 bra 	$L__BB0_17;

	add.s64 	%rd48, %rd5, %rd45;
	ld.global.nc.f32 	%f16, [%rd48];
	add.s64 	%rd49, %rd4, %rd45;
	ld.global.nc.f32 	%f17, [%rd49];
	mul.f32 	%f114, %f17, %f17;
	fma.rn.f32 	%f115, %f16, %f16, %f114;
	add.s64 	%rd50, %rd3, %rd45;
	ld.global.nc.f32 	%f18, [%rd50];
	fma.rn.f32 	%f116, %f18, %f18, %f115;
	setp.eq.f32 	%p13, %f116, 0f00000000;
	@%p13 bra 	$L__BB0_17;

	add.s64 	%rd52, %rd2, %rd45;
	ld.global.nc.f32 	%f117, [%rd52];
	mul.f32 	%f19, %f117, %f79;
	setp.eq.f32 	%p14, %f19, 0f00000000;
	@%p14 bra 	$L__BB0_17;

	mul.f32 	%f118, %f15, %f19;
	mul.f32 	%f119, %f16, %f118;
	mul.f32 	%f120, %f17, %f118;
	mul.f32 	%f121, %f18, %f118;
	ld.global.nc.f32 	%f122, [%rd11+24];
	ld.global.nc.f32 	%f123, [%rd11+28];
	mul.f32 	%f124, %f120, %f123;
	fma.rn.f32 	%f125, %f119, %f122, %f124;
	ld.global.nc.f32 	%f126, [%rd11+32];
	fma.rn.f32 	%f127, %f121, %f126, %f125;
	add.f32 	%f269, %f269, %f127;
	ld.global.nc.f32 	%f128, [%rd11+36];
	mul.f32 	%f129, %f120, %f128;
	fma.rn.f32 	%f130, %f119, %f123, %f129;
	ld.global.nc.f32 	%f131, [%rd11+40];
	fma.rn.f32 	%f132, %f121, %f131, %f130;
	add.f32 	%f270, %f270, %f132;
	mul.f32 	%f133, %f120, %f131;
	fma.rn.f32 	%f134, %f119, %f126, %f133;
	ld.global.nc.f32 	%f135, [%rd11+44];
	fma.rn.f32 	%f136, %f121, %f135, %f134;
	add.f32 	%f271, %f271, %f136;

$L__BB0_17:
	add.s32 	%r42, %r42, 2;
	add.s32 	%r41, %r41, -2;
	setp.ne.s32 	%p15, %r41, 0;
	@%p15 bra 	$L__BB0_7;

$L__BB0_18:
	setp.eq.s32 	%p16, %r3, 0;
	@%p16 bra 	$L__BB0_40;

	add.s32 	%r10, %r42, %r2;
	mul.wide.s32 	%rd53, %r10, 4;
	add.s64 	%rd54, %rd6, %rd53;
	ld.global.nc.u32 	%r30, [%rd54];
	cvt.s64.s32 	%rd13, %r30;
	setp.lt.s32 	%p17, %r30, 0;
	@%p17 bra 	$L__BB0_40;

	shl.b64 	%rd55, %rd13, 2;
	add.s64 	%rd56, %rd7, %rd55;
	ld.global.nc.f32 	%f32, [%rd56];
	setp.le.f32 	%p18, %f32, 0f00000000;
	@%p18 bra 	$L__BB0_40;

	add.s64 	%rd58, %rd5, %rd55;
	ld.global.nc.f32 	%f33, [%rd58];
	add.s64 	%rd59, %rd4, %rd55;
	ld.global.nc.f32 	%f34, [%rd59];
	mul.f32 	%f137, %f34, %f34;
	fma.rn.f32 	%f138, %f33, %f33, %f137;
	add.s64 	%rd60, %rd3, %rd55;
	ld.global.nc.f32 	%f35, [%rd60];
	fma.rn.f32 	%f139, %f35, %f35, %f138;
	setp.eq.f32 	%p19, %f139, 0f00000000;
	@%p19 bra 	$L__BB0_40;

	add.s64 	%rd62, %rd2, %rd55;
	ld.global.nc.f32 	%f140, [%rd62];
	mul.f32 	%f36, %f140, %f79;
	setp.eq.f32 	%p20, %f36, 0f00000000;
	@%p20 bra 	$L__BB0_40;

	mul.f32 	%f141, %f32, %f36;
	mul.f32 	%f142, %f33, %f141;
	mul.f32 	%f143, %f34, %f141;
	mul.f32 	%f144, %f35, %f141;
	mul.lo.s32 	%r31, %r10, 6;
	mul.wide.s32 	%rd63, %r31, 4;
	add.s64 	%rd64, %rd1, %rd63;
	ld.global.nc.f32 	%f145, [%rd64];
	ld.global.nc.f32 	%f146, [%rd64+4];
	mul.f32 	%f147, %f143, %f146;
	fma.rn.f32 	%f148, %f142, %f145, %f147;
	ld.global.nc.f32 	%f149, [%rd64+8];
	fma.rn.f32 	%f150, %f144, %f149, %f148;
	add.f32 	%f269, %f269, %f150;
	ld.global.nc.f32 	%f151, [%rd64+12];
	mul.f32 	%f152, %f143, %f151;
	fma.rn.f32 	%f153, %f142, %f146, %f152;
	ld.global.nc.f32 	%f154, [%rd64+16];
	fma.rn.f32 	%f155, %f144, %f154, %f153;
	add.f32 	%f270, %f270, %f155;
	mul.f32 	%f156, %f143, %f154;
	fma.rn.f32 	%f157, %f142, %f149, %f156;
	ld.global.nc.f32 	%f158, [%rd64+20];
	fma.rn.f32 	%f159, %f144, %f158, %f157;
	add.f32 	%f271, %f271, %f159;
	bra.uni 	$L__BB0_40;

$L__BB0_24:
	setp.eq.s32 	%p21, %r18, 1;
	mov.f32 	%f271, 0f00000000;
	mov.u32 	%r45, 0;
	mov.f32 	%f270, %f271;
	mov.f32 	%f269, %f271;
	@%p21 bra 	$L__BB0_35;

	sub.s32 	%r44, %r18, %r3;
	mov.f32 	%f271, 0f00000000;
	mov.u32 	%r45, 0;

$L__BB0_26:
	add.s32 	%r34, %r45, %r2;
	mul.wide.s32 	%rd65, %r34, 4;
	add.s64 	%rd14, %rd6, %rd65;
	ld.global.nc.u32 	%r35, [%rd14];
	cvt.s64.s32 	%rd15, %r35;
	setp.lt.s32 	%p22, %r35, 0;
	mul.lo.s32 	%r36, %r34, 6;
	mul.wide.s32 	%rd66, %r36, 4;
	add.s64 	%rd16, %rd1, %rd66;
	@%p22 bra 	$L__BB0_30;

	shl.b64 	%rd67, %rd15, 2;
	add.s64 	%rd68, %rd7, %rd67;
	ld.global.nc.f32 	%f43, [%rd68];
	setp.le.f32 	%p23, %f43, 0f00000000;
	@%p23 bra 	$L__BB0_30;

	setp.eq.f32 	%p24, %f79, 0f00000000;
	add.s64 	%rd70, %rd5, %rd67;
	ld.global.nc.f32 	%f44, [%rd70];
	add.s64 	%rd71, %rd4, %rd67;
	ld.global.nc.f32 	%f45, [%rd71];
	mul.f32 	%f167, %f45, %f45;
	fma.rn.f32 	%f168, %f44, %f44, %f167;
	add.s64 	%rd72, %rd3, %rd67;
	ld.global.nc.f32 	%f46, [%rd72];
	fma.rn.f32 	%f169, %f46, %f46, %f168;
	setp.eq.f32 	%p25, %f169, 0f00000000;
	or.pred  	%p26, %p25, %p24;
	@%p26 bra 	$L__BB0_30;

	mul.f32 	%f170, %f43, %f79;
	mul.f32 	%f171, %f44, %f170;
	mul.f32 	%f172, %f45, %f170;
	mul.f32 	%f173, %f46, %f170;
	ld.global.nc.f32 	%f174, [%rd16];
	ld.global.nc.f32 	%f175, [%rd16+4];
	mul.f32 	%f176, %f172, %f175;
	fma.rn.f32 	%f177, %f171, %f174, %f176;
	ld.global.nc.f32 	%f178, [%rd16+8];
	fma.rn.f32 	%f179, %f173, %f178, %f177;
	add.f32 	%f269, %f269, %f179;
	ld.global.nc.f32 	%f180, [%rd16+12];
	mul.f32 	%f181, %f172, %f180;
	fma.rn.f32 	%f182, %f171, %f175, %f181;
	ld.global.nc.f32 	%f183, [%rd16+16];
	fma.rn.f32 	%f184, %f173, %f183, %f182;
	add.f32 	%f270, %f270, %f184;
	mul.f32 	%f185, %f172, %f183;
	fma.rn.f32 	%f186, %f171, %f178, %f185;
	ld.global.nc.f32 	%f187, [%rd16+20];
	fma.rn.f32 	%f188, %f173, %f187, %f186;
	add.f32 	%f271, %f271, %f188;

$L__BB0_30:
	ld.global.nc.u32 	%r37, [%rd14+4];
	cvt.s64.s32 	%rd17, %r37;
	setp.lt.s32 	%p27, %r37, 0;
	@%p27 bra 	$L__BB0_34;

	shl.b64 	%rd73, %rd17, 2;
	add.s64 	%rd74, %rd7, %rd73;
	ld.global.nc.f32 	%f53, [%rd74];
	setp.le.f32 	%p28, %f53, 0f00000000;
	@%p28 bra 	$L__BB0_34;

	setp.eq.f32 	%p29, %f79, 0f00000000;
	add.s64 	%rd76, %rd5, %rd73;
	ld.global.nc.f32 	%f54, [%rd76];
	add.s64 	%rd77, %rd4, %rd73;
	ld.global.nc.f32 	%f55, [%rd77];
	mul.f32 	%f189, %f55, %f55;
	fma.rn.f32 	%f190, %f54, %f54, %f189;
	add.s64 	%rd78, %rd3, %rd73;
	ld.global.nc.f32 	%f56, [%rd78];
	fma.rn.f32 	%f191, %f56, %f56, %f190;
	setp.eq.f32 	%p30, %f191, 0f00000000;
	or.pred  	%p31, %p30, %p29;
	@%p31 bra 	$L__BB0_34;

	mul.f32 	%f192, %f53, %f79;
	mul.f32 	%f193, %f54, %f192;
	mul.f32 	%f194, %f55, %f192;
	mul.f32 	%f195, %f56, %f192;
	ld.global.nc.f32 	%f196, [%rd16+24];
	ld.global.nc.f32 	%f197, [%rd16+28];
	mul.f32 	%f198, %f194, %f197;
	fma.rn.f32 	%f199, %f193, %f196, %f198;
	ld.global.nc.f32 	%f200, [%rd16+32];
	fma.rn.f32 	%f201, %f195, %f200, %f199;
	add.f32 	%f269, %f269, %f201;
	ld.global.nc.f32 	%f202, [%rd16+36];
	mul.f32 	%f203, %f194, %f202;
	fma.rn.f32 	%f204, %f193, %f197, %f203;
	ld.global.nc.f32 	%f205, [%rd16+40];
	fma.rn.f32 	%f206, %f195, %f205, %f204;
	add.f32 	%f270, %f270, %f206;
	mul.f32 	%f207, %f194, %f205;
	fma.rn.f32 	%f208, %f193, %f200, %f207;
	ld.global.nc.f32 	%f209, [%rd16+44];
	fma.rn.f32 	%f210, %f195, %f209, %f208;
	add.f32 	%f271, %f271, %f210;

$L__BB0_34:
	add.s32 	%r45, %r45, 2;
	add.s32 	%r44, %r44, -2;
	setp.ne.s32 	%p32, %r44, 0;
	@%p32 bra 	$L__BB0_26;

$L__BB0_35:
	setp.eq.s32 	%p33, %r3, 0;
	@%p33 bra 	$L__BB0_40;

	add.s32 	%r17, %r45, %r2;
	mul.wide.s32 	%rd79, %r17, 4;
	add.s64 	%rd80, %rd6, %rd79;
	ld.global.nc.u32 	%r38, [%rd80];
	cvt.s64.s32 	%rd18, %r38;
	setp.lt.s32 	%p34, %r38, 0;
	@%p34 bra 	$L__BB0_40;

	shl.b64 	%rd81, %rd18, 2;
	add.s64 	%rd82, %rd7, %rd81;
	ld.global.nc.f32 	%f69, [%rd82];
	setp.le.f32 	%p35, %f69, 0f00000000;
	@%p35 bra 	$L__BB0_40;

	add.s64 	%rd84, %rd5, %rd81;
	ld.global.nc.f32 	%f70, [%rd84];
	add.s64 	%rd85, %rd4, %rd81;
	ld.global.nc.f32 	%f71, [%rd85];
	mul.f32 	%f211, %f71, %f71;
	fma.rn.f32 	%f212, %f70, %f70, %f211;
	add.s64 	%rd86, %rd3, %rd81;
	ld.global.nc.f32 	%f72, [%rd86];
	fma.rn.f32 	%f213, %f72, %f72, %f212;
	setp.eq.f32 	%p36, %f213, 0f00000000;
	setp.eq.f32 	%p37, %f79, 0f00000000;
	or.pred  	%p38, %p36, %p37;
	@%p38 bra 	$L__BB0_40;

	mul.f32 	%f214, %f69, %f79;
	mul.f32 	%f215, %f70, %f214;
	mul.f32 	%f216, %f71, %f214;
	mul.f32 	%f217, %f72, %f214;
	mul.lo.s32 	%r39, %r17, 6;
	mul.wide.s32 	%rd87, %r39, 4;
	add.s64 	%rd88, %rd1, %rd87;
	ld.global.nc.f32 	%f218, [%rd88];
	ld.global.nc.f32 	%f219, [%rd88+4];
	mul.f32 	%f220, %f216, %f219;
	fma.rn.f32 	%f221, %f215, %f218, %f220;
	ld.global.nc.f32 	%f222, [%rd88+8];
	fma.rn.f32 	%f223, %f217, %f222, %f221;
	add.f32 	%f269, %f269, %f223;
	ld.global.nc.f32 	%f224, [%rd88+12];
	mul.f32 	%f225, %f216, %f224;
	fma.rn.f32 	%f226, %f215, %f219, %f225;
	ld.global.nc.f32 	%f227, [%rd88+16];
	fma.rn.f32 	%f228, %f217, %f227, %f226;
	add.f32 	%f270, %f270, %f228;
	mul.f32 	%f229, %f216, %f227;
	fma.rn.f32 	%f230, %f215, %f222, %f229;
	ld.global.nc.f32 	%f231, [%rd88+20];
	fma.rn.f32 	%f232, %f217, %f231, %f230;
	add.f32 	%f271, %f271, %f232;

$L__BB0_40:
	cvta.to.global.u64 	%rd89, %rd19;
	add.s64 	%rd91, %rd89, %rd33;
	ld.global.f32 	%f233, [%rd91];
	add.f32 	%f234, %f269, %f233;
	st.global.f32 	[%rd91], %f234;
	cvta.to.global.u64 	%rd92, %rd20;
	add.s64 	%rd93, %rd92, %rd33;
	ld.global.f32 	%f235, [%rd93];
	add.f32 	%f236, %f270, %f235;
	st.global.f32 	[%rd93], %f236;
	cvta.to.global.u64 	%rd94, %rd21;
	add.s64 	%rd95, %rd94, %rd33;
	ld.global.f32 	%f237, [%rd95];
	add.f32 	%f238, %f271, %f237;
	st.global.f32 	[%rd95], %f238;

$L__BB0_41:
	ret;

}

`
	)
