package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for adddmi kernel
var adddmiCode cu.Function

// Stores the arguments for adddmi kernel invocation
type adddmiArgsT struct {
	argHx unsafe.Pointer
	argHy unsafe.Pointer
	argHz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argMs unsafe.Pointer
	argMsMul float32
	argVol unsafe.Pointer
	argFxm unsafe.Pointer
	argFxp unsafe.Pointer
	argFym unsafe.Pointer
	argFyp unsafe.Pointer
	argFzm unsafe.Pointer
	argFzp unsafe.Pointer
	argALUT2d unsafe.Pointer
	argDLUT2d unsafe.Pointer
	argRegions unsafe.Pointer
	argCx float32
	argCy float32
	argCz float32
	argPhiFloor float32
	argNx int
	argNy int
	argNz int
	argPBC byte
	argOpenBC byte
	argptr [27]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for adddmi kernel invocation
var adddmiArgs adddmiArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	adddmiArgs.argptr[0] = unsafe.Pointer(&adddmiArgs.argHx)
	adddmiArgs.argptr[1] = unsafe.Pointer(&adddmiArgs.argHy)
	adddmiArgs.argptr[2] = unsafe.Pointer(&adddmiArgs.argHz)
	adddmiArgs.argptr[3] = unsafe.Pointer(&adddmiArgs.argMx)
	adddmiArgs.argptr[4] = unsafe.Pointer(&adddmiArgs.argMy)
	adddmiArgs.argptr[5] = unsafe.Pointer(&adddmiArgs.argMz)
	adddmiArgs.argptr[6] = unsafe.Pointer(&adddmiArgs.argMs)
	adddmiArgs.argptr[7] = unsafe.Pointer(&adddmiArgs.argMsMul)
	adddmiArgs.argptr[8] = unsafe.Pointer(&adddmiArgs.argVol)
	adddmiArgs.argptr[9] = unsafe.Pointer(&adddmiArgs.argFxm)
	adddmiArgs.argptr[10] = unsafe.Pointer(&adddmiArgs.argFxp)
	adddmiArgs.argptr[11] = unsafe.Pointer(&adddmiArgs.argFym)
	adddmiArgs.argptr[12] = unsafe.Pointer(&adddmiArgs.argFyp)
	adddmiArgs.argptr[13] = unsafe.Pointer(&adddmiArgs.argFzm)
	adddmiArgs.argptr[14] = unsafe.Pointer(&adddmiArgs.argFzp)
	adddmiArgs.argptr[15] = unsafe.Pointer(&adddmiArgs.argALUT2d)
	adddmiArgs.argptr[16] = unsafe.Pointer(&adddmiArgs.argDLUT2d)
	adddmiArgs.argptr[17] = unsafe.Pointer(&adddmiArgs.argRegions)
	adddmiArgs.argptr[18] = unsafe.Pointer(&adddmiArgs.argCx)
	adddmiArgs.argptr[19] = unsafe.Pointer(&adddmiArgs.argCy)
	adddmiArgs.argptr[20] = unsafe.Pointer(&adddmiArgs.argCz)
	adddmiArgs.argptr[21] = unsafe.Pointer(&adddmiArgs.argPhiFloor)
	adddmiArgs.argptr[22] = unsafe.Pointer(&adddmiArgs.argNx)
	adddmiArgs.argptr[23] = unsafe.Pointer(&adddmiArgs.argNy)
	adddmiArgs.argptr[24] = unsafe.Pointer(&adddmiArgs.argNz)
	adddmiArgs.argptr[25] = unsafe.Pointer(&adddmiArgs.argPBC)
	adddmiArgs.argptr[26] = unsafe.Pointer(&adddmiArgs.argOpenBC)
	}

// Wrapper for adddmi CUDA kernel, asynchronous.
func kAdddmiAsync(Hx unsafe.Pointer, Hy unsafe.Pointer, Hz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, vol unsafe.Pointer, fxm unsafe.Pointer, fxp unsafe.Pointer, fym unsafe.Pointer, fyp unsafe.Pointer, fzm unsafe.Pointer, fzp unsafe.Pointer, aLUT2d unsafe.Pointer, dLUT2d unsafe.Pointer, regions unsafe.Pointer, cx float32, cy float32, cz float32, phiFloor float32, Nx int, Ny int, Nz int, PBC byte, OpenBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("adddmi")
	}

	adddmiArgs.Lock()
	defer adddmiArgs.Unlock()

	if adddmiCode == 0 {
		adddmiCode = fatbinLoad(adddmiMap, "adddmi")
	}

	adddmiArgs.argHx = Hx
	adddmiArgs.argHy = Hy
	adddmiArgs.argHz = Hz
	adddmiArgs.argMx = mx
	adddmiArgs.argMy = my
	adddmiArgs.argMz = mz
	adddmiArgs.argMs = Ms_
	adddmiArgs.argMsMul = Ms_mul
	adddmiArgs.argVol = vol
	adddmiArgs.argFxm = fxm
	adddmiArgs.argFxp = fxp
	adddmiArgs.argFym = fym
	adddmiArgs.argFyp = fyp
	adddmiArgs.argFzm = fzm
	adddmiArgs.argFzp = fzp
	adddmiArgs.argALUT2d = aLUT2d
	adddmiArgs.argDLUT2d = dLUT2d
	adddmiArgs.argRegions = regions
	adddmiArgs.argCx = cx
	adddmiArgs.argCy = cy
	adddmiArgs.argCz = cz
	adddmiArgs.argPhiFloor = phiFloor
	adddmiArgs.argNx = Nx
	adddmiArgs.argNy = Ny
	adddmiArgs.argNz = Nz
	adddmiArgs.argPBC = PBC
	adddmiArgs.argOpenBC = OpenBC
	
	args := adddmiArgs.argptr[:]
	cu.LaunchKernel(adddmiCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("adddmi")
	}
}

// maps compute capability on PTX code for adddmi kernel.
var adddmiMap = map[int]string{
	0: "",
	52: adddmiPtx52,
}

// adddmi PTX code for various compute capabilities.
const (
	adddmiPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	adddmi

.visible .entry adddmi(
	.param .u64 adddmi_param_0,
	.param .u64 adddmi_param_1,
	.param .u64 adddmi_param_2,
	.param .u64 adddmi_param_3,
	.param .u64 adddmi_param_4,
	.param .u64 adddmi_param_5,
	.param .u64 adddmi_param_6,
	.param .f32 adddmi_param_7,
	.param .u64 adddmi_param_8,
	.param .u64 adddmi_param_9,
	.param .u64 adddmi_param_10,
	.param .u64 adddmi_param_11,
	.param .u64 adddmi_param_12,
	.param .u64 adddmi_param_13,
	.param .u64 adddmi_param_14,
	.param .u64 adddmi_param_15,
	.param .u64 adddmi_param_16,
	.param .u64 adddmi_param_17,
	.param .f32 adddmi_param_18,
	.param .f32 adddmi_param_19,
	.param .f32 adddmi_param_20,
	.param .f32 adddmi_param_21,
	.param .u32 adddmi_param_22,
	.param .u32 adddmi_param_23,
	.param .u32 adddmi_param_24,
	.param .u8 adddmi_param_25,
	.param .u8 adddmi_param_26
)
{
	.reg .pred 	%p<109>;
	.reg .b16 	%rs<55>;
	.reg .f32 	%f<581>;
	.reg .b32 	%r<224>;
	.reg .b64 	%rd<150>;


	ld.param.u64 	%rd25, [adddmi_param_3];
	ld.param.u64 	%rd26, [adddmi_param_4];
	ld.param.u64 	%rd27, [adddmi_param_5];
	ld.param.u64 	%rd19, [adddmi_param_9];
	ld.param.u64 	%rd20, [adddmi_param_10];
	ld.param.u64 	%rd21, [adddmi_param_11];
	ld.param.u64 	%rd22, [adddmi_param_12];
	ld.param.u64 	%rd28, [adddmi_param_15];
	ld.param.u64 	%rd30, [adddmi_param_17];
	ld.param.u32 	%r73, [adddmi_param_22];
	ld.param.u32 	%r74, [adddmi_param_23];
	ld.param.u32 	%r75, [adddmi_param_24];
	cvta.to.global.u64 	%rd2, %rd28;
	cvta.to.global.u64 	%rd3, %rd30;
	cvta.to.global.u64 	%rd4, %rd27;
	cvta.to.global.u64 	%rd5, %rd26;
	cvta.to.global.u64 	%rd6, %rd25;
	mov.u32 	%r76, %ntid.x;
	mov.u32 	%r77, %ctaid.x;
	mov.u32 	%r78, %tid.x;
	mad.lo.s32 	%r1, %r77, %r76, %r78;
	mov.u32 	%r79, %ntid.y;
	mov.u32 	%r80, %ctaid.y;
	mov.u32 	%r81, %tid.y;
	mad.lo.s32 	%r2, %r80, %r79, %r81;
	mov.u32 	%r82, %ntid.z;
	mov.u32 	%r83, %ctaid.z;
	mov.u32 	%r84, %tid.z;
	mad.lo.s32 	%r3, %r83, %r82, %r84;
	setp.ge.s32 	%p7, %r1, %r73;
	setp.ge.s32 	%p8, %r2, %r74;
	or.pred  	%p9, %p7, %p8;
	setp.ge.s32 	%p10, %r3, %r75;
	or.pred  	%p11, %p9, %p10;
	@%p11 bra 	$L__BB0_111;

	mul.lo.s32 	%r4, %r3, %r74;
	add.s32 	%r85, %r4, %r2;
	mul.lo.s32 	%r5, %r85, %r73;
	add.s32 	%r86, %r5, %r1;
	cvt.s64.s32 	%rd7, %r86;
	mul.wide.s32 	%rd31, %r86, 4;
	add.s64 	%rd32, %rd6, %rd31;
	add.s64 	%rd33, %rd5, %rd31;
	add.s64 	%rd34, %rd4, %rd31;
	add.s64 	%rd35, %rd3, %rd7;
	ld.global.nc.u8 	%rs12, [%rd35];
	cvt.u32.u16 	%r87, %rs12;
	and.b32  	%r6, %r87, 255;
	ld.global.nc.f32 	%f1, [%rd32];
	ld.global.nc.f32 	%f2, [%rd33];
	mul.f32 	%f159, %f2, %f2;
	fma.rn.f32 	%f160, %f1, %f1, %f159;
	ld.global.nc.f32 	%f3, [%rd34];
	fma.rn.f32 	%f161, %f3, %f3, %f160;
	setp.eq.f32 	%p12, %f161, 0f00000000;
	@%p12 bra 	$L__BB0_111;

	ld.param.u64 	%rd145, [adddmi_param_8];
	cvta.to.global.u64 	%rd36, %rd145;
	shl.b64 	%rd37, %rd7, 2;
	add.s64 	%rd38, %rd36, %rd37;
	ld.global.nc.f32 	%f4, [%rd38];
	setp.le.f32 	%p13, %f4, 0f00000000;
	@%p13 bra 	$L__BB0_111;

	ld.param.u8 	%rs47, [adddmi_param_25];
	ld.param.u64 	%rd147, [adddmi_param_14];
	ld.param.u64 	%rd146, [adddmi_param_13];
	ld.param.f32 	%f529, [adddmi_param_21];
	mov.f32 	%f165, 0f358637BD;
	max.f32 	%f166, %f529, %f165;
	max.f32 	%f167, %f4, %f166;
	rcp.rn.f32 	%f5, %f167;
	cvta.to.global.u64 	%rd39, %rd19;
	add.s64 	%rd41, %rd39, %rd37;
	ld.global.nc.f32 	%f6, [%rd41];
	cvta.to.global.u64 	%rd42, %rd20;
	add.s64 	%rd43, %rd42, %rd37;
	ld.global.nc.f32 	%f7, [%rd43];
	cvta.to.global.u64 	%rd44, %rd21;
	add.s64 	%rd45, %rd44, %rd37;
	ld.global.nc.f32 	%f8, [%rd45];
	cvta.to.global.u64 	%rd46, %rd22;
	add.s64 	%rd47, %rd46, %rd37;
	ld.global.nc.f32 	%f9, [%rd47];
	cvta.to.global.u64 	%rd48, %rd146;
	add.s64 	%rd49, %rd48, %rd37;
	ld.global.nc.f32 	%f10, [%rd49];
	cvta.to.global.u64 	%rd50, %rd147;
	add.s64 	%rd51, %rd50, %rd37;
	ld.global.nc.f32 	%f11, [%rd51];
	and.b16  	%rs1, %rs47, 1;
	setp.eq.s16 	%p14, %rs1, 0;
	mov.u16 	%rs50, 0;
	setp.lt.s32 	%p15, %r1, 1;
	mov.f32 	%f531, 0f00000000;
	and.pred  	%p16, %p15, %p14;
	mov.f32 	%f532, %f531;
	mov.f32 	%f533, %f531;
	mov.u16 	%rs49, %rs50;
	mov.u32 	%r203, %r6;
	@%p16 bra 	$L__BB0_9;

	add.s32 	%r7, %r1, -1;
	@%p14 bra 	$L__BB0_6;
	bra.uni 	$L__BB0_5;

$L__BB0_6:
	max.s32 	%r202, %r7, 0;
	bra.uni 	$L__BB0_7;

$L__BB0_5:
	rem.s32 	%r88, %r7, %r73;
	add.s32 	%r89, %r88, %r73;
	rem.s32 	%r202, %r89, %r73;

$L__BB0_7:
	add.s32 	%r90, %r202, %r5;
	cvt.s64.s32 	%rd8, %r90;
	mul.wide.s32 	%rd52, %r90, 4;
	add.s64 	%rd53, %rd6, %rd52;
	add.s64 	%rd54, %rd5, %rd52;
	add.s64 	%rd55, %rd4, %rd52;
	ld.global.nc.f32 	%f533, [%rd55];
	ld.global.nc.f32 	%f531, [%rd53];
	ld.global.nc.f32 	%f532, [%rd54];
	mul.f32 	%f168, %f532, %f532;
	fma.rn.f32 	%f169, %f531, %f531, %f168;
	fma.rn.f32 	%f170, %f533, %f533, %f169;
	setp.eq.f32 	%p18, %f170, 0f00000000;
	mov.u16 	%rs49, %rs50;
	mov.u32 	%r203, %r6;
	@%p18 bra 	$L__BB0_9;

	add.s64 	%rd56, %rd3, %rd8;
	ld.global.nc.u8 	%rs16, [%rd56];
	cvt.u32.u16 	%r91, %rs16;
	and.b32  	%r203, %r91, 255;
	mov.u16 	%rs49, 1;

$L__BB0_9:
	mov.f32 	%f534, 0f00000000;
	add.s32 	%r13, %r1, 1;
	setp.ge.s32 	%p19, %r13, %r73;
	and.pred  	%p21, %p19, %p14;
	mov.f32 	%f535, %f534;
	mov.f32 	%f536, %f534;
	mov.u32 	%r205, %r6;
	@%p21 bra 	$L__BB0_15;

	@%p14 bra 	$L__BB0_12;
	bra.uni 	$L__BB0_11;

$L__BB0_12:
	add.s32 	%r94, %r73, -1;
	min.s32 	%r204, %r13, %r94;
	bra.uni 	$L__BB0_13;

$L__BB0_11:
	rem.s32 	%r92, %r13, %r73;
	add.s32 	%r93, %r92, %r73;
	rem.s32 	%r204, %r93, %r73;

$L__BB0_13:
	add.s32 	%r95, %r204, %r5;
	cvt.s64.s32 	%rd9, %r95;
	mul.wide.s32 	%rd57, %r95, 4;
	add.s64 	%rd58, %rd6, %rd57;
	add.s64 	%rd59, %rd5, %rd57;
	add.s64 	%rd60, %rd4, %rd57;
	ld.global.nc.f32 	%f536, [%rd60];
	ld.global.nc.f32 	%f534, [%rd58];
	ld.global.nc.f32 	%f535, [%rd59];
	mul.f32 	%f174, %f535, %f535;
	fma.rn.f32 	%f175, %f534, %f534, %f174;
	fma.rn.f32 	%f176, %f536, %f536, %f175;
	setp.eq.f32 	%p23, %f176, 0f00000000;
	mov.u32 	%r205, %r6;
	@%p23 bra 	$L__BB0_15;

	add.s64 	%rd61, %rd3, %rd9;
	ld.global.nc.u8 	%rs20, [%rd61];
	cvt.u32.u16 	%r96, %rs20;
	and.b32  	%r205, %r96, 255;
	mov.u16 	%rs50, 1;

$L__BB0_15:
	ld.param.u8 	%rs48, [adddmi_param_25];
	and.b16  	%rs4, %rs48, 2;
	setp.eq.s16 	%p24, %rs4, 0;
	mov.u16 	%rs51, 0;
	setp.lt.s32 	%p25, %r2, 1;
	mov.f32 	%f537, 0f00000000;
	and.pred  	%p26, %p25, %p24;
	mov.f32 	%f538, %f537;
	mov.f32 	%f539, %f537;
	mov.u32 	%r207, %r6;
	@%p26 bra 	$L__BB0_21;

	add.s32 	%r19, %r2, -1;
	@%p24 bra 	$L__BB0_18;
	bra.uni 	$L__BB0_17;

$L__BB0_18:
	max.s32 	%r206, %r19, 0;
	bra.uni 	$L__BB0_19;

$L__BB0_17:
	ld.param.u32 	%r200, [adddmi_param_23];
	rem.s32 	%r97, %r19, %r200;
	add.s32 	%r98, %r97, %r200;
	rem.s32 	%r206, %r98, %r200;

$L__BB0_19:
	ld.param.u32 	%r201, [adddmi_param_22];
	add.s32 	%r99, %r206, %r4;
	mad.lo.s32 	%r100, %r99, %r201, %r1;
	cvt.s64.s32 	%rd10, %r100;
	mul.wide.s32 	%rd62, %r100, 4;
	add.s64 	%rd63, %rd6, %rd62;
	add.s64 	%rd64, %rd5, %rd62;
	add.s64 	%rd65, %rd4, %rd62;
	ld.global.nc.f32 	%f539, [%rd65];
	ld.global.nc.f32 	%f537, [%rd63];
	ld.global.nc.f32 	%f538, [%rd64];
	mul.f32 	%f180, %f538, %f538;
	fma.rn.f32 	%f181, %f537, %f537, %f180;
	fma.rn.f32 	%f182, %f539, %f539, %f181;
	setp.eq.f32 	%p28, %f182, 0f00000000;
	mov.u32 	%r207, %r6;
	@%p28 bra 	$L__BB0_21;

	add.s64 	%rd66, %rd3, %rd10;
	ld.global.nc.u8 	%rs24, [%rd66];
	cvt.u32.u16 	%r101, %rs24;
	and.b32  	%r207, %r101, 255;
	mov.u16 	%rs51, 1;

$L__BB0_21:
	mov.f32 	%f540, 0f00000000;
	mov.u16 	%rs52, 0;
	ld.param.u32 	%r185, [adddmi_param_23];
	add.s32 	%r25, %r2, 1;
	setp.ge.s32 	%p29, %r25, %r185;
	and.pred  	%p31, %p29, %p24;
	mov.f32 	%f541, %f540;
	mov.f32 	%f542, %f540;
	mov.u32 	%r209, %r6;
	@%p31 bra 	$L__BB0_27;

	@%p24 bra 	$L__BB0_24;
	bra.uni 	$L__BB0_23;

$L__BB0_24:
	ld.param.u32 	%r191, [adddmi_param_23];
	add.s32 	%r104, %r191, -1;
	min.s32 	%r208, %r25, %r104;
	bra.uni 	$L__BB0_25;

$L__BB0_23:
	ld.param.u32 	%r189, [adddmi_param_23];
	rem.s32 	%r102, %r25, %r189;
	add.s32 	%r103, %r102, %r189;
	rem.s32 	%r208, %r103, %r189;

$L__BB0_25:
	mov.u16 	%rs52, 0;
	ld.param.u64 	%rd130, [adddmi_param_5];
	cvta.to.global.u64 	%rd129, %rd130;
	ld.param.u64 	%rd128, [adddmi_param_4];
	cvta.to.global.u64 	%rd127, %rd128;
	ld.param.u32 	%r190, [adddmi_param_22];
	add.s32 	%r105, %r208, %r4;
	mad.lo.s32 	%r106, %r105, %r190, %r1;
	cvt.s64.s32 	%rd11, %r106;
	mul.wide.s32 	%rd67, %r106, 4;
	add.s64 	%rd68, %rd6, %rd67;
	add.s64 	%rd69, %rd127, %rd67;
	add.s64 	%rd70, %rd129, %rd67;
	ld.global.nc.f32 	%f542, [%rd70];
	ld.global.nc.f32 	%f540, [%rd68];
	ld.global.nc.f32 	%f541, [%rd69];
	mul.f32 	%f186, %f541, %f541;
	fma.rn.f32 	%f187, %f540, %f540, %f186;
	fma.rn.f32 	%f188, %f542, %f542, %f187;
	setp.eq.f32 	%p33, %f188, 0f00000000;
	mov.u32 	%r209, %r6;
	@%p33 bra 	$L__BB0_27;

	ld.param.u64 	%rd138, [adddmi_param_17];
	cvta.to.global.u64 	%rd137, %rd138;
	add.s64 	%rd71, %rd137, %rd11;
	ld.global.nc.u8 	%rs28, [%rd71];
	cvt.u32.u16 	%r107, %rs28;
	and.b32  	%r209, %r107, 255;
	mov.u16 	%rs52, 1;

$L__BB0_27:
	ld.param.u8 	%rs44, [adddmi_param_25];
	and.b16  	%rs7, %rs44, 4;
	setp.eq.s16 	%p34, %rs7, 0;
	mov.u16 	%rs53, 0;
	setp.lt.s32 	%p35, %r3, 1;
	mov.f32 	%f543, 0f00000000;
	and.pred  	%p36, %p35, %p34;
	mov.f32 	%f544, %f543;
	mov.f32 	%f545, %f543;
	mov.u32 	%r211, %r6;
	@%p36 bra 	$L__BB0_33;

	add.s32 	%r31, %r3, -1;
	@%p34 bra 	$L__BB0_30;
	bra.uni 	$L__BB0_29;

$L__BB0_30:
	max.s32 	%r210, %r31, 0;
	bra.uni 	$L__BB0_31;

$L__BB0_29:
	ld.param.u32 	%r186, [adddmi_param_24];
	rem.s32 	%r108, %r31, %r186;
	add.s32 	%r109, %r108, %r186;
	rem.s32 	%r210, %r109, %r186;

$L__BB0_31:
	mov.u16 	%rs53, 0;
	ld.param.u64 	%rd134, [adddmi_param_3];
	cvta.to.global.u64 	%rd133, %rd134;
	ld.param.u64 	%rd126, [adddmi_param_5];
	cvta.to.global.u64 	%rd125, %rd126;
	ld.param.u64 	%rd124, [adddmi_param_4];
	cvta.to.global.u64 	%rd123, %rd124;
	ld.param.u32 	%r188, [adddmi_param_22];
	ld.param.u32 	%r187, [adddmi_param_23];
	mad.lo.s32 	%r110, %r210, %r187, %r2;
	mad.lo.s32 	%r111, %r110, %r188, %r1;
	cvt.s64.s32 	%rd12, %r111;
	mul.wide.s32 	%rd72, %r111, 4;
	add.s64 	%rd73, %rd133, %rd72;
	add.s64 	%rd74, %rd123, %rd72;
	add.s64 	%rd75, %rd125, %rd72;
	ld.global.nc.f32 	%f545, [%rd75];
	ld.global.nc.f32 	%f543, [%rd73];
	ld.global.nc.f32 	%f544, [%rd74];
	mul.f32 	%f192, %f544, %f544;
	fma.rn.f32 	%f193, %f543, %f543, %f192;
	fma.rn.f32 	%f194, %f545, %f545, %f193;
	setp.eq.f32 	%p38, %f194, 0f00000000;
	mov.u32 	%r211, %r6;
	@%p38 bra 	$L__BB0_33;

	ld.param.u64 	%rd136, [adddmi_param_17];
	cvta.to.global.u64 	%rd135, %rd136;
	add.s64 	%rd76, %rd135, %rd12;
	ld.global.nc.u8 	%rs32, [%rd76];
	cvt.u32.u16 	%r112, %rs32;
	and.b32  	%r211, %r112, 255;
	mov.u16 	%rs53, 1;

$L__BB0_33:
	mov.f32 	%f546, 0f00000000;
	mov.u16 	%rs54, 0;
	ld.param.u32 	%r179, [adddmi_param_24];
	add.s32 	%r37, %r3, 1;
	setp.ge.s32 	%p39, %r37, %r179;
	and.pred  	%p41, %p39, %p34;
	mov.f32 	%f547, %f546;
	mov.f32 	%f548, %f546;
	mov.u32 	%r213, %r6;
	@%p41 bra 	$L__BB0_39;

	@%p34 bra 	$L__BB0_36;
	bra.uni 	$L__BB0_35;

$L__BB0_36:
	ld.param.u32 	%r184, [adddmi_param_24];
	add.s32 	%r115, %r184, -1;
	min.s32 	%r212, %r37, %r115;
	bra.uni 	$L__BB0_37;

$L__BB0_35:
	ld.param.u32 	%r181, [adddmi_param_24];
	rem.s32 	%r113, %r37, %r181;
	add.s32 	%r114, %r113, %r181;
	rem.s32 	%r212, %r114, %r181;

$L__BB0_37:
	mov.u32 	%r199, %tid.x;
	mov.u32 	%r198, %ntid.x;
	mov.u32 	%r197, %ctaid.x;
	mad.lo.s32 	%r196, %r197, %r198, %r199;
	mov.u32 	%r195, %tid.y;
	mov.u32 	%r194, %ntid.y;
	mov.u32 	%r193, %ctaid.y;
	mad.lo.s32 	%r192, %r193, %r194, %r195;
	mov.u16 	%rs54, 0;
	ld.param.u64 	%rd122, [adddmi_param_5];
	cvta.to.global.u64 	%rd121, %rd122;
	ld.param.u64 	%rd120, [adddmi_param_4];
	cvta.to.global.u64 	%rd119, %rd120;
	ld.param.u64 	%rd118, [adddmi_param_3];
	cvta.to.global.u64 	%rd117, %rd118;
	ld.param.u32 	%r183, [adddmi_param_22];
	ld.param.u32 	%r182, [adddmi_param_23];
	mad.lo.s32 	%r116, %r212, %r182, %r192;
	mad.lo.s32 	%r117, %r116, %r183, %r196;
	cvt.s64.s32 	%rd13, %r117;
	mul.wide.s32 	%rd77, %r117, 4;
	add.s64 	%rd78, %rd117, %rd77;
	add.s64 	%rd79, %rd119, %rd77;
	add.s64 	%rd80, %rd121, %rd77;
	ld.global.nc.f32 	%f548, [%rd80];
	ld.global.nc.f32 	%f546, [%rd78];
	ld.global.nc.f32 	%f547, [%rd79];
	mul.f32 	%f198, %f547, %f547;
	fma.rn.f32 	%f199, %f546, %f546, %f198;
	fma.rn.f32 	%f200, %f548, %f548, %f199;
	setp.eq.f32 	%p43, %f200, 0f00000000;
	mov.u32 	%r213, %r6;
	@%p43 bra 	$L__BB0_39;

	ld.param.u64 	%rd132, [adddmi_param_17];
	cvta.to.global.u64 	%rd131, %rd132;
	add.s64 	%rd81, %rd131, %rd13;
	ld.global.nc.u8 	%rs36, [%rd81];
	cvt.u32.u16 	%r118, %rs36;
	and.b32  	%r213, %r118, 255;
	mov.u16 	%rs54, 1;

$L__BB0_39:
	setp.eq.s16 	%p44, %rs49, 0;
	setp.gt.f32 	%p45, %f6, 0f00000000;
	mov.f32 	%f552, 0f00000000;
	and.pred  	%p1, %p45, %p44;
	setp.eq.s16 	%p46, %rs50, 0;
	setp.gt.f32 	%p47, %f7, 0f00000000;
	and.pred  	%p2, %p47, %p46;
	setp.eq.s16 	%p48, %rs51, 0;
	setp.gt.f32 	%p49, %f8, 0f00000000;
	and.pred  	%p3, %p49, %p48;
	setp.eq.s16 	%p50, %rs52, 0;
	setp.gt.f32 	%p51, %f9, 0f00000000;
	and.pred  	%p4, %p51, %p50;
	setp.eq.s16 	%p52, %rs53, 0;
	setp.gt.f32 	%p53, %f10, 0f00000000;
	and.pred  	%p5, %p53, %p52;
	setp.eq.s16 	%p54, %rs54, 0;
	setp.gt.f32 	%p55, %f11, 0f00000000;
	and.pred  	%p6, %p55, %p54;
	mul.f32 	%f48, %f6, %f5;
	setp.leu.f32 	%p56, %f48, 0f00000000;
	mov.f32 	%f553, %f552;
	mov.f32 	%f554, %f552;
	@%p56 bra 	$L__BB0_53;

	setp.gt.u32 	%p57, %r203, %r6;
	@%p57 bra 	$L__BB0_42;
	bra.uni 	$L__BB0_41;

$L__BB0_42:
	add.s32 	%r122, %r203, 1;
	mul.lo.s32 	%r123, %r122, %r203;
	shr.u32 	%r124, %r123, 1;
	add.s32 	%r214, %r124, %r6;
	bra.uni 	$L__BB0_43;

$L__BB0_41:
	add.s32 	%r119, %r6, 1;
	mul.lo.s32 	%r120, %r119, %r6;
	shr.u32 	%r121, %r120, 1;
	add.s32 	%r214, %r203, %r121;

$L__BB0_43:
	mul.wide.u32 	%rd82, %r214, 4;
	add.s64 	%rd83, %rd2, %rd82;
	ld.global.nc.f32 	%f49, [%rd83];
	@%p57 bra 	$L__BB0_45;
	bra.uni 	$L__BB0_44;

$L__BB0_45:
	add.s32 	%r128, %r203, 1;
	mul.lo.s32 	%r129, %r128, %r203;
	shr.u32 	%r130, %r129, 1;
	add.s32 	%r215, %r130, %r6;
	bra.uni 	$L__BB0_46;

$L__BB0_44:
	add.s32 	%r125, %r6, 1;
	mul.lo.s32 	%r126, %r125, %r6;
	shr.u32 	%r127, %r126, 1;
	add.s32 	%r215, %r203, %r127;

$L__BB0_46:
	ld.param.u64 	%rd149, [adddmi_param_16];
	cvta.to.global.u64 	%rd148, %rd149;
	setp.eq.s16 	%p108, %rs49, 0;
	mul.wide.u32 	%rd84, %r215, 4;
	add.s64 	%rd85, %rd148, %rd84;
	ld.global.nc.f32 	%f50, [%rd85];
	@%p108 bra 	$L__BB0_48;

	mul.f32 	%f524, %f6, %f5;
	ld.param.f32 	%f521, [adddmi_param_18];
	add.f32 	%f204, %f49, %f49;
	mul.f32 	%f205, %f521, %f521;
	div.rn.f32 	%f206, %f204, %f205;
	sub.f32 	%f207, %f531, %f1;
	mul.f32 	%f208, %f207, %f206;
	sub.f32 	%f209, %f532, %f2;
	mul.f32 	%f210, %f209, %f206;
	sub.f32 	%f211, %f533, %f3;
	mul.f32 	%f212, %f211, %f206;
	fma.rn.f32 	%f213, %f524, %f208, 0f00000000;
	fma.rn.f32 	%f553, %f524, %f210, 0f00000000;
	fma.rn.f32 	%f214, %f524, %f212, 0f00000000;
	div.rn.f32 	%f215, %f50, %f521;
	mul.f32 	%f216, %f524, %f215;
	mul.f32 	%f217, %f533, %f216;
	sub.f32 	%f554, %f213, %f217;
	fma.rn.f32 	%f552, %f531, %f216, %f214;
	bra.uni 	$L__BB0_53;

$L__BB0_48:
	mov.f32 	%f552, 0f00000000;
	ld.param.u8 	%rs41, [adddmi_param_26];
	setp.leu.f32 	%p60, %f6, 0f00000000;
	setp.ne.s16 	%p61, %rs41, 0;
	or.pred  	%p62, %p61, %p60;
	mov.f32 	%f553, %f552;
	mov.f32 	%f554, %f552;
	@%p62 bra 	$L__BB0_53;

	mov.f32 	%f552, 0f00000000;
	abs.f32 	%f224, %f49;
	setp.leu.f32 	%p63, %f224, 0f0DA24260;
	@%p63 bra 	$L__BB0_53;

	selp.f32 	%f228, %f7, 0f00000000, %p2;
	selp.f32 	%f229, %f6, 0f00000000, %p1;
	sub.f32 	%f54, %f228, %f229;
	selp.f32 	%f230, %f8, 0f00000000, %p3;
	selp.f32 	%f231, %f9, 0f00000000, %p4;
	sub.f32 	%f55, %f231, %f230;
	selp.f32 	%f232, %f10, 0f00000000, %p5;
	selp.f32 	%f233, %f11, 0f00000000, %p6;
	sub.f32 	%f56, %f233, %f232;
	mul.f32 	%f234, %f55, %f55;
	fma.rn.f32 	%f235, %f54, %f54, %f234;
	fma.rn.f32 	%f236, %f56, %f56, %f235;
	sqrt.rn.f32 	%f57, %f236;
	setp.le.f32 	%p64, %f57, 0f2B8CBCCC;
	mov.f32 	%f550, 0f00000000;
	mov.f32 	%f549, 0fBF800000;
	mov.f32 	%f551, %f550;
	@%p64 bra 	$L__BB0_52;

	rcp.rn.f32 	%f237, %f57;
	mul.f32 	%f551, %f56, %f237;
	mul.f32 	%f550, %f55, %f237;
	mul.f32 	%f549, %f54, %f237;

$L__BB0_52:
	mul.f32 	%f527, %f6, %f5;
	ld.param.f32 	%f522, [adddmi_param_18];
	mul.f32 	%f238, %f50, 0f3F000000;
	div.rn.f32 	%f239, %f238, %f49;
	mul.f32 	%f240, %f551, 0f00000000;
	sub.f32 	%f241, %f240, %f550;
	sub.f32 	%f242, %f549, %f240;
	mul.f32 	%f243, %f550, 0f00000000;
	mul.f32 	%f244, %f549, 0f00000000;
	sub.f32 	%f245, %f243, %f244;
	mul.f32 	%f246, %f3, %f242;
	mul.f32 	%f247, %f2, %f245;
	sub.f32 	%f248, %f246, %f247;
	mul.f32 	%f249, %f1, %f245;
	mul.f32 	%f250, %f3, %f241;
	sub.f32 	%f251, %f249, %f250;
	mul.f32 	%f252, %f2, %f241;
	mul.f32 	%f253, %f1, %f242;
	sub.f32 	%f254, %f252, %f253;
	mul.f32 	%f255, %f248, %f239;
	mul.f32 	%f256, %f251, %f239;
	mul.f32 	%f257, %f254, %f239;
	mul.f32 	%f258, %f255, %f522;
	mul.f32 	%f259, %f256, %f522;
	mul.f32 	%f260, %f257, %f522;
	sub.f32 	%f261, %f1, %f258;
	sub.f32 	%f262, %f2, %f259;
	sub.f32 	%f263, %f3, %f260;
	mul.f32 	%f264, %f522, %f522;
	add.f32 	%f265, %f49, %f49;
	div.rn.f32 	%f266, %f265, %f264;
	sub.f32 	%f267, %f261, %f1;
	sub.f32 	%f268, %f262, %f2;
	sub.f32 	%f269, %f263, %f3;
	mul.f32 	%f270, %f266, %f267;
	mul.f32 	%f271, %f266, %f268;
	mul.f32 	%f272, %f266, %f269;
	fma.rn.f32 	%f273, %f527, %f270, 0f00000000;
	fma.rn.f32 	%f553, %f527, %f271, 0f00000000;
	fma.rn.f32 	%f274, %f527, %f272, 0f00000000;
	div.rn.f32 	%f275, %f50, %f522;
	mul.f32 	%f276, %f527, %f275;
	mul.f32 	%f277, %f276, %f263;
	sub.f32 	%f554, %f273, %f277;
	fma.rn.f32 	%f552, %f276, %f261, %f274;

$L__BB0_53:
	mul.f32 	%f70, %f5, %f7;
	setp.leu.f32 	%p65, %f70, 0f00000000;
	@%p65 bra 	$L__BB0_67;

	setp.gt.u32 	%p66, %r205, %r6;
	@%p66 bra 	$L__BB0_56;
	bra.uni 	$L__BB0_55;

$L__BB0_56:
	add.s32 	%r134, %r205, 1;
	mul.lo.s32 	%r135, %r134, %r205;
	shr.u32 	%r136, %r135, 1;
	add.s32 	%r216, %r136, %r6;
	bra.uni 	$L__BB0_57;

$L__BB0_55:
	add.s32 	%r131, %r6, 1;
	mul.lo.s32 	%r132, %r131, %r6;
	shr.u32 	%r133, %r132, 1;
	add.s32 	%r216, %r205, %r133;

$L__BB0_57:
	mul.wide.u32 	%rd86, %r216, 4;
	add.s64 	%rd87, %rd2, %rd86;
	ld.global.nc.f32 	%f71, [%rd87];
	@%p66 bra 	$L__BB0_59;
	bra.uni 	$L__BB0_58;

$L__BB0_59:
	add.s32 	%r140, %r205, 1;
	mul.lo.s32 	%r141, %r140, %r205;
	shr.u32 	%r142, %r141, 1;
	add.s32 	%r217, %r142, %r6;
	bra.uni 	$L__BB0_60;

$L__BB0_58:
	add.s32 	%r137, %r6, 1;
	mul.lo.s32 	%r138, %r137, %r6;
	shr.u32 	%r139, %r138, 1;
	add.s32 	%r217, %r205, %r139;

$L__BB0_60:
	ld.param.u64 	%rd144, [adddmi_param_16];
	cvta.to.global.u64 	%rd143, %rd144;
	setp.eq.s16 	%p107, %rs50, 0;
	mul.wide.u32 	%rd88, %r217, 4;
	add.s64 	%rd89, %rd143, %rd88;
	ld.global.nc.f32 	%f72, [%rd89];
	@%p107 bra 	$L__BB0_62;

	ld.param.f32 	%f519, [adddmi_param_18];
	add.f32 	%f278, %f71, %f71;
	mul.f32 	%f279, %f519, %f519;
	div.rn.f32 	%f280, %f278, %f279;
	sub.f32 	%f281, %f534, %f1;
	mul.f32 	%f282, %f281, %f280;
	sub.f32 	%f283, %f535, %f2;
	mul.f32 	%f284, %f283, %f280;
	sub.f32 	%f285, %f536, %f3;
	mul.f32 	%f286, %f285, %f280;
	fma.rn.f32 	%f287, %f70, %f282, %f554;
	fma.rn.f32 	%f553, %f70, %f284, %f553;
	fma.rn.f32 	%f288, %f70, %f286, %f552;
	div.rn.f32 	%f289, %f72, %f519;
	mul.f32 	%f290, %f70, %f289;
	fma.rn.f32 	%f554, %f536, %f290, %f287;
	mul.f32 	%f291, %f534, %f290;
	sub.f32 	%f552, %f288, %f291;
	bra.uni 	$L__BB0_67;

$L__BB0_62:
	ld.param.u8 	%rs40, [adddmi_param_26];
	setp.leu.f32 	%p69, %f7, 0f00000000;
	setp.ne.s16 	%p70, %rs40, 0;
	or.pred  	%p71, %p70, %p69;
	@%p71 bra 	$L__BB0_67;

	abs.f32 	%f292, %f71;
	setp.leu.f32 	%p72, %f292, 0f0DA24260;
	@%p72 bra 	$L__BB0_67;

	selp.f32 	%f296, %f7, 0f00000000, %p2;
	selp.f32 	%f297, %f6, 0f00000000, %p1;
	sub.f32 	%f76, %f296, %f297;
	selp.f32 	%f298, %f8, 0f00000000, %p3;
	selp.f32 	%f299, %f9, 0f00000000, %p4;
	sub.f32 	%f77, %f299, %f298;
	selp.f32 	%f300, %f10, 0f00000000, %p5;
	selp.f32 	%f301, %f11, 0f00000000, %p6;
	sub.f32 	%f78, %f301, %f300;
	mul.f32 	%f302, %f77, %f77;
	fma.rn.f32 	%f303, %f76, %f76, %f302;
	fma.rn.f32 	%f304, %f78, %f78, %f303;
	sqrt.rn.f32 	%f79, %f304;
	setp.le.f32 	%p73, %f79, 0f2B8CBCCC;
	mov.f32 	%f556, 0f00000000;
	mov.f32 	%f555, 0f3F800000;
	mov.f32 	%f557, %f556;
	@%p73 bra 	$L__BB0_66;

	rcp.rn.f32 	%f305, %f79;
	mul.f32 	%f557, %f78, %f305;
	mul.f32 	%f556, %f77, %f305;
	mul.f32 	%f555, %f76, %f305;

$L__BB0_66:
	mul.f32 	%f528, %f5, %f7;
	ld.param.f32 	%f520, [adddmi_param_18];
	mul.f32 	%f306, %f72, 0f3F000000;
	div.rn.f32 	%f307, %f306, %f71;
	mul.f32 	%f308, %f557, 0f00000000;
	sub.f32 	%f309, %f308, %f556;
	sub.f32 	%f310, %f555, %f308;
	mul.f32 	%f311, %f556, 0f00000000;
	mul.f32 	%f312, %f555, 0f00000000;
	sub.f32 	%f313, %f311, %f312;
	mul.f32 	%f314, %f3, %f310;
	mul.f32 	%f315, %f2, %f313;
	sub.f32 	%f316, %f314, %f315;
	mul.f32 	%f317, %f1, %f313;
	mul.f32 	%f318, %f3, %f309;
	sub.f32 	%f319, %f317, %f318;
	mul.f32 	%f320, %f2, %f309;
	mul.f32 	%f321, %f1, %f310;
	sub.f32 	%f322, %f320, %f321;
	mul.f32 	%f323, %f316, %f307;
	mul.f32 	%f324, %f319, %f307;
	mul.f32 	%f325, %f322, %f307;
	mul.f32 	%f326, %f323, %f520;
	mul.f32 	%f327, %f324, %f520;
	mul.f32 	%f328, %f325, %f520;
	sub.f32 	%f329, %f1, %f326;
	sub.f32 	%f330, %f2, %f327;
	sub.f32 	%f331, %f3, %f328;
	mul.f32 	%f332, %f520, %f520;
	add.f32 	%f333, %f71, %f71;
	div.rn.f32 	%f334, %f333, %f332;
	sub.f32 	%f335, %f329, %f1;
	sub.f32 	%f336, %f330, %f2;
	sub.f32 	%f337, %f331, %f3;
	mul.f32 	%f338, %f334, %f335;
	mul.f32 	%f339, %f334, %f336;
	mul.f32 	%f340, %f334, %f337;
	fma.rn.f32 	%f341, %f528, %f338, %f554;
	fma.rn.f32 	%f553, %f528, %f339, %f553;
	fma.rn.f32 	%f342, %f528, %f340, %f552;
	div.rn.f32 	%f343, %f72, %f520;
	mul.f32 	%f344, %f528, %f343;
	fma.rn.f32 	%f554, %f344, %f331, %f341;
	mul.f32 	%f345, %f344, %f329;
	sub.f32 	%f552, %f342, %f345;

$L__BB0_67:
	mul.f32 	%f92, %f5, %f8;
	setp.leu.f32 	%p74, %f92, 0f00000000;
	@%p74 bra 	$L__BB0_81;

	setp.gt.u32 	%p75, %r207, %r6;
	@%p75 bra 	$L__BB0_70;
	bra.uni 	$L__BB0_69;

$L__BB0_70:
	add.s32 	%r146, %r207, 1;
	mul.lo.s32 	%r147, %r146, %r207;
	shr.u32 	%r148, %r147, 1;
	add.s32 	%r218, %r148, %r6;
	bra.uni 	$L__BB0_71;

$L__BB0_69:
	add.s32 	%r143, %r6, 1;
	mul.lo.s32 	%r144, %r143, %r6;
	shr.u32 	%r145, %r144, 1;
	add.s32 	%r218, %r207, %r145;

$L__BB0_71:
	mul.wide.u32 	%rd90, %r218, 4;
	add.s64 	%rd91, %rd2, %rd90;
	ld.global.nc.f32 	%f93, [%rd91];
	@%p75 bra 	$L__BB0_73;
	bra.uni 	$L__BB0_72;

$L__BB0_73:
	add.s32 	%r152, %r207, 1;
	mul.lo.s32 	%r153, %r152, %r207;
	shr.u32 	%r154, %r153, 1;
	add.s32 	%r219, %r154, %r6;
	bra.uni 	$L__BB0_74;

$L__BB0_72:
	add.s32 	%r149, %r6, 1;
	mul.lo.s32 	%r150, %r149, %r6;
	shr.u32 	%r151, %r150, 1;
	add.s32 	%r219, %r207, %r151;

$L__BB0_74:
	ld.param.u64 	%rd142, [adddmi_param_16];
	cvta.to.global.u64 	%rd141, %rd142;
	setp.eq.s16 	%p106, %rs51, 0;
	mul.wide.u32 	%rd92, %r219, 4;
	add.s64 	%rd93, %rd141, %rd92;
	ld.global.nc.f32 	%f94, [%rd93];
	@%p106 bra 	$L__BB0_76;

	ld.param.f32 	%f517, [adddmi_param_19];
	add.f32 	%f346, %f93, %f93;
	mul.f32 	%f347, %f517, %f517;
	div.rn.f32 	%f348, %f346, %f347;
	sub.f32 	%f349, %f537, %f1;
	mul.f32 	%f350, %f349, %f348;
	sub.f32 	%f351, %f538, %f2;
	mul.f32 	%f352, %f351, %f348;
	sub.f32 	%f353, %f539, %f3;
	mul.f32 	%f354, %f353, %f348;
	fma.rn.f32 	%f554, %f92, %f350, %f554;
	fma.rn.f32 	%f355, %f92, %f352, %f553;
	fma.rn.f32 	%f356, %f92, %f354, %f552;
	div.rn.f32 	%f357, %f94, %f517;
	mul.f32 	%f358, %f92, %f357;
	mul.f32 	%f359, %f539, %f358;
	sub.f32 	%f553, %f355, %f359;
	fma.rn.f32 	%f552, %f538, %f358, %f356;
	bra.uni 	$L__BB0_81;

$L__BB0_76:
	ld.param.u8 	%rs39, [adddmi_param_26];
	setp.leu.f32 	%p78, %f8, 0f00000000;
	setp.ne.s16 	%p79, %rs39, 0;
	or.pred  	%p80, %p79, %p78;
	@%p80 bra 	$L__BB0_81;

	abs.f32 	%f360, %f93;
	setp.leu.f32 	%p81, %f360, 0f0DA24260;
	@%p81 bra 	$L__BB0_81;

	selp.f32 	%f364, %f7, 0f00000000, %p2;
	selp.f32 	%f365, %f6, 0f00000000, %p1;
	sub.f32 	%f98, %f364, %f365;
	selp.f32 	%f366, %f8, 0f00000000, %p3;
	selp.f32 	%f367, %f9, 0f00000000, %p4;
	sub.f32 	%f99, %f367, %f366;
	selp.f32 	%f368, %f10, 0f00000000, %p5;
	selp.f32 	%f369, %f11, 0f00000000, %p6;
	sub.f32 	%f100, %f369, %f368;
	mul.f32 	%f370, %f99, %f99;
	fma.rn.f32 	%f371, %f98, %f98, %f370;
	fma.rn.f32 	%f372, %f100, %f100, %f371;
	sqrt.rn.f32 	%f101, %f372;
	setp.le.f32 	%p82, %f101, 0f2B8CBCCC;
	mov.f32 	%f561, 0f00000000;
	mov.f32 	%f562, 0fBF800000;
	mov.f32 	%f563, %f561;
	@%p82 bra 	$L__BB0_80;

	rcp.rn.f32 	%f373, %f101;
	mul.f32 	%f563, %f100, %f373;
	mul.f32 	%f562, %f99, %f373;
	mul.f32 	%f561, %f98, %f373;

$L__BB0_80:
	ld.param.f32 	%f518, [adddmi_param_19];
	mul.f32 	%f374, %f94, 0f3F000000;
	div.rn.f32 	%f375, %f374, %f93;
	mul.f32 	%f376, %f563, 0f00000000;
	sub.f32 	%f377, %f376, %f562;
	sub.f32 	%f378, %f561, %f376;
	mul.f32 	%f379, %f562, 0f00000000;
	mul.f32 	%f380, %f561, 0f00000000;
	sub.f32 	%f381, %f379, %f380;
	mul.f32 	%f382, %f3, %f378;
	mul.f32 	%f383, %f2, %f381;
	sub.f32 	%f384, %f382, %f383;
	mul.f32 	%f385, %f1, %f381;
	mul.f32 	%f386, %f3, %f377;
	sub.f32 	%f387, %f385, %f386;
	mul.f32 	%f388, %f2, %f377;
	mul.f32 	%f389, %f1, %f378;
	sub.f32 	%f390, %f388, %f389;
	mul.f32 	%f391, %f384, %f375;
	mul.f32 	%f392, %f387, %f375;
	mul.f32 	%f393, %f390, %f375;
	mul.f32 	%f394, %f391, %f518;
	mul.f32 	%f395, %f392, %f518;
	mul.f32 	%f396, %f393, %f518;
	sub.f32 	%f397, %f1, %f394;
	sub.f32 	%f398, %f2, %f395;
	sub.f32 	%f399, %f3, %f396;
	mul.f32 	%f400, %f518, %f518;
	add.f32 	%f401, %f93, %f93;
	div.rn.f32 	%f402, %f401, %f400;
	sub.f32 	%f403, %f397, %f1;
	sub.f32 	%f404, %f398, %f2;
	sub.f32 	%f405, %f399, %f3;
	mul.f32 	%f406, %f402, %f403;
	mul.f32 	%f407, %f402, %f404;
	mul.f32 	%f408, %f402, %f405;
	fma.rn.f32 	%f554, %f92, %f406, %f554;
	fma.rn.f32 	%f409, %f92, %f407, %f553;
	fma.rn.f32 	%f410, %f92, %f408, %f552;
	div.rn.f32 	%f411, %f94, %f518;
	mul.f32 	%f412, %f92, %f411;
	mul.f32 	%f413, %f412, %f399;
	sub.f32 	%f553, %f409, %f413;
	fma.rn.f32 	%f552, %f412, %f398, %f410;

$L__BB0_81:
	mul.f32 	%f114, %f5, %f9;
	setp.leu.f32 	%p83, %f114, 0f00000000;
	@%p83 bra 	$L__BB0_95;

	setp.gt.u32 	%p84, %r209, %r6;
	@%p84 bra 	$L__BB0_84;
	bra.uni 	$L__BB0_83;

$L__BB0_84:
	add.s32 	%r158, %r209, 1;
	mul.lo.s32 	%r159, %r158, %r209;
	shr.u32 	%r160, %r159, 1;
	add.s32 	%r220, %r160, %r6;
	bra.uni 	$L__BB0_85;

$L__BB0_83:
	add.s32 	%r155, %r6, 1;
	mul.lo.s32 	%r156, %r155, %r6;
	shr.u32 	%r157, %r156, 1;
	add.s32 	%r220, %r209, %r157;

$L__BB0_85:
	mul.wide.u32 	%rd94, %r220, 4;
	add.s64 	%rd95, %rd2, %rd94;
	ld.global.nc.f32 	%f115, [%rd95];
	@%p84 bra 	$L__BB0_87;
	bra.uni 	$L__BB0_86;

$L__BB0_87:
	add.s32 	%r164, %r209, 1;
	mul.lo.s32 	%r165, %r164, %r209;
	shr.u32 	%r166, %r165, 1;
	add.s32 	%r221, %r166, %r6;
	bra.uni 	$L__BB0_88;

$L__BB0_86:
	add.s32 	%r161, %r6, 1;
	mul.lo.s32 	%r162, %r161, %r6;
	shr.u32 	%r163, %r162, 1;
	add.s32 	%r221, %r209, %r163;

$L__BB0_88:
	ld.param.u64 	%rd140, [adddmi_param_16];
	cvta.to.global.u64 	%rd139, %rd140;
	setp.eq.s16 	%p105, %rs52, 0;
	mul.wide.u32 	%rd96, %r221, 4;
	add.s64 	%rd97, %rd139, %rd96;
	ld.global.nc.f32 	%f116, [%rd97];
	@%p105 bra 	$L__BB0_90;

	ld.param.f32 	%f515, [adddmi_param_19];
	add.f32 	%f414, %f115, %f115;
	mul.f32 	%f415, %f515, %f515;
	div.rn.f32 	%f416, %f414, %f415;
	sub.f32 	%f417, %f540, %f1;
	mul.f32 	%f418, %f417, %f416;
	sub.f32 	%f419, %f541, %f2;
	mul.f32 	%f420, %f419, %f416;
	sub.f32 	%f421, %f542, %f3;
	mul.f32 	%f422, %f421, %f416;
	fma.rn.f32 	%f554, %f114, %f418, %f554;
	fma.rn.f32 	%f423, %f114, %f420, %f553;
	fma.rn.f32 	%f424, %f114, %f422, %f552;
	div.rn.f32 	%f425, %f116, %f515;
	mul.f32 	%f426, %f114, %f425;
	fma.rn.f32 	%f553, %f542, %f426, %f423;
	mul.f32 	%f427, %f541, %f426;
	sub.f32 	%f552, %f424, %f427;
	bra.uni 	$L__BB0_95;

$L__BB0_90:
	ld.param.u8 	%rs38, [adddmi_param_26];
	setp.leu.f32 	%p87, %f9, 0f00000000;
	setp.ne.s16 	%p88, %rs38, 0;
	or.pred  	%p89, %p88, %p87;
	@%p89 bra 	$L__BB0_95;

	abs.f32 	%f428, %f115;
	setp.leu.f32 	%p90, %f428, 0f0DA24260;
	@%p90 bra 	$L__BB0_95;

	selp.f32 	%f432, %f7, 0f00000000, %p2;
	selp.f32 	%f433, %f6, 0f00000000, %p1;
	sub.f32 	%f120, %f432, %f433;
	selp.f32 	%f434, %f8, 0f00000000, %p3;
	selp.f32 	%f435, %f9, 0f00000000, %p4;
	sub.f32 	%f121, %f435, %f434;
	selp.f32 	%f436, %f10, 0f00000000, %p5;
	selp.f32 	%f437, %f11, 0f00000000, %p6;
	sub.f32 	%f122, %f437, %f436;
	mul.f32 	%f438, %f121, %f121;
	fma.rn.f32 	%f439, %f120, %f120, %f438;
	fma.rn.f32 	%f440, %f122, %f122, %f439;
	sqrt.rn.f32 	%f123, %f440;
	setp.le.f32 	%p91, %f123, 0f2B8CBCCC;
	mov.f32 	%f567, 0f00000000;
	mov.f32 	%f568, 0f3F800000;
	mov.f32 	%f569, %f567;
	@%p91 bra 	$L__BB0_94;

	rcp.rn.f32 	%f441, %f123;
	mul.f32 	%f569, %f122, %f441;
	mul.f32 	%f568, %f121, %f441;
	mul.f32 	%f567, %f120, %f441;

$L__BB0_94:
	ld.param.f32 	%f516, [adddmi_param_19];
	mul.f32 	%f442, %f116, 0f3F000000;
	div.rn.f32 	%f443, %f442, %f115;
	mul.f32 	%f444, %f569, 0f00000000;
	sub.f32 	%f445, %f444, %f568;
	sub.f32 	%f446, %f567, %f444;
	mul.f32 	%f447, %f568, 0f00000000;
	mul.f32 	%f448, %f567, 0f00000000;
	sub.f32 	%f449, %f447, %f448;
	mul.f32 	%f450, %f3, %f446;
	mul.f32 	%f451, %f2, %f449;
	sub.f32 	%f452, %f450, %f451;
	mul.f32 	%f453, %f1, %f449;
	mul.f32 	%f454, %f3, %f445;
	sub.f32 	%f455, %f453, %f454;
	mul.f32 	%f456, %f2, %f445;
	mul.f32 	%f457, %f1, %f446;
	sub.f32 	%f458, %f456, %f457;
	mul.f32 	%f459, %f452, %f443;
	mul.f32 	%f460, %f455, %f443;
	mul.f32 	%f461, %f458, %f443;
	mul.f32 	%f462, %f459, %f516;
	mul.f32 	%f463, %f460, %f516;
	mul.f32 	%f464, %f461, %f516;
	sub.f32 	%f465, %f1, %f462;
	sub.f32 	%f466, %f2, %f463;
	sub.f32 	%f467, %f3, %f464;
	mul.f32 	%f468, %f516, %f516;
	add.f32 	%f469, %f115, %f115;
	div.rn.f32 	%f470, %f469, %f468;
	sub.f32 	%f471, %f465, %f1;
	sub.f32 	%f472, %f466, %f2;
	sub.f32 	%f473, %f467, %f3;
	mul.f32 	%f474, %f470, %f471;
	mul.f32 	%f475, %f470, %f472;
	mul.f32 	%f476, %f470, %f473;
	fma.rn.f32 	%f554, %f114, %f474, %f554;
	fma.rn.f32 	%f477, %f114, %f475, %f553;
	fma.rn.f32 	%f478, %f114, %f476, %f552;
	div.rn.f32 	%f479, %f116, %f516;
	mul.f32 	%f480, %f114, %f479;
	fma.rn.f32 	%f553, %f480, %f467, %f477;
	mul.f32 	%f481, %f480, %f466;
	sub.f32 	%f552, %f478, %f481;

$L__BB0_95:
	ld.param.u32 	%r180, [adddmi_param_24];
	setp.eq.s32 	%p92, %r180, 1;
	@%p92 bra 	$L__BB0_106;

	setp.eq.s16 	%p103, %rs53, 0;
	mul.f32 	%f136, %f5, %f10;
	setp.leu.f32 	%p93, %f136, 0f00000000;
	or.pred  	%p95, %p93, %p103;
	@%p95 bra 	$L__BB0_101;

	setp.gt.u32 	%p96, %r211, %r6;
	@%p96 bra 	$L__BB0_99;
	bra.uni 	$L__BB0_98;

$L__BB0_99:
	add.s32 	%r170, %r211, 1;
	mul.lo.s32 	%r171, %r170, %r211;
	shr.u32 	%r172, %r171, 1;
	add.s32 	%r222, %r172, %r6;
	bra.uni 	$L__BB0_100;

$L__BB0_98:
	add.s32 	%r167, %r6, 1;
	mul.lo.s32 	%r168, %r167, %r6;
	shr.u32 	%r169, %r168, 1;
	add.s32 	%r222, %r211, %r169;

$L__BB0_100:
	ld.param.f32 	%f512, [adddmi_param_20];
	mul.wide.u32 	%rd98, %r222, 4;
	add.s64 	%rd99, %rd2, %rd98;
	ld.global.nc.f32 	%f482, [%rd99];
	add.f32 	%f483, %f482, %f482;
	mul.f32 	%f484, %f512, %f512;
	div.rn.f32 	%f485, %f483, %f484;
	sub.f32 	%f486, %f543, %f1;
	sub.f32 	%f487, %f544, %f2;
	sub.f32 	%f488, %f545, %f3;
	mul.f32 	%f489, %f486, %f485;
	mul.f32 	%f490, %f487, %f485;
	mul.f32 	%f491, %f488, %f485;
	fma.rn.f32 	%f554, %f136, %f489, %f554;
	fma.rn.f32 	%f553, %f136, %f490, %f553;
	fma.rn.f32 	%f552, %f136, %f491, %f552;

$L__BB0_101:
	setp.eq.s16 	%p104, %rs54, 0;
	mul.f32 	%f143, %f5, %f11;
	setp.leu.f32 	%p97, %f143, 0f00000000;
	or.pred  	%p99, %p97, %p104;
	@%p99 bra 	$L__BB0_106;

	setp.gt.u32 	%p100, %r213, %r6;
	@%p100 bra 	$L__BB0_104;
	bra.uni 	$L__BB0_103;

$L__BB0_104:
	add.s32 	%r176, %r213, 1;
	mul.lo.s32 	%r177, %r176, %r213;
	shr.u32 	%r178, %r177, 1;
	add.s32 	%r223, %r178, %r6;
	bra.uni 	$L__BB0_105;

$L__BB0_103:
	add.s32 	%r173, %r6, 1;
	mul.lo.s32 	%r174, %r173, %r6;
	shr.u32 	%r175, %r174, 1;
	add.s32 	%r223, %r213, %r175;

$L__BB0_105:
	ld.param.f32 	%f511, [adddmi_param_20];
	mul.wide.u32 	%rd100, %r223, 4;
	add.s64 	%rd101, %rd2, %rd100;
	ld.global.nc.f32 	%f492, [%rd101];
	add.f32 	%f493, %f492, %f492;
	mul.f32 	%f494, %f511, %f511;
	div.rn.f32 	%f495, %f493, %f494;
	sub.f32 	%f496, %f546, %f1;
	sub.f32 	%f497, %f547, %f2;
	sub.f32 	%f498, %f548, %f3;
	mul.f32 	%f499, %f496, %f495;
	mul.f32 	%f500, %f497, %f495;
	mul.f32 	%f501, %f498, %f495;
	fma.rn.f32 	%f554, %f143, %f499, %f554;
	fma.rn.f32 	%f553, %f143, %f500, %f553;
	fma.rn.f32 	%f552, %f143, %f501, %f552;

$L__BB0_106:
	ld.param.f32 	%f579, [adddmi_param_7];
	ld.param.u64 	%rd112, [adddmi_param_6];
	setp.eq.s64 	%p101, %rd112, 0;
	@%p101 bra 	$L__BB0_108;

	ld.param.f32 	%f514, [adddmi_param_7];
	ld.param.u64 	%rd113, [adddmi_param_6];
	cvta.to.global.u64 	%rd102, %rd113;
	add.s64 	%rd104, %rd102, %rd37;
	ld.global.nc.f32 	%f502, [%rd104];
	mul.f32 	%f579, %f502, %f514;

$L__BB0_108:
	setp.eq.f32 	%p102, %f579, 0f00000000;
	mov.f32 	%f580, 0f00000000;
	@%p102 bra 	$L__BB0_110;

	rcp.rn.f32 	%f580, %f579;

$L__BB0_110:
	ld.param.u64 	%rd116, [adddmi_param_2];
	ld.param.u64 	%rd115, [adddmi_param_1];
	ld.param.u64 	%rd114, [adddmi_param_0];
	cvta.to.global.u64 	%rd105, %rd114;
	add.s64 	%rd107, %rd105, %rd37;
	ld.global.f32 	%f504, [%rd107];
	fma.rn.f32 	%f505, %f554, %f580, %f504;
	st.global.f32 	[%rd107], %f505;
	cvta.to.global.u64 	%rd108, %rd115;
	add.s64 	%rd109, %rd108, %rd37;
	ld.global.f32 	%f506, [%rd109];
	fma.rn.f32 	%f507, %f553, %f580, %f506;
	st.global.f32 	[%rd109], %f507;
	cvta.to.global.u64 	%rd110, %rd116;
	add.s64 	%rd111, %rd110, %rd37;
	ld.global.f32 	%f508, [%rd111];
	fma.rn.f32 	%f509, %f552, %f580, %f508;
	st.global.f32 	[%rd111], %f509;

$L__BB0_111:
	ret;

}

`
	)
