package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for adddmibulk kernel
var adddmibulkCode cu.Function

// Stores the arguments for adddmibulk kernel invocation
type adddmibulkArgsT struct {
	argHx unsafe.Pointer
	argHy unsafe.Pointer
	argHz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argMs unsafe.Pointer
	argMsMul float32
	argVol unsafe.Pointer
	argFxm unsafe.Pointer
	argFxp unsafe.Pointer
	argFym unsafe.Pointer
	argFyp unsafe.Pointer
	argFzm unsafe.Pointer
	argFzp unsafe.Pointer
	argALUT2d unsafe.Pointer
	argDLUT2d unsafe.Pointer
	argRegions unsafe.Pointer
	argCx float32
	argCy float32
	argCz float32
	argPhiFloor float32
	argNx int
	argNy int
	argNz int
	argPBC byte
	argOpenBC byte
	argptr [27]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for adddmibulk kernel invocation
var adddmibulkArgs adddmibulkArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	adddmibulkArgs.argptr[0] = unsafe.Pointer(&adddmibulkArgs.argHx)
	adddmibulkArgs.argptr[1] = unsafe.Pointer(&adddmibulkArgs.argHy)
	adddmibulkArgs.argptr[2] = unsafe.Pointer(&adddmibulkArgs.argHz)
	adddmibulkArgs.argptr[3] = unsafe.Pointer(&adddmibulkArgs.argMx)
	adddmibulkArgs.argptr[4] = unsafe.Pointer(&adddmibulkArgs.argMy)
	adddmibulkArgs.argptr[5] = unsafe.Pointer(&adddmibulkArgs.argMz)
	adddmibulkArgs.argptr[6] = unsafe.Pointer(&adddmibulkArgs.argMs)
	adddmibulkArgs.argptr[7] = unsafe.Pointer(&adddmibulkArgs.argMsMul)
	adddmibulkArgs.argptr[8] = unsafe.Pointer(&adddmibulkArgs.argVol)
	adddmibulkArgs.argptr[9] = unsafe.Pointer(&adddmibulkArgs.argFxm)
	adddmibulkArgs.argptr[10] = unsafe.Pointer(&adddmibulkArgs.argFxp)
	adddmibulkArgs.argptr[11] = unsafe.Pointer(&adddmibulkArgs.argFym)
	adddmibulkArgs.argptr[12] = unsafe.Pointer(&adddmibulkArgs.argFyp)
	adddmibulkArgs.argptr[13] = unsafe.Pointer(&adddmibulkArgs.argFzm)
	adddmibulkArgs.argptr[14] = unsafe.Pointer(&adddmibulkArgs.argFzp)
	adddmibulkArgs.argptr[15] = unsafe.Pointer(&adddmibulkArgs.argALUT2d)
	adddmibulkArgs.argptr[16] = unsafe.Pointer(&adddmibulkArgs.argDLUT2d)
	adddmibulkArgs.argptr[17] = unsafe.Pointer(&adddmibulkArgs.argRegions)
	adddmibulkArgs.argptr[18] = unsafe.Pointer(&adddmibulkArgs.argCx)
	adddmibulkArgs.argptr[19] = unsafe.Pointer(&adddmibulkArgs.argCy)
	adddmibulkArgs.argptr[20] = unsafe.Pointer(&adddmibulkArgs.argCz)
	adddmibulkArgs.argptr[21] = unsafe.Pointer(&adddmibulkArgs.argPhiFloor)
	adddmibulkArgs.argptr[22] = unsafe.Pointer(&adddmibulkArgs.argNx)
	adddmibulkArgs.argptr[23] = unsafe.Pointer(&adddmibulkArgs.argNy)
	adddmibulkArgs.argptr[24] = unsafe.Pointer(&adddmibulkArgs.argNz)
	adddmibulkArgs.argptr[25] = unsafe.Pointer(&adddmibulkArgs.argPBC)
	adddmibulkArgs.argptr[26] = unsafe.Pointer(&adddmibulkArgs.argOpenBC)
	}

// Wrapper for adddmibulk CUDA kernel, asynchronous.
func kAdddmibulkAsync(Hx unsafe.Pointer, Hy unsafe.Pointer, Hz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, vol unsafe.Pointer, fxm unsafe.Pointer, fxp unsafe.Pointer, fym unsafe.Pointer, fyp unsafe.Pointer, fzm unsafe.Pointer, fzp unsafe.Pointer, aLUT2d unsafe.Pointer, DLUT2d unsafe.Pointer, regions unsafe.Pointer, cx float32, cy float32, cz float32, phiFloor float32, Nx int, Ny int, Nz int, PBC byte, OpenBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("adddmibulk")
	}

	adddmibulkArgs.Lock()
	defer adddmibulkArgs.Unlock()

	if adddmibulkCode == 0 {
		adddmibulkCode = fatbinLoad(adddmibulkMap, "adddmibulk")
	}

	adddmibulkArgs.argHx = Hx
	adddmibulkArgs.argHy = Hy
	adddmibulkArgs.argHz = Hz
	adddmibulkArgs.argMx = mx
	adddmibulkArgs.argMy = my
	adddmibulkArgs.argMz = mz
	adddmibulkArgs.argMs = Ms_
	adddmibulkArgs.argMsMul = Ms_mul
	adddmibulkArgs.argVol = vol
	adddmibulkArgs.argFxm = fxm
	adddmibulkArgs.argFxp = fxp
	adddmibulkArgs.argFym = fym
	adddmibulkArgs.argFyp = fyp
	adddmibulkArgs.argFzm = fzm
	adddmibulkArgs.argFzp = fzp
	adddmibulkArgs.argALUT2d = aLUT2d
	adddmibulkArgs.argDLUT2d = DLUT2d
	adddmibulkArgs.argRegions = regions
	adddmibulkArgs.argCx = cx
	adddmibulkArgs.argCy = cy
	adddmibulkArgs.argCz = cz
	adddmibulkArgs.argPhiFloor = phiFloor
	adddmibulkArgs.argNx = Nx
	adddmibulkArgs.argNy = Ny
	adddmibulkArgs.argNz = Nz
	adddmibulkArgs.argPBC = PBC
	adddmibulkArgs.argOpenBC = OpenBC
	
	args := adddmibulkArgs.argptr[:]
	cu.LaunchKernel(adddmibulkCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("adddmibulk")
	}
}

// maps compute capability on PTX code for adddmibulk kernel.
var adddmibulkMap = map[int]string{
	0: "",
	52: adddmibulkPtx52,
}

// adddmibulk PTX code for various compute capabilities.
const (
	adddmibulkPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	adddmibulk

.visible .entry adddmibulk(
	.param .u64 adddmibulk_param_0,
	.param .u64 adddmibulk_param_1,
	.param .u64 adddmibulk_param_2,
	.param .u64 adddmibulk_param_3,
	.param .u64 adddmibulk_param_4,
	.param .u64 adddmibulk_param_5,
	.param .u64 adddmibulk_param_6,
	.param .f32 adddmibulk_param_7,
	.param .u64 adddmibulk_param_8,
	.param .u64 adddmibulk_param_9,
	.param .u64 adddmibulk_param_10,
	.param .u64 adddmibulk_param_11,
	.param .u64 adddmibulk_param_12,
	.param .u64 adddmibulk_param_13,
	.param .u64 adddmibulk_param_14,
	.param .u64 adddmibulk_param_15,
	.param .u64 adddmibulk_param_16,
	.param .u64 adddmibulk_param_17,
	.param .f32 adddmibulk_param_18,
	.param .f32 adddmibulk_param_19,
	.param .f32 adddmibulk_param_20,
	.param .f32 adddmibulk_param_21,
	.param .u32 adddmibulk_param_22,
	.param .u32 adddmibulk_param_23,
	.param .u32 adddmibulk_param_24,
	.param .u8 adddmibulk_param_25,
	.param .u8 adddmibulk_param_26
)
{
	.reg .pred 	%p<85>;
	.reg .b16 	%rs<16>;
	.reg .f32 	%f<448>;
	.reg .b32 	%r<221>;
	.reg .b64 	%rd<133>;


	ld.param.u8 	%rs8, [adddmibulk_param_26];
	ld.param.u8 	%rs7, [adddmibulk_param_25];
	ld.param.u64 	%rd25, [adddmibulk_param_3];
	ld.param.u64 	%rd26, [adddmibulk_param_4];
	ld.param.u64 	%rd27, [adddmibulk_param_5];
	ld.param.u64 	%rd28, [adddmibulk_param_15];
	ld.param.u64 	%rd29, [adddmibulk_param_16];
	ld.param.u64 	%rd30, [adddmibulk_param_17];
	ld.param.f32 	%f131, [adddmibulk_param_18];
	ld.param.f32 	%f132, [adddmibulk_param_19];
	ld.param.u32 	%r79, [adddmibulk_param_22];
	ld.param.u32 	%r80, [adddmibulk_param_23];
	ld.param.u32 	%r81, [adddmibulk_param_24];
	cvta.to.global.u64 	%rd1, %rd29;
	cvta.to.global.u64 	%rd2, %rd28;
	cvta.to.global.u64 	%rd3, %rd30;
	cvta.to.global.u64 	%rd4, %rd27;
	cvta.to.global.u64 	%rd5, %rd26;
	cvta.to.global.u64 	%rd6, %rd25;
	mov.u32 	%r82, %ntid.x;
	mov.u32 	%r83, %ctaid.x;
	mov.u32 	%r84, %tid.x;
	mad.lo.s32 	%r1, %r83, %r82, %r84;
	mov.u32 	%r85, %ntid.y;
	mov.u32 	%r86, %ctaid.y;
	mov.u32 	%r87, %tid.y;
	mad.lo.s32 	%r2, %r86, %r85, %r87;
	mov.u32 	%r88, %ntid.z;
	mov.u32 	%r89, %ctaid.z;
	mov.u32 	%r90, %tid.z;
	mad.lo.s32 	%r3, %r89, %r88, %r90;
	setp.ge.s32 	%p1, %r1, %r79;
	setp.ge.s32 	%p2, %r2, %r80;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r81;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_111;

	mul.lo.s32 	%r4, %r3, %r80;
	add.s32 	%r91, %r4, %r2;
	mul.lo.s32 	%r5, %r91, %r79;
	add.s32 	%r92, %r5, %r1;
	cvt.s64.s32 	%rd7, %r92;
	mul.wide.s32 	%rd31, %r92, 4;
	add.s64 	%rd32, %rd6, %rd31;
	add.s64 	%rd33, %rd5, %rd31;
	add.s64 	%rd34, %rd4, %rd31;
	add.s64 	%rd35, %rd3, %rd7;
	ld.global.nc.u8 	%rs9, [%rd35];
	cvt.u32.u16 	%r93, %rs9;
	and.b32  	%r6, %r93, 255;
	ld.global.nc.f32 	%f1, [%rd32];
	ld.global.nc.f32 	%f2, [%rd33];
	mul.f32 	%f135, %f2, %f2;
	fma.rn.f32 	%f136, %f1, %f1, %f135;
	ld.global.nc.f32 	%f3, [%rd34];
	fma.rn.f32 	%f137, %f3, %f3, %f136;
	setp.eq.f32 	%p6, %f137, 0f00000000;
	@%p6 bra 	$L__BB0_111;

	ld.param.u64 	%rd121, [adddmibulk_param_8];
	cvta.to.global.u64 	%rd36, %rd121;
	shl.b64 	%rd37, %rd7, 2;
	add.s64 	%rd38, %rd36, %rd37;
	ld.global.nc.f32 	%f4, [%rd38];
	setp.le.f32 	%p7, %f4, 0f00000000;
	mov.f32 	%f413, 0f00000000;
	mov.f32 	%f414, 0f00000000;
	mov.f32 	%f415, 0f00000000;
	@%p7 bra 	$L__BB0_111;

	ld.param.u64 	%rd122, [adddmibulk_param_9];
	ld.param.f32 	%f398, [adddmibulk_param_21];
	mov.f32 	%f141, 0f358637BD;
	max.f32 	%f142, %f398, %f141;
	max.f32 	%f143, %f4, %f142;
	rcp.rn.f32 	%f5, %f143;
	cvta.to.global.u64 	%rd39, %rd122;
	add.s64 	%rd41, %rd39, %rd37;
	ld.global.nc.f32 	%f6, [%rd41];
	mul.f32 	%f7, %f6, %f5;
	setp.leu.f32 	%p8, %f7, 0f00000000;
	@%p8 bra 	$L__BB0_20;

	setp.lt.s32 	%p9, %r1, 1;
	and.b16  	%rs1, %rs7, 1;
	setp.eq.s16 	%p10, %rs1, 0;
	mov.f32 	%f410, 0f00000000;
	and.pred  	%p11, %p9, %p10;
	mov.f32 	%f411, %f410;
	mov.f32 	%f412, %f410;
	mov.u32 	%r198, %r6;
	@%p11 bra 	$L__BB0_10;

	add.s32 	%r7, %r1, -1;
	@%p10 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_6;

$L__BB0_7:
	max.s32 	%r197, %r7, 0;
	bra.uni 	$L__BB0_8;

$L__BB0_6:
	rem.s32 	%r94, %r7, %r79;
	add.s32 	%r95, %r94, %r79;
	rem.s32 	%r197, %r95, %r79;

$L__BB0_8:
	add.s32 	%r96, %r197, %r5;
	cvt.s64.s32 	%rd8, %r96;
	mul.wide.s32 	%rd42, %r96, 4;
	add.s64 	%rd43, %rd6, %rd42;
	add.s64 	%rd44, %rd5, %rd42;
	add.s64 	%rd45, %rd4, %rd42;
	ld.global.nc.f32 	%f412, [%rd43];
	ld.global.nc.f32 	%f411, [%rd44];
	mul.f32 	%f147, %f411, %f411;
	fma.rn.f32 	%f148, %f412, %f412, %f147;
	ld.global.nc.f32 	%f410, [%rd45];
	fma.rn.f32 	%f149, %f410, %f410, %f148;
	setp.eq.f32 	%p13, %f149, 0f00000000;
	mov.u32 	%r198, %r6;
	@%p13 bra 	$L__BB0_10;

	add.s64 	%rd46, %rd3, %rd8;
	ld.global.nc.u8 	%rs10, [%rd46];
	cvt.u32.u16 	%r97, %rs10;
	and.b32  	%r198, %r97, 255;

$L__BB0_10:
	setp.gt.u32 	%p14, %r198, %r6;
	@%p14 bra 	$L__BB0_12;
	bra.uni 	$L__BB0_11;

$L__BB0_12:
	add.s32 	%r101, %r198, 1;
	mul.lo.s32 	%r102, %r101, %r198;
	shr.u32 	%r103, %r102, 1;
	add.s32 	%r199, %r103, %r6;
	bra.uni 	$L__BB0_13;

$L__BB0_11:
	add.s32 	%r98, %r6, 1;
	mul.lo.s32 	%r99, %r98, %r6;
	shr.u32 	%r100, %r99, 1;
	add.s32 	%r199, %r198, %r100;

$L__BB0_13:
	mul.wide.u32 	%rd47, %r199, 4;
	add.s64 	%rd48, %rd2, %rd47;
	ld.global.nc.f32 	%f14, [%rd48];
	@%p14 bra 	$L__BB0_15;
	bra.uni 	$L__BB0_14;

$L__BB0_15:
	add.s32 	%r107, %r198, 1;
	mul.lo.s32 	%r108, %r107, %r198;
	shr.u32 	%r109, %r108, 1;
	add.s32 	%r200, %r109, %r6;
	bra.uni 	$L__BB0_16;

$L__BB0_14:
	add.s32 	%r104, %r6, 1;
	mul.lo.s32 	%r105, %r104, %r6;
	shr.u32 	%r106, %r105, 1;
	add.s32 	%r200, %r198, %r106;

$L__BB0_16:
	mul.wide.u32 	%rd49, %r200, 4;
	add.s64 	%rd50, %rd1, %rd49;
	add.f32 	%f15, %f14, %f14;
	ld.global.nc.f32 	%f16, [%rd50];
	mul.f32 	%f150, %f412, %f412;
	fma.rn.f32 	%f151, %f411, %f411, %f150;
	fma.rn.f32 	%f152, %f410, %f410, %f151;
	setp.neu.f32 	%p16, %f152, 0f00000000;
	@%p16 bra 	$L__BB0_19;
	bra.uni 	$L__BB0_17;

$L__BB0_19:
	mul.f32 	%f174, %f131, %f131;
	div.rn.f32 	%f175, %f15, %f174;
	sub.f32 	%f176, %f412, %f1;
	mul.f32 	%f177, %f176, %f175;
	sub.f32 	%f178, %f411, %f2;
	mul.f32 	%f179, %f178, %f175;
	sub.f32 	%f180, %f410, %f3;
	mul.f32 	%f181, %f180, %f175;
	fma.rn.f32 	%f413, %f7, %f177, 0f00000000;
	fma.rn.f32 	%f182, %f7, %f179, 0f00000000;
	fma.rn.f32 	%f183, %f7, %f181, 0f00000000;
	div.rn.f32 	%f184, %f16, %f131;
	mul.f32 	%f185, %f7, %f184;
	mul.f32 	%f186, %f410, %f185;
	sub.f32 	%f414, %f182, %f186;
	fma.rn.f32 	%f415, %f411, %f185, %f183;
	bra.uni 	$L__BB0_20;

$L__BB0_17:
	mov.f32 	%f415, 0f00000000;
	mov.f32 	%f414, 0f00000000;
	mov.f32 	%f413, 0f00000000;
	setp.ne.s16 	%p17, %rs8, 0;
	setp.leu.f32 	%p18, %f6, 0f3F7FBE77;
	or.pred  	%p19, %p17, %p18;
	@%p19 bra 	$L__BB0_20;

	div.rn.f32 	%f156, %f16, %f15;
	mul.f32 	%f157, %f156, %f131;
	fma.rn.f32 	%f158, %f3, %f157, %f2;
	mul.f32 	%f159, %f2, %f157;
	sub.f32 	%f160, %f3, %f159;
	mul.f32 	%f161, %f131, %f131;
	div.rn.f32 	%f162, %f15, %f161;
	sub.f32 	%f163, %f158, %f2;
	sub.f32 	%f164, %f160, %f3;
	sub.f32 	%f165, %f1, %f1;
	mul.f32 	%f166, %f165, %f162;
	mul.f32 	%f167, %f162, %f163;
	mul.f32 	%f168, %f162, %f164;
	fma.rn.f32 	%f413, %f7, %f166, 0f00000000;
	fma.rn.f32 	%f169, %f7, %f167, 0f00000000;
	fma.rn.f32 	%f170, %f7, %f168, 0f00000000;
	div.rn.f32 	%f171, %f16, %f131;
	mul.f32 	%f172, %f7, %f171;
	mul.f32 	%f173, %f172, %f160;
	sub.f32 	%f414, %f169, %f173;
	fma.rn.f32 	%f415, %f172, %f158, %f170;

$L__BB0_20:
	ld.param.u64 	%rd123, [adddmibulk_param_10];
	cvta.to.global.u64 	%rd51, %rd123;
	add.s64 	%rd53, %rd51, %rd37;
	ld.global.nc.f32 	%f26, [%rd53];
	mul.f32 	%f27, %f5, %f26;
	setp.leu.f32 	%p20, %f27, 0f00000000;
	@%p20 bra 	$L__BB0_37;

	add.s32 	%r19, %r1, 1;
	setp.ge.s32 	%p21, %r19, %r79;
	and.b16  	%rs2, %rs7, 1;
	setp.eq.s16 	%p22, %rs2, 0;
	mov.f32 	%f416, 0f00000000;
	and.pred  	%p23, %p21, %p22;
	mov.f32 	%f417, %f416;
	mov.f32 	%f418, %f416;
	mov.u32 	%r202, %r6;
	@%p23 bra 	$L__BB0_27;

	@%p22 bra 	$L__BB0_24;
	bra.uni 	$L__BB0_23;

$L__BB0_24:
	add.s32 	%r112, %r79, -1;
	min.s32 	%r201, %r19, %r112;
	bra.uni 	$L__BB0_25;

$L__BB0_23:
	rem.s32 	%r110, %r19, %r79;
	add.s32 	%r111, %r110, %r79;
	rem.s32 	%r201, %r111, %r79;

$L__BB0_25:
	add.s32 	%r113, %r201, %r5;
	cvt.s64.s32 	%rd9, %r113;
	mul.wide.s32 	%rd54, %r113, 4;
	add.s64 	%rd55, %rd6, %rd54;
	add.s64 	%rd56, %rd5, %rd54;
	add.s64 	%rd57, %rd4, %rd54;
	ld.global.nc.f32 	%f418, [%rd55];
	ld.global.nc.f32 	%f417, [%rd56];
	mul.f32 	%f190, %f417, %f417;
	fma.rn.f32 	%f191, %f418, %f418, %f190;
	ld.global.nc.f32 	%f416, [%rd57];
	fma.rn.f32 	%f192, %f416, %f416, %f191;
	setp.eq.f32 	%p25, %f192, 0f00000000;
	mov.u32 	%r202, %r6;
	@%p25 bra 	$L__BB0_27;

	add.s64 	%rd58, %rd3, %rd9;
	ld.global.nc.u8 	%rs11, [%rd58];
	cvt.u32.u16 	%r114, %rs11;
	and.b32  	%r202, %r114, 255;

$L__BB0_27:
	setp.gt.u32 	%p26, %r202, %r6;
	@%p26 bra 	$L__BB0_29;
	bra.uni 	$L__BB0_28;

$L__BB0_29:
	add.s32 	%r118, %r202, 1;
	mul.lo.s32 	%r119, %r118, %r202;
	shr.u32 	%r120, %r119, 1;
	add.s32 	%r203, %r120, %r6;
	bra.uni 	$L__BB0_30;

$L__BB0_28:
	add.s32 	%r115, %r6, 1;
	mul.lo.s32 	%r116, %r115, %r6;
	shr.u32 	%r117, %r116, 1;
	add.s32 	%r203, %r202, %r117;

$L__BB0_30:
	mul.wide.u32 	%rd59, %r203, 4;
	add.s64 	%rd60, %rd2, %rd59;
	ld.global.nc.f32 	%f34, [%rd60];
	@%p26 bra 	$L__BB0_32;
	bra.uni 	$L__BB0_31;

$L__BB0_32:
	add.s32 	%r124, %r202, 1;
	mul.lo.s32 	%r125, %r124, %r202;
	shr.u32 	%r126, %r125, 1;
	add.s32 	%r204, %r126, %r6;
	bra.uni 	$L__BB0_33;

$L__BB0_31:
	add.s32 	%r121, %r6, 1;
	mul.lo.s32 	%r122, %r121, %r6;
	shr.u32 	%r123, %r122, 1;
	add.s32 	%r204, %r202, %r123;

$L__BB0_33:
	mul.wide.u32 	%rd61, %r204, 4;
	add.s64 	%rd62, %rd1, %rd61;
	add.f32 	%f35, %f34, %f34;
	ld.global.nc.f32 	%f36, [%rd62];
	mul.f32 	%f193, %f418, %f418;
	fma.rn.f32 	%f194, %f417, %f417, %f193;
	fma.rn.f32 	%f195, %f416, %f416, %f194;
	setp.neu.f32 	%p28, %f195, 0f00000000;
	@%p28 bra 	$L__BB0_36;
	bra.uni 	$L__BB0_34;

$L__BB0_36:
	ld.param.f32 	%f409, [adddmibulk_param_18];
	mul.f32 	%f214, %f409, %f409;
	div.rn.f32 	%f215, %f35, %f214;
	sub.f32 	%f216, %f418, %f1;
	mul.f32 	%f217, %f216, %f215;
	sub.f32 	%f218, %f417, %f2;
	mul.f32 	%f219, %f218, %f215;
	sub.f32 	%f220, %f416, %f3;
	mul.f32 	%f221, %f220, %f215;
	fma.rn.f32 	%f413, %f27, %f217, %f413;
	fma.rn.f32 	%f222, %f27, %f219, %f414;
	fma.rn.f32 	%f223, %f27, %f221, %f415;
	div.rn.f32 	%f224, %f36, %f409;
	mul.f32 	%f225, %f27, %f224;
	fma.rn.f32 	%f414, %f416, %f225, %f222;
	mul.f32 	%f226, %f417, %f225;
	sub.f32 	%f415, %f223, %f226;
	bra.uni 	$L__BB0_37;

$L__BB0_34:
	setp.ne.s16 	%p29, %rs8, 0;
	setp.leu.f32 	%p30, %f26, 0f3F7FBE77;
	or.pred  	%p31, %p29, %p30;
	@%p31 bra 	$L__BB0_37;

	ld.param.f32 	%f408, [adddmibulk_param_18];
	div.rn.f32 	%f196, %f36, %f35;
	mul.f32 	%f197, %f196, %f408;
	mul.f32 	%f198, %f3, %f197;
	sub.f32 	%f199, %f2, %f198;
	fma.rn.f32 	%f200, %f2, %f197, %f3;
	mul.f32 	%f201, %f408, %f408;
	div.rn.f32 	%f202, %f35, %f201;
	sub.f32 	%f203, %f199, %f2;
	sub.f32 	%f204, %f200, %f3;
	sub.f32 	%f205, %f1, %f1;
	mul.f32 	%f206, %f205, %f202;
	mul.f32 	%f207, %f202, %f203;
	mul.f32 	%f208, %f202, %f204;
	fma.rn.f32 	%f413, %f27, %f206, %f413;
	fma.rn.f32 	%f209, %f27, %f207, %f414;
	fma.rn.f32 	%f210, %f27, %f208, %f415;
	div.rn.f32 	%f211, %f36, %f408;
	mul.f32 	%f212, %f27, %f211;
	fma.rn.f32 	%f414, %f212, %f200, %f209;
	mul.f32 	%f213, %f212, %f199;
	sub.f32 	%f415, %f210, %f213;

$L__BB0_37:
	ld.param.u64 	%rd124, [adddmibulk_param_11];
	cvta.to.global.u64 	%rd63, %rd124;
	add.s64 	%rd65, %rd63, %rd37;
	ld.global.nc.f32 	%f46, [%rd65];
	mul.f32 	%f47, %f5, %f46;
	setp.leu.f32 	%p32, %f47, 0f00000000;
	@%p32 bra 	$L__BB0_54;

	setp.lt.s32 	%p33, %r2, 1;
	and.b16  	%rs3, %rs7, 2;
	setp.eq.s16 	%p34, %rs3, 0;
	mov.f32 	%f422, 0f00000000;
	and.pred  	%p35, %p33, %p34;
	mov.f32 	%f423, %f422;
	mov.f32 	%f424, %f422;
	mov.u32 	%r206, %r6;
	@%p35 bra 	$L__BB0_44;

	add.s32 	%r31, %r2, -1;
	@%p34 bra 	$L__BB0_41;
	bra.uni 	$L__BB0_40;

$L__BB0_41:
	max.s32 	%r205, %r31, 0;
	bra.uni 	$L__BB0_42;

$L__BB0_40:
	rem.s32 	%r127, %r31, %r80;
	add.s32 	%r128, %r127, %r80;
	rem.s32 	%r205, %r128, %r80;

$L__BB0_42:
	add.s32 	%r129, %r205, %r4;
	mad.lo.s32 	%r130, %r129, %r79, %r1;
	cvt.s64.s32 	%rd10, %r130;
	mul.wide.s32 	%rd66, %r130, 4;
	add.s64 	%rd67, %rd6, %rd66;
	add.s64 	%rd68, %rd5, %rd66;
	add.s64 	%rd69, %rd4, %rd66;
	ld.global.nc.f32 	%f424, [%rd67];
	ld.global.nc.f32 	%f423, [%rd68];
	mul.f32 	%f230, %f423, %f423;
	fma.rn.f32 	%f231, %f424, %f424, %f230;
	ld.global.nc.f32 	%f422, [%rd69];
	fma.rn.f32 	%f232, %f422, %f422, %f231;
	setp.eq.f32 	%p37, %f232, 0f00000000;
	mov.u32 	%r206, %r6;
	@%p37 bra 	$L__BB0_44;

	add.s64 	%rd70, %rd3, %rd10;
	ld.global.nc.u8 	%rs12, [%rd70];
	cvt.u32.u16 	%r131, %rs12;
	and.b32  	%r206, %r131, 255;

$L__BB0_44:
	setp.gt.u32 	%p38, %r206, %r6;
	@%p38 bra 	$L__BB0_46;
	bra.uni 	$L__BB0_45;

$L__BB0_46:
	add.s32 	%r135, %r206, 1;
	mul.lo.s32 	%r136, %r135, %r206;
	shr.u32 	%r137, %r136, 1;
	add.s32 	%r207, %r137, %r6;
	bra.uni 	$L__BB0_47;

$L__BB0_45:
	add.s32 	%r132, %r6, 1;
	mul.lo.s32 	%r133, %r132, %r6;
	shr.u32 	%r134, %r133, 1;
	add.s32 	%r207, %r206, %r134;

$L__BB0_47:
	mul.wide.u32 	%rd71, %r207, 4;
	add.s64 	%rd72, %rd2, %rd71;
	ld.global.nc.f32 	%f54, [%rd72];
	@%p38 bra 	$L__BB0_49;
	bra.uni 	$L__BB0_48;

$L__BB0_49:
	add.s32 	%r141, %r206, 1;
	mul.lo.s32 	%r142, %r141, %r206;
	shr.u32 	%r143, %r142, 1;
	add.s32 	%r208, %r143, %r6;
	bra.uni 	$L__BB0_50;

$L__BB0_48:
	add.s32 	%r138, %r6, 1;
	mul.lo.s32 	%r139, %r138, %r6;
	shr.u32 	%r140, %r139, 1;
	add.s32 	%r208, %r206, %r140;

$L__BB0_50:
	mul.wide.u32 	%rd73, %r208, 4;
	add.s64 	%rd74, %rd1, %rd73;
	add.f32 	%f55, %f54, %f54;
	ld.global.nc.f32 	%f56, [%rd74];
	mul.f32 	%f233, %f424, %f424;
	fma.rn.f32 	%f234, %f423, %f423, %f233;
	fma.rn.f32 	%f235, %f422, %f422, %f234;
	setp.neu.f32 	%p40, %f235, 0f00000000;
	@%p40 bra 	$L__BB0_53;
	bra.uni 	$L__BB0_51;

$L__BB0_53:
	mul.f32 	%f254, %f132, %f132;
	div.rn.f32 	%f255, %f55, %f254;
	sub.f32 	%f256, %f424, %f1;
	mul.f32 	%f257, %f256, %f255;
	sub.f32 	%f258, %f423, %f2;
	mul.f32 	%f259, %f258, %f255;
	sub.f32 	%f260, %f422, %f3;
	mul.f32 	%f261, %f260, %f255;
	fma.rn.f32 	%f262, %f47, %f257, %f413;
	fma.rn.f32 	%f414, %f47, %f259, %f414;
	fma.rn.f32 	%f263, %f47, %f261, %f415;
	div.rn.f32 	%f264, %f56, %f132;
	mul.f32 	%f265, %f47, %f264;
	fma.rn.f32 	%f413, %f422, %f265, %f262;
	mul.f32 	%f266, %f424, %f265;
	sub.f32 	%f415, %f263, %f266;
	bra.uni 	$L__BB0_54;

$L__BB0_51:
	setp.ne.s16 	%p41, %rs8, 0;
	setp.leu.f32 	%p42, %f46, 0f3F7FBE77;
	or.pred  	%p43, %p41, %p42;
	@%p43 bra 	$L__BB0_54;

	div.rn.f32 	%f236, %f56, %f55;
	mul.f32 	%f237, %f236, %f132;
	mul.f32 	%f238, %f3, %f237;
	sub.f32 	%f239, %f1, %f238;
	fma.rn.f32 	%f240, %f1, %f237, %f3;
	mul.f32 	%f241, %f132, %f132;
	div.rn.f32 	%f242, %f55, %f241;
	sub.f32 	%f243, %f239, %f1;
	sub.f32 	%f244, %f240, %f3;
	mul.f32 	%f245, %f242, %f243;
	sub.f32 	%f246, %f2, %f2;
	mul.f32 	%f247, %f246, %f242;
	mul.f32 	%f248, %f242, %f244;
	fma.rn.f32 	%f249, %f47, %f245, %f413;
	fma.rn.f32 	%f414, %f47, %f247, %f414;
	fma.rn.f32 	%f250, %f47, %f248, %f415;
	div.rn.f32 	%f251, %f56, %f132;
	mul.f32 	%f252, %f47, %f251;
	fma.rn.f32 	%f413, %f252, %f240, %f249;
	mul.f32 	%f253, %f252, %f239;
	sub.f32 	%f415, %f250, %f253;

$L__BB0_54:
	ld.param.u64 	%rd125, [adddmibulk_param_12];
	cvta.to.global.u64 	%rd75, %rd125;
	add.s64 	%rd77, %rd75, %rd37;
	ld.global.nc.f32 	%f66, [%rd77];
	mul.f32 	%f67, %f5, %f66;
	setp.leu.f32 	%p44, %f67, 0f00000000;
	@%p44 bra 	$L__BB0_71;

	add.s32 	%r43, %r2, 1;
	setp.ge.s32 	%p45, %r43, %r80;
	and.b16  	%rs4, %rs7, 2;
	setp.eq.s16 	%p46, %rs4, 0;
	mov.f32 	%f428, 0f00000000;
	and.pred  	%p47, %p45, %p46;
	mov.f32 	%f429, %f428;
	mov.f32 	%f430, %f428;
	mov.u32 	%r210, %r6;
	@%p47 bra 	$L__BB0_61;

	@%p46 bra 	$L__BB0_58;
	bra.uni 	$L__BB0_57;

$L__BB0_58:
	add.s32 	%r146, %r80, -1;
	min.s32 	%r209, %r43, %r146;
	bra.uni 	$L__BB0_59;

$L__BB0_57:
	rem.s32 	%r144, %r43, %r80;
	add.s32 	%r145, %r144, %r80;
	rem.s32 	%r209, %r145, %r80;

$L__BB0_59:
	add.s32 	%r147, %r209, %r4;
	mad.lo.s32 	%r148, %r147, %r79, %r1;
	cvt.s64.s32 	%rd11, %r148;
	mul.wide.s32 	%rd78, %r148, 4;
	add.s64 	%rd79, %rd6, %rd78;
	add.s64 	%rd80, %rd5, %rd78;
	add.s64 	%rd81, %rd4, %rd78;
	ld.global.nc.f32 	%f430, [%rd79];
	ld.global.nc.f32 	%f429, [%rd80];
	mul.f32 	%f270, %f429, %f429;
	fma.rn.f32 	%f271, %f430, %f430, %f270;
	ld.global.nc.f32 	%f428, [%rd81];
	fma.rn.f32 	%f272, %f428, %f428, %f271;
	setp.eq.f32 	%p49, %f272, 0f00000000;
	mov.u32 	%r210, %r6;
	@%p49 bra 	$L__BB0_61;

	add.s64 	%rd82, %rd3, %rd11;
	ld.global.nc.u8 	%rs13, [%rd82];
	cvt.u32.u16 	%r149, %rs13;
	and.b32  	%r210, %r149, 255;

$L__BB0_61:
	setp.gt.u32 	%p50, %r210, %r6;
	@%p50 bra 	$L__BB0_63;
	bra.uni 	$L__BB0_62;

$L__BB0_63:
	add.s32 	%r153, %r210, 1;
	mul.lo.s32 	%r154, %r153, %r210;
	shr.u32 	%r155, %r154, 1;
	add.s32 	%r211, %r155, %r6;
	bra.uni 	$L__BB0_64;

$L__BB0_62:
	add.s32 	%r150, %r6, 1;
	mul.lo.s32 	%r151, %r150, %r6;
	shr.u32 	%r152, %r151, 1;
	add.s32 	%r211, %r210, %r152;

$L__BB0_64:
	mul.wide.u32 	%rd83, %r211, 4;
	add.s64 	%rd84, %rd2, %rd83;
	ld.global.nc.f32 	%f74, [%rd84];
	@%p50 bra 	$L__BB0_66;
	bra.uni 	$L__BB0_65;

$L__BB0_66:
	add.s32 	%r159, %r210, 1;
	mul.lo.s32 	%r160, %r159, %r210;
	shr.u32 	%r161, %r160, 1;
	add.s32 	%r212, %r161, %r6;
	bra.uni 	$L__BB0_67;

$L__BB0_65:
	add.s32 	%r156, %r6, 1;
	mul.lo.s32 	%r157, %r156, %r6;
	shr.u32 	%r158, %r157, 1;
	add.s32 	%r212, %r210, %r158;

$L__BB0_67:
	mul.wide.u32 	%rd85, %r212, 4;
	add.s64 	%rd86, %rd1, %rd85;
	add.f32 	%f75, %f74, %f74;
	ld.global.nc.f32 	%f76, [%rd86];
	mul.f32 	%f273, %f430, %f430;
	fma.rn.f32 	%f274, %f429, %f429, %f273;
	fma.rn.f32 	%f275, %f428, %f428, %f274;
	setp.neu.f32 	%p52, %f275, 0f00000000;
	@%p52 bra 	$L__BB0_70;
	bra.uni 	$L__BB0_68;

$L__BB0_70:
	mul.f32 	%f294, %f132, %f132;
	div.rn.f32 	%f295, %f75, %f294;
	sub.f32 	%f296, %f430, %f1;
	mul.f32 	%f297, %f296, %f295;
	sub.f32 	%f298, %f429, %f2;
	mul.f32 	%f299, %f298, %f295;
	sub.f32 	%f300, %f428, %f3;
	mul.f32 	%f301, %f300, %f295;
	fma.rn.f32 	%f302, %f67, %f297, %f413;
	fma.rn.f32 	%f414, %f67, %f299, %f414;
	fma.rn.f32 	%f303, %f67, %f301, %f415;
	div.rn.f32 	%f304, %f76, %f132;
	mul.f32 	%f305, %f67, %f304;
	mul.f32 	%f306, %f428, %f305;
	sub.f32 	%f413, %f302, %f306;
	fma.rn.f32 	%f415, %f430, %f305, %f303;
	bra.uni 	$L__BB0_71;

$L__BB0_68:
	setp.ne.s16 	%p53, %rs8, 0;
	setp.leu.f32 	%p54, %f66, 0f3F7FBE77;
	or.pred  	%p55, %p53, %p54;
	@%p55 bra 	$L__BB0_71;

	div.rn.f32 	%f276, %f76, %f75;
	mul.f32 	%f277, %f276, %f132;
	fma.rn.f32 	%f278, %f3, %f277, %f1;
	mul.f32 	%f279, %f1, %f277;
	sub.f32 	%f280, %f3, %f279;
	mul.f32 	%f281, %f132, %f132;
	div.rn.f32 	%f282, %f75, %f281;
	sub.f32 	%f283, %f278, %f1;
	sub.f32 	%f284, %f280, %f3;
	mul.f32 	%f285, %f282, %f283;
	sub.f32 	%f286, %f2, %f2;
	mul.f32 	%f287, %f286, %f282;
	mul.f32 	%f288, %f282, %f284;
	fma.rn.f32 	%f289, %f67, %f285, %f413;
	fma.rn.f32 	%f414, %f67, %f287, %f414;
	fma.rn.f32 	%f290, %f67, %f288, %f415;
	div.rn.f32 	%f291, %f76, %f132;
	mul.f32 	%f292, %f67, %f291;
	mul.f32 	%f293, %f292, %f280;
	sub.f32 	%f413, %f289, %f293;
	fma.rn.f32 	%f415, %f292, %f278, %f290;

$L__BB0_71:
	setp.ne.s16 	%p56, %rs8, 0;
	setp.eq.s32 	%p57, %r81, 1;
	and.pred  	%p58, %p57, %p56;
	@%p58 bra 	$L__BB0_106;

	ld.param.u64 	%rd127, [adddmibulk_param_13];
	cvta.to.global.u64 	%rd87, %rd127;
	add.s64 	%rd89, %rd87, %rd37;
	ld.global.nc.f32 	%f86, [%rd89];
	mul.f32 	%f87, %f5, %f86;
	setp.leu.f32 	%p59, %f87, 0f00000000;
	@%p59 bra 	$L__BB0_89;

	setp.lt.s32 	%p60, %r3, 1;
	and.b16  	%rs5, %rs7, 4;
	setp.eq.s16 	%p61, %rs5, 0;
	mov.f32 	%f434, 0f00000000;
	and.pred  	%p62, %p60, %p61;
	mov.f32 	%f435, %f434;
	mov.f32 	%f436, %f434;
	mov.u32 	%r214, %r6;
	@%p62 bra 	$L__BB0_79;

	add.s32 	%r55, %r3, -1;
	@%p61 bra 	$L__BB0_76;
	bra.uni 	$L__BB0_75;

$L__BB0_76:
	max.s32 	%r213, %r55, 0;
	bra.uni 	$L__BB0_77;

$L__BB0_75:
	rem.s32 	%r162, %r55, %r81;
	add.s32 	%r163, %r162, %r81;
	rem.s32 	%r213, %r163, %r81;

$L__BB0_77:
	mad.lo.s32 	%r164, %r213, %r80, %r2;
	mad.lo.s32 	%r165, %r164, %r79, %r1;
	cvt.s64.s32 	%rd12, %r165;
	mul.wide.s32 	%rd90, %r165, 4;
	add.s64 	%rd91, %rd6, %rd90;
	add.s64 	%rd92, %rd5, %rd90;
	add.s64 	%rd93, %rd4, %rd90;
	ld.global.nc.f32 	%f436, [%rd91];
	ld.global.nc.f32 	%f435, [%rd92];
	mul.f32 	%f310, %f435, %f435;
	fma.rn.f32 	%f311, %f436, %f436, %f310;
	ld.global.nc.f32 	%f434, [%rd93];
	fma.rn.f32 	%f312, %f434, %f434, %f311;
	setp.eq.f32 	%p64, %f312, 0f00000000;
	mov.u32 	%r214, %r6;
	@%p64 bra 	$L__BB0_79;

	add.s64 	%rd94, %rd3, %rd12;
	ld.global.nc.u8 	%rs14, [%rd94];
	cvt.u32.u16 	%r166, %rs14;
	and.b32  	%r214, %r166, 255;

$L__BB0_79:
	setp.gt.u32 	%p65, %r214, %r6;
	@%p65 bra 	$L__BB0_81;
	bra.uni 	$L__BB0_80;

$L__BB0_81:
	add.s32 	%r170, %r214, 1;
	mul.lo.s32 	%r171, %r170, %r214;
	shr.u32 	%r172, %r171, 1;
	add.s32 	%r215, %r172, %r6;
	bra.uni 	$L__BB0_82;

$L__BB0_80:
	add.s32 	%r167, %r6, 1;
	mul.lo.s32 	%r168, %r167, %r6;
	shr.u32 	%r169, %r168, 1;
	add.s32 	%r215, %r214, %r169;

$L__BB0_82:
	mul.wide.u32 	%rd95, %r215, 4;
	add.s64 	%rd96, %rd2, %rd95;
	ld.global.nc.f32 	%f94, [%rd96];
	@%p65 bra 	$L__BB0_84;
	bra.uni 	$L__BB0_83;

$L__BB0_84:
	add.s32 	%r176, %r214, 1;
	mul.lo.s32 	%r177, %r176, %r214;
	shr.u32 	%r178, %r177, 1;
	add.s32 	%r216, %r178, %r6;
	bra.uni 	$L__BB0_85;

$L__BB0_83:
	add.s32 	%r173, %r6, 1;
	mul.lo.s32 	%r174, %r173, %r6;
	shr.u32 	%r175, %r174, 1;
	add.s32 	%r216, %r214, %r175;

$L__BB0_85:
	mul.wide.u32 	%rd97, %r216, 4;
	add.s64 	%rd98, %rd1, %rd97;
	add.f32 	%f95, %f94, %f94;
	ld.global.nc.f32 	%f96, [%rd98];
	mul.f32 	%f313, %f436, %f436;
	fma.rn.f32 	%f314, %f435, %f435, %f313;
	fma.rn.f32 	%f315, %f434, %f434, %f314;
	setp.neu.f32 	%p67, %f315, 0f00000000;
	@%p67 bra 	$L__BB0_88;
	bra.uni 	$L__BB0_86;

$L__BB0_88:
	ld.param.f32 	%f407, [adddmibulk_param_20];
	mul.f32 	%f334, %f407, %f407;
	div.rn.f32 	%f335, %f95, %f334;
	sub.f32 	%f336, %f436, %f1;
	mul.f32 	%f337, %f336, %f335;
	sub.f32 	%f338, %f435, %f2;
	mul.f32 	%f339, %f338, %f335;
	sub.f32 	%f340, %f434, %f3;
	mul.f32 	%f341, %f340, %f335;
	fma.rn.f32 	%f342, %f87, %f337, %f413;
	fma.rn.f32 	%f343, %f87, %f339, %f414;
	fma.rn.f32 	%f415, %f87, %f341, %f415;
	div.rn.f32 	%f344, %f96, %f407;
	mul.f32 	%f345, %f87, %f344;
	mul.f32 	%f346, %f435, %f345;
	sub.f32 	%f413, %f342, %f346;
	fma.rn.f32 	%f414, %f436, %f345, %f343;
	bra.uni 	$L__BB0_89;

$L__BB0_86:
	setp.leu.f32 	%p69, %f86, 0f3F7FBE77;
	or.pred  	%p70, %p56, %p69;
	@%p70 bra 	$L__BB0_89;

	ld.param.f32 	%f406, [adddmibulk_param_20];
	div.rn.f32 	%f316, %f96, %f95;
	mul.f32 	%f317, %f316, %f406;
	fma.rn.f32 	%f318, %f2, %f317, %f1;
	mul.f32 	%f319, %f1, %f317;
	sub.f32 	%f320, %f2, %f319;
	mul.f32 	%f321, %f406, %f406;
	div.rn.f32 	%f322, %f95, %f321;
	sub.f32 	%f323, %f318, %f1;
	sub.f32 	%f324, %f320, %f2;
	mul.f32 	%f325, %f322, %f323;
	mul.f32 	%f326, %f322, %f324;
	sub.f32 	%f327, %f3, %f3;
	mul.f32 	%f328, %f327, %f322;
	fma.rn.f32 	%f329, %f87, %f325, %f413;
	fma.rn.f32 	%f330, %f87, %f326, %f414;
	fma.rn.f32 	%f415, %f87, %f328, %f415;
	div.rn.f32 	%f331, %f96, %f406;
	mul.f32 	%f332, %f87, %f331;
	mul.f32 	%f333, %f332, %f320;
	sub.f32 	%f413, %f329, %f333;
	fma.rn.f32 	%f414, %f332, %f318, %f330;

$L__BB0_89:
	ld.param.u64 	%rd128, [adddmibulk_param_14];
	cvta.to.global.u64 	%rd99, %rd128;
	add.s64 	%rd101, %rd99, %rd37;
	ld.global.nc.f32 	%f106, [%rd101];
	mul.f32 	%f107, %f5, %f106;
	setp.leu.f32 	%p71, %f107, 0f00000000;
	@%p71 bra 	$L__BB0_106;

	add.s32 	%r67, %r3, 1;
	setp.ge.s32 	%p72, %r67, %r81;
	and.b16  	%rs6, %rs7, 4;
	setp.eq.s16 	%p73, %rs6, 0;
	mov.f32 	%f440, 0f00000000;
	and.pred  	%p74, %p72, %p73;
	mov.f32 	%f441, %f440;
	mov.f32 	%f442, %f440;
	mov.u32 	%r218, %r6;
	@%p74 bra 	$L__BB0_96;

	@%p73 bra 	$L__BB0_93;
	bra.uni 	$L__BB0_92;

$L__BB0_93:
	add.s32 	%r181, %r81, -1;
	min.s32 	%r217, %r67, %r181;
	bra.uni 	$L__BB0_94;

$L__BB0_92:
	rem.s32 	%r179, %r67, %r81;
	add.s32 	%r180, %r179, %r81;
	rem.s32 	%r217, %r180, %r81;

$L__BB0_94:
	mad.lo.s32 	%r182, %r217, %r80, %r2;
	mad.lo.s32 	%r183, %r182, %r79, %r1;
	cvt.s64.s32 	%rd13, %r183;
	mul.wide.s32 	%rd102, %r183, 4;
	add.s64 	%rd103, %rd6, %rd102;
	add.s64 	%rd104, %rd5, %rd102;
	add.s64 	%rd105, %rd4, %rd102;
	ld.global.nc.f32 	%f442, [%rd103];
	ld.global.nc.f32 	%f441, [%rd104];
	mul.f32 	%f350, %f441, %f441;
	fma.rn.f32 	%f351, %f442, %f442, %f350;
	ld.global.nc.f32 	%f440, [%rd105];
	fma.rn.f32 	%f352, %f440, %f440, %f351;
	setp.eq.f32 	%p76, %f352, 0f00000000;
	mov.u32 	%r218, %r6;
	@%p76 bra 	$L__BB0_96;

	add.s64 	%rd106, %rd3, %rd13;
	ld.global.nc.u8 	%rs15, [%rd106];
	cvt.u32.u16 	%r184, %rs15;
	and.b32  	%r218, %r184, 255;

$L__BB0_96:
	setp.gt.u32 	%p77, %r218, %r6;
	@%p77 bra 	$L__BB0_98;
	bra.uni 	$L__BB0_97;

$L__BB0_98:
	add.s32 	%r188, %r218, 1;
	mul.lo.s32 	%r189, %r188, %r218;
	shr.u32 	%r190, %r189, 1;
	add.s32 	%r219, %r190, %r6;
	bra.uni 	$L__BB0_99;

$L__BB0_97:
	add.s32 	%r185, %r6, 1;
	mul.lo.s32 	%r186, %r185, %r6;
	shr.u32 	%r187, %r186, 1;
	add.s32 	%r219, %r218, %r187;

$L__BB0_99:
	mul.wide.u32 	%rd107, %r219, 4;
	add.s64 	%rd108, %rd2, %rd107;
	ld.global.nc.f32 	%f114, [%rd108];
	@%p77 bra 	$L__BB0_101;
	bra.uni 	$L__BB0_100;

$L__BB0_101:
	add.s32 	%r194, %r218, 1;
	mul.lo.s32 	%r195, %r194, %r218;
	shr.u32 	%r196, %r195, 1;
	add.s32 	%r220, %r196, %r6;
	bra.uni 	$L__BB0_102;

$L__BB0_100:
	add.s32 	%r191, %r6, 1;
	mul.lo.s32 	%r192, %r191, %r6;
	shr.u32 	%r193, %r192, 1;
	add.s32 	%r220, %r218, %r193;

$L__BB0_102:
	mul.wide.u32 	%rd109, %r220, 4;
	add.s64 	%rd110, %rd1, %rd109;
	add.f32 	%f115, %f114, %f114;
	ld.global.nc.f32 	%f116, [%rd110];
	mul.f32 	%f353, %f442, %f442;
	fma.rn.f32 	%f354, %f441, %f441, %f353;
	fma.rn.f32 	%f355, %f440, %f440, %f354;
	setp.neu.f32 	%p79, %f355, 0f00000000;
	@%p79 bra 	$L__BB0_105;
	bra.uni 	$L__BB0_103;

$L__BB0_105:
	ld.param.f32 	%f405, [adddmibulk_param_20];
	mul.f32 	%f374, %f405, %f405;
	div.rn.f32 	%f375, %f115, %f374;
	sub.f32 	%f376, %f442, %f1;
	mul.f32 	%f377, %f376, %f375;
	sub.f32 	%f378, %f441, %f2;
	mul.f32 	%f379, %f378, %f375;
	sub.f32 	%f380, %f440, %f3;
	mul.f32 	%f381, %f380, %f375;
	fma.rn.f32 	%f382, %f107, %f377, %f413;
	fma.rn.f32 	%f383, %f107, %f379, %f414;
	fma.rn.f32 	%f415, %f107, %f381, %f415;
	div.rn.f32 	%f384, %f116, %f405;
	mul.f32 	%f385, %f107, %f384;
	fma.rn.f32 	%f413, %f441, %f385, %f382;
	mul.f32 	%f386, %f442, %f385;
	sub.f32 	%f414, %f383, %f386;
	bra.uni 	$L__BB0_106;

$L__BB0_103:
	setp.leu.f32 	%p81, %f106, 0f3F7FBE77;
	or.pred  	%p82, %p56, %p81;
	@%p82 bra 	$L__BB0_106;

	ld.param.f32 	%f404, [adddmibulk_param_20];
	div.rn.f32 	%f356, %f116, %f115;
	mul.f32 	%f357, %f356, %f404;
	mul.f32 	%f358, %f2, %f357;
	sub.f32 	%f359, %f1, %f358;
	fma.rn.f32 	%f360, %f1, %f357, %f2;
	mul.f32 	%f361, %f404, %f404;
	div.rn.f32 	%f362, %f115, %f361;
	sub.f32 	%f363, %f359, %f1;
	sub.f32 	%f364, %f360, %f2;
	mul.f32 	%f365, %f362, %f363;
	mul.f32 	%f366, %f362, %f364;
	sub.f32 	%f367, %f3, %f3;
	mul.f32 	%f368, %f367, %f362;
	fma.rn.f32 	%f369, %f107, %f365, %f413;
	fma.rn.f32 	%f370, %f107, %f366, %f414;
	fma.rn.f32 	%f415, %f107, %f368, %f415;
	div.rn.f32 	%f371, %f116, %f404;
	mul.f32 	%f372, %f107, %f371;
	fma.rn.f32 	%f413, %f372, %f360, %f369;
	mul.f32 	%f373, %f372, %f359;
	sub.f32 	%f414, %f370, %f373;

$L__BB0_106:
	ld.param.u64 	%rd129, [adddmibulk_param_6];
	ld.param.f32 	%f446, [adddmibulk_param_7];
	setp.eq.s64 	%p83, %rd129, 0;
	@%p83 bra 	$L__BB0_108;

	ld.param.u64 	%rd130, [adddmibulk_param_6];
	ld.param.f32 	%f400, [adddmibulk_param_7];
	cvta.to.global.u64 	%rd111, %rd130;
	add.s64 	%rd113, %rd111, %rd37;
	ld.global.nc.f32 	%f387, [%rd113];
	mul.f32 	%f446, %f387, %f400;

$L__BB0_108:
	setp.eq.f32 	%p84, %f446, 0f00000000;
	mov.f32 	%f447, 0f00000000;
	@%p84 bra 	$L__BB0_110;

	rcp.rn.f32 	%f447, %f446;

$L__BB0_110:
	ld.param.u64 	%rd132, [adddmibulk_param_2];
	ld.param.u64 	%rd131, [adddmibulk_param_1];
	ld.param.u64 	%rd126, [adddmibulk_param_0];
	cvta.to.global.u64 	%rd114, %rd126;
	add.s64 	%rd116, %rd114, %rd37;
	ld.global.f32 	%f389, [%rd116];
	fma.rn.f32 	%f390, %f413, %f447, %f389;
	st.global.f32 	[%rd116], %f390;
	cvta.to.global.u64 	%rd117, %rd131;
	add.s64 	%rd118, %rd117, %rd37;
	ld.global.f32 	%f391, [%rd118];
	fma.rn.f32 	%f392, %f414, %f447, %f391;
	st.global.f32 	[%rd118], %f392;
	cvta.to.global.u64 	%rd119, %rd132;
	add.s64 	%rd120, %rd119, %rd37;
	ld.global.f32 	%f393, [%rd120];
	fma.rn.f32 	%f394, %f415, %f447, %f393;
	st.global.f32 	[%rd120], %f394;

$L__BB0_111:
	ret;

}

`
	)
