package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for addexchange kernel
var addexchangeCode cu.Function

// Stores the arguments for addexchange kernel invocation
type addexchangeArgsT struct {
	argBx unsafe.Pointer
	argBy unsafe.Pointer
	argBz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argMs unsafe.Pointer
	argMsMul float32
	argVol unsafe.Pointer
	argFxm unsafe.Pointer
	argFxp unsafe.Pointer
	argFym unsafe.Pointer
	argFyp unsafe.Pointer
	argFzm unsafe.Pointer
	argFzp unsafe.Pointer
	argALUT2d unsafe.Pointer
	argRegions unsafe.Pointer
	argWx float32
	argWy float32
	argWz float32
	argPhiFloor float32
	argNx int
	argNy int
	argNz int
	argPBC byte
	argptr [25]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addexchange kernel invocation
var addexchangeArgs addexchangeArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addexchangeArgs.argptr[0] = unsafe.Pointer(&addexchangeArgs.argBx)
	addexchangeArgs.argptr[1] = unsafe.Pointer(&addexchangeArgs.argBy)
	addexchangeArgs.argptr[2] = unsafe.Pointer(&addexchangeArgs.argBz)
	addexchangeArgs.argptr[3] = unsafe.Pointer(&addexchangeArgs.argMx)
	addexchangeArgs.argptr[4] = unsafe.Pointer(&addexchangeArgs.argMy)
	addexchangeArgs.argptr[5] = unsafe.Pointer(&addexchangeArgs.argMz)
	addexchangeArgs.argptr[6] = unsafe.Pointer(&addexchangeArgs.argMs)
	addexchangeArgs.argptr[7] = unsafe.Pointer(&addexchangeArgs.argMsMul)
	addexchangeArgs.argptr[8] = unsafe.Pointer(&addexchangeArgs.argVol)
	addexchangeArgs.argptr[9] = unsafe.Pointer(&addexchangeArgs.argFxm)
	addexchangeArgs.argptr[10] = unsafe.Pointer(&addexchangeArgs.argFxp)
	addexchangeArgs.argptr[11] = unsafe.Pointer(&addexchangeArgs.argFym)
	addexchangeArgs.argptr[12] = unsafe.Pointer(&addexchangeArgs.argFyp)
	addexchangeArgs.argptr[13] = unsafe.Pointer(&addexchangeArgs.argFzm)
	addexchangeArgs.argptr[14] = unsafe.Pointer(&addexchangeArgs.argFzp)
	addexchangeArgs.argptr[15] = unsafe.Pointer(&addexchangeArgs.argALUT2d)
	addexchangeArgs.argptr[16] = unsafe.Pointer(&addexchangeArgs.argRegions)
	addexchangeArgs.argptr[17] = unsafe.Pointer(&addexchangeArgs.argWx)
	addexchangeArgs.argptr[18] = unsafe.Pointer(&addexchangeArgs.argWy)
	addexchangeArgs.argptr[19] = unsafe.Pointer(&addexchangeArgs.argWz)
	addexchangeArgs.argptr[20] = unsafe.Pointer(&addexchangeArgs.argPhiFloor)
	addexchangeArgs.argptr[21] = unsafe.Pointer(&addexchangeArgs.argNx)
	addexchangeArgs.argptr[22] = unsafe.Pointer(&addexchangeArgs.argNy)
	addexchangeArgs.argptr[23] = unsafe.Pointer(&addexchangeArgs.argNz)
	addexchangeArgs.argptr[24] = unsafe.Pointer(&addexchangeArgs.argPBC)
	}

// Wrapper for addexchange CUDA kernel, asynchronous.
func kAddexchangeAsync(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, Ms_ unsafe.Pointer, Ms_mul float32, vol unsafe.Pointer, fxm unsafe.Pointer, fxp unsafe.Pointer, fym unsafe.Pointer, fyp unsafe.Pointer, fzm unsafe.Pointer, fzp unsafe.Pointer, aLUT2d unsafe.Pointer, regions unsafe.Pointer, wx float32, wy float32, wz float32, phiFloor float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("addexchange")
	}

	addexchangeArgs.Lock()
	defer addexchangeArgs.Unlock()

	if addexchangeCode == 0 {
		addexchangeCode = fatbinLoad(addexchangeMap, "addexchange")
	}

	addexchangeArgs.argBx = Bx
	addexchangeArgs.argBy = By
	addexchangeArgs.argBz = Bz
	addexchangeArgs.argMx = mx
	addexchangeArgs.argMy = my
	addexchangeArgs.argMz = mz
	addexchangeArgs.argMs = Ms_
	addexchangeArgs.argMsMul = Ms_mul
	addexchangeArgs.argVol = vol
	addexchangeArgs.argFxm = fxm
	addexchangeArgs.argFxp = fxp
	addexchangeArgs.argFym = fym
	addexchangeArgs.argFyp = fyp
	addexchangeArgs.argFzm = fzm
	addexchangeArgs.argFzp = fzp
	addexchangeArgs.argALUT2d = aLUT2d
	addexchangeArgs.argRegions = regions
	addexchangeArgs.argWx = wx
	addexchangeArgs.argWy = wy
	addexchangeArgs.argWz = wz
	addexchangeArgs.argPhiFloor = phiFloor
	addexchangeArgs.argNx = Nx
	addexchangeArgs.argNy = Ny
	addexchangeArgs.argNz = Nz
	addexchangeArgs.argPBC = PBC
	
	args := addexchangeArgs.argptr[:]
	cu.LaunchKernel(addexchangeCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("addexchange")
	}
}

// maps compute capability on PTX code for addexchange kernel.
var addexchangeMap = map[int]string{
	0: "",
	52: addexchangePtx52,
}

// addexchange PTX code for various compute capabilities.
const (
	addexchangePtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	addexchange

.visible .entry addexchange(
	.param .u64 addexchange_param_0,
	.param .u64 addexchange_param_1,
	.param .u64 addexchange_param_2,
	.param .u64 addexchange_param_3,
	.param .u64 addexchange_param_4,
	.param .u64 addexchange_param_5,
	.param .u64 addexchange_param_6,
	.param .f32 addexchange_param_7,
	.param .u64 addexchange_param_8,
	.param .u64 addexchange_param_9,
	.param .u64 addexchange_param_10,
	.param .u64 addexchange_param_11,
	.param .u64 addexchange_param_12,
	.param .u64 addexchange_param_13,
	.param .u64 addexchange_param_14,
	.param .u64 addexchange_param_15,
	.param .u64 addexchange_param_16,
	.param .f32 addexchange_param_17,
	.param .f32 addexchange_param_18,
	.param .f32 addexchange_param_19,
	.param .f32 addexchange_param_20,
	.param .u32 addexchange_param_21,
	.param .u32 addexchange_param_22,
	.param .u32 addexchange_param_23,
	.param .u8 addexchange_param_24
)
{
	.reg .pred 	%p<47>;
	.reg .b16 	%rs<38>;
	.reg .f32 	%f<190>;
	.reg .b32 	%r<111>;
	.reg .b64 	%rd<114>;


	ld.param.u8 	%rs5, [addexchange_param_24];
	ld.param.u64 	%rd13, [addexchange_param_0];
	ld.param.u64 	%rd14, [addexchange_param_1];
	ld.param.u64 	%rd15, [addexchange_param_2];
	ld.param.u64 	%rd24, [addexchange_param_3];
	ld.param.u64 	%rd25, [addexchange_param_4];
	ld.param.u64 	%rd26, [addexchange_param_5];
	ld.param.u64 	%rd16, [addexchange_param_6];
	ld.param.u64 	%rd27, [addexchange_param_15];
	ld.param.u64 	%rd28, [addexchange_param_16];
	ld.param.u32 	%r30, [addexchange_param_21];
	ld.param.u32 	%r31, [addexchange_param_22];
	ld.param.u32 	%r32, [addexchange_param_23];
	cvta.to.global.u64 	%rd1, %rd27;
	cvta.to.global.u64 	%rd2, %rd28;
	cvta.to.global.u64 	%rd3, %rd26;
	cvta.to.global.u64 	%rd4, %rd25;
	cvta.to.global.u64 	%rd5, %rd24;
	mov.u32 	%r33, %ntid.x;
	mov.u32 	%r34, %ctaid.x;
	mov.u32 	%r35, %tid.x;
	mad.lo.s32 	%r1, %r34, %r33, %r35;
	mov.u32 	%r36, %ntid.y;
	mov.u32 	%r37, %ctaid.y;
	mov.u32 	%r38, %tid.y;
	mad.lo.s32 	%r2, %r37, %r36, %r38;
	mov.u32 	%r39, %ntid.z;
	mov.u32 	%r40, %ctaid.z;
	mov.u32 	%r41, %tid.z;
	mad.lo.s32 	%r3, %r40, %r39, %r41;
	setp.ge.s32 	%p1, %r1, %r30;
	setp.ge.s32 	%p2, %r2, %r31;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32 	%p4, %r3, %r32;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	$L__BB0_51;

	mul.lo.s32 	%r4, %r3, %r31;
	add.s32 	%r42, %r4, %r2;
	mul.lo.s32 	%r5, %r42, %r30;
	add.s32 	%r43, %r5, %r1;
	cvt.s64.s32 	%rd6, %r43;
	mul.wide.s32 	%rd29, %r43, 4;
	add.s64 	%rd30, %rd5, %rd29;
	add.s64 	%rd31, %rd4, %rd29;
	add.s64 	%rd32, %rd3, %rd29;
	ld.global.nc.f32 	%f1, [%rd30];
	ld.global.nc.f32 	%f2, [%rd31];
	mul.f32 	%f75, %f2, %f2;
	fma.rn.f32 	%f76, %f1, %f1, %f75;
	ld.global.nc.f32 	%f3, [%rd32];
	fma.rn.f32 	%f77, %f3, %f3, %f76;
	setp.eq.f32 	%p6, %f77, 0f00000000;
	@%p6 bra 	$L__BB0_51;

	ld.param.u64 	%rd107, [addexchange_param_8];
	cvta.to.global.u64 	%rd33, %rd107;
	shl.b64 	%rd34, %rd6, 2;
	add.s64 	%rd35, %rd33, %rd34;
	ld.global.nc.f32 	%f4, [%rd35];
	setp.le.f32 	%p7, %f4, 0f00000000;
	mov.f32 	%f173, 0f00000000;
	mov.f32 	%f174, 0f00000000;
	mov.f32 	%f175, 0f00000000;
	@%p7 bra 	$L__BB0_51;

	ld.param.f32 	%f161, [addexchange_param_20];
	mov.f32 	%f81, 0f358637BD;
	max.f32 	%f82, %f161, %f81;
	max.f32 	%f83, %f4, %f82;
	rcp.rn.f32 	%f5, %f83;
	add.s64 	%rd36, %rd2, %rd6;
	ld.global.nc.u8 	%rs1, [%rd36];
	and.b16  	%rs2, %rs5, 1;
	setp.eq.s16 	%p8, %rs2, 0;
	setp.lt.s32 	%p9, %r1, 1;
	and.pred  	%p10, %p9, %p8;
	@%p10 bra 	$L__BB0_10;

	ld.param.u64 	%rd111, [addexchange_param_9];
	cvta.to.global.u64 	%rd37, %rd111;
	add.s64 	%rd39, %rd37, %rd34;
	ld.global.nc.f32 	%f87, [%rd39];
	mul.f32 	%f6, %f5, %f87;
	setp.leu.f32 	%p11, %f6, 0f00000000;
	@%p11 bra 	$L__BB0_10;

	add.s32 	%r6, %r1, -1;
	@%p8 bra 	$L__BB0_7;
	bra.uni 	$L__BB0_6;

$L__BB0_7:
	max.s32 	%r105, %r6, 0;
	bra.uni 	$L__BB0_8;

$L__BB0_6:
	rem.s32 	%r44, %r6, %r30;
	add.s32 	%r45, %r44, %r30;
	rem.s32 	%r105, %r45, %r30;

$L__BB0_8:
	add.s32 	%r46, %r105, %r5;
	cvt.s64.s32 	%rd7, %r46;
	mul.wide.s32 	%rd40, %r46, 4;
	add.s64 	%rd41, %rd5, %rd40;
	add.s64 	%rd42, %rd4, %rd40;
	add.s64 	%rd43, %rd3, %rd40;
	ld.global.nc.f32 	%f7, [%rd41];
	ld.global.nc.f32 	%f8, [%rd42];
	mul.f32 	%f91, %f8, %f8;
	fma.rn.f32 	%f92, %f7, %f7, %f91;
	ld.global.nc.f32 	%f9, [%rd43];
	fma.rn.f32 	%f93, %f9, %f9, %f92;
	setp.eq.f32 	%p13, %f93, 0f00000000;
	@%p13 bra 	$L__BB0_10;

	ld.param.f32 	%f165, [addexchange_param_17];
	add.s64 	%rd44, %rd2, %rd7;
	ld.global.nc.u8 	%rs6, [%rd44];
	min.u16 	%rs9, %rs6, %rs1;
	max.u16 	%rs10, %rs6, %rs1;
	cvt.u32.u16 	%r47, %rs10;
	add.s32 	%r48, %r47, 1;
	mul.lo.s32 	%r49, %r48, %r47;
	shr.u32 	%r50, %r49, 1;
	cvt.u32.u16 	%r51, %rs9;
	add.s32 	%r52, %r50, %r51;
	mul.wide.s32 	%rd45, %r52, 4;
	add.s64 	%rd46, %rd1, %rd45;
	mul.f32 	%f94, %f6, %f165;
	ld.global.nc.f32 	%f95, [%rd46];
	mul.f32 	%f96, %f94, %f95;
	sub.f32 	%f97, %f7, %f1;
	sub.f32 	%f98, %f8, %f2;
	sub.f32 	%f99, %f9, %f3;
	fma.rn.f32 	%f175, %f97, %f96, 0f00000000;
	fma.rn.f32 	%f174, %f98, %f96, 0f00000000;
	fma.rn.f32 	%f173, %f99, %f96, 0f00000000;

$L__BB0_10:
	add.s32 	%r10, %r1, 1;
	setp.ge.s32 	%p14, %r10, %r30;
	and.pred  	%p16, %p14, %p8;
	@%p16 bra 	$L__BB0_17;

	ld.param.u64 	%rd110, [addexchange_param_10];
	cvta.to.global.u64 	%rd47, %rd110;
	add.s64 	%rd49, %rd47, %rd34;
	ld.global.nc.f32 	%f100, [%rd49];
	mul.f32 	%f16, %f5, %f100;
	setp.leu.f32 	%p17, %f16, 0f00000000;
	@%p17 bra 	$L__BB0_17;

	@%p8 bra 	$L__BB0_14;
	bra.uni 	$L__BB0_13;

$L__BB0_14:
	add.s32 	%r55, %r30, -1;
	min.s32 	%r106, %r10, %r55;
	bra.uni 	$L__BB0_15;

$L__BB0_13:
	rem.s32 	%r53, %r10, %r30;
	add.s32 	%r54, %r53, %r30;
	rem.s32 	%r106, %r54, %r30;

$L__BB0_15:
	add.s32 	%r56, %r106, %r5;
	cvt.s64.s32 	%rd8, %r56;
	mul.wide.s32 	%rd50, %r56, 4;
	add.s64 	%rd51, %rd5, %rd50;
	add.s64 	%rd52, %rd4, %rd50;
	add.s64 	%rd53, %rd3, %rd50;
	ld.global.nc.f32 	%f17, [%rd51];
	ld.global.nc.f32 	%f18, [%rd52];
	mul.f32 	%f101, %f18, %f18;
	fma.rn.f32 	%f102, %f17, %f17, %f101;
	ld.global.nc.f32 	%f19, [%rd53];
	fma.rn.f32 	%f103, %f19, %f19, %f102;
	setp.eq.f32 	%p19, %f103, 0f00000000;
	@%p19 bra 	$L__BB0_17;

	ld.param.f32 	%f164, [addexchange_param_17];
	add.s64 	%rd54, %rd2, %rd8;
	ld.global.nc.u8 	%rs11, [%rd54];
	min.u16 	%rs14, %rs11, %rs1;
	max.u16 	%rs15, %rs11, %rs1;
	cvt.u32.u16 	%r57, %rs15;
	add.s32 	%r58, %r57, 1;
	mul.lo.s32 	%r59, %r58, %r57;
	shr.u32 	%r60, %r59, 1;
	cvt.u32.u16 	%r61, %rs14;
	add.s32 	%r62, %r60, %r61;
	mul.wide.s32 	%rd55, %r62, 4;
	add.s64 	%rd56, %rd1, %rd55;
	mul.f32 	%f104, %f16, %f164;
	ld.global.nc.f32 	%f105, [%rd56];
	mul.f32 	%f106, %f104, %f105;
	sub.f32 	%f107, %f17, %f1;
	sub.f32 	%f108, %f18, %f2;
	sub.f32 	%f109, %f19, %f3;
	fma.rn.f32 	%f175, %f107, %f106, %f175;
	fma.rn.f32 	%f174, %f108, %f106, %f174;
	fma.rn.f32 	%f173, %f109, %f106, %f173;

$L__BB0_17:
	ld.param.u8 	%rs36, [addexchange_param_24];
	and.b16  	%rs3, %rs36, 2;
	setp.eq.s16 	%p20, %rs3, 0;
	setp.lt.s32 	%p21, %r2, 1;
	and.pred  	%p22, %p21, %p20;
	@%p22 bra 	$L__BB0_24;

	ld.param.u64 	%rd109, [addexchange_param_11];
	cvta.to.global.u64 	%rd57, %rd109;
	add.s64 	%rd59, %rd57, %rd34;
	ld.global.nc.f32 	%f110, [%rd59];
	mul.f32 	%f26, %f5, %f110;
	setp.leu.f32 	%p23, %f26, 0f00000000;
	@%p23 bra 	$L__BB0_24;

	add.s32 	%r14, %r2, -1;
	@%p20 bra 	$L__BB0_21;
	bra.uni 	$L__BB0_20;

$L__BB0_21:
	max.s32 	%r107, %r14, 0;
	bra.uni 	$L__BB0_22;

$L__BB0_20:
	rem.s32 	%r63, %r14, %r31;
	add.s32 	%r64, %r63, %r31;
	rem.s32 	%r107, %r64, %r31;

$L__BB0_22:
	add.s32 	%r65, %r107, %r4;
	mad.lo.s32 	%r66, %r65, %r30, %r1;
	cvt.s64.s32 	%rd9, %r66;
	mul.wide.s32 	%rd60, %r66, 4;
	add.s64 	%rd61, %rd5, %rd60;
	add.s64 	%rd62, %rd4, %rd60;
	add.s64 	%rd63, %rd3, %rd60;
	ld.global.nc.f32 	%f27, [%rd61];
	ld.global.nc.f32 	%f28, [%rd62];
	mul.f32 	%f111, %f28, %f28;
	fma.rn.f32 	%f112, %f27, %f27, %f111;
	ld.global.nc.f32 	%f29, [%rd63];
	fma.rn.f32 	%f113, %f29, %f29, %f112;
	setp.eq.f32 	%p25, %f113, 0f00000000;
	@%p25 bra 	$L__BB0_24;

	ld.param.f32 	%f163, [addexchange_param_18];
	add.s64 	%rd64, %rd2, %rd9;
	ld.global.nc.u8 	%rs16, [%rd64];
	min.u16 	%rs19, %rs16, %rs1;
	max.u16 	%rs20, %rs16, %rs1;
	cvt.u32.u16 	%r67, %rs20;
	add.s32 	%r68, %r67, 1;
	mul.lo.s32 	%r69, %r68, %r67;
	shr.u32 	%r70, %r69, 1;
	cvt.u32.u16 	%r71, %rs19;
	add.s32 	%r72, %r70, %r71;
	mul.wide.s32 	%rd65, %r72, 4;
	add.s64 	%rd66, %rd1, %rd65;
	mul.f32 	%f114, %f26, %f163;
	ld.global.nc.f32 	%f115, [%rd66];
	mul.f32 	%f116, %f114, %f115;
	sub.f32 	%f117, %f27, %f1;
	sub.f32 	%f118, %f28, %f2;
	sub.f32 	%f119, %f29, %f3;
	fma.rn.f32 	%f175, %f117, %f116, %f175;
	fma.rn.f32 	%f174, %f118, %f116, %f174;
	fma.rn.f32 	%f173, %f119, %f116, %f173;

$L__BB0_24:
	add.s32 	%r18, %r2, 1;
	setp.ge.s32 	%p26, %r18, %r31;
	and.pred  	%p28, %p26, %p20;
	@%p28 bra 	$L__BB0_31;

	ld.param.u64 	%rd108, [addexchange_param_12];
	cvta.to.global.u64 	%rd67, %rd108;
	add.s64 	%rd69, %rd67, %rd34;
	ld.global.nc.f32 	%f120, [%rd69];
	mul.f32 	%f36, %f5, %f120;
	setp.leu.f32 	%p29, %f36, 0f00000000;
	@%p29 bra 	$L__BB0_31;

	@%p20 bra 	$L__BB0_28;
	bra.uni 	$L__BB0_27;

$L__BB0_28:
	add.s32 	%r75, %r31, -1;
	min.s32 	%r108, %r18, %r75;
	bra.uni 	$L__BB0_29;

$L__BB0_27:
	rem.s32 	%r73, %r18, %r31;
	add.s32 	%r74, %r73, %r31;
	rem.s32 	%r108, %r74, %r31;

$L__BB0_29:
	add.s32 	%r76, %r108, %r4;
	mad.lo.s32 	%r77, %r76, %r30, %r1;
	cvt.s64.s32 	%rd10, %r77;
	mul.wide.s32 	%rd70, %r77, 4;
	add.s64 	%rd71, %rd5, %rd70;
	add.s64 	%rd72, %rd4, %rd70;
	add.s64 	%rd73, %rd3, %rd70;
	ld.global.nc.f32 	%f37, [%rd71];
	ld.global.nc.f32 	%f38, [%rd72];
	mul.f32 	%f121, %f38, %f38;
	fma.rn.f32 	%f122, %f37, %f37, %f121;
	ld.global.nc.f32 	%f39, [%rd73];
	fma.rn.f32 	%f123, %f39, %f39, %f122;
	setp.eq.f32 	%p31, %f123, 0f00000000;
	@%p31 bra 	$L__BB0_31;

	ld.param.f32 	%f162, [addexchange_param_18];
	add.s64 	%rd74, %rd2, %rd10;
	ld.global.nc.u8 	%rs21, [%rd74];
	min.u16 	%rs24, %rs21, %rs1;
	max.u16 	%rs25, %rs21, %rs1;
	cvt.u32.u16 	%r78, %rs25;
	add.s32 	%r79, %r78, 1;
	mul.lo.s32 	%r80, %r79, %r78;
	shr.u32 	%r81, %r80, 1;
	cvt.u32.u16 	%r82, %rs24;
	add.s32 	%r83, %r81, %r82;
	mul.wide.s32 	%rd75, %r83, 4;
	add.s64 	%rd76, %rd1, %rd75;
	mul.f32 	%f124, %f36, %f162;
	ld.global.nc.f32 	%f125, [%rd76];
	mul.f32 	%f126, %f124, %f125;
	sub.f32 	%f127, %f37, %f1;
	sub.f32 	%f128, %f38, %f2;
	sub.f32 	%f129, %f39, %f3;
	fma.rn.f32 	%f175, %f127, %f126, %f175;
	fma.rn.f32 	%f174, %f128, %f126, %f174;
	fma.rn.f32 	%f173, %f129, %f126, %f173;

$L__BB0_31:
	setp.eq.s32 	%p32, %r32, 1;
	@%p32 bra 	$L__BB0_46;

	ld.param.u8 	%rs37, [addexchange_param_24];
	setp.lt.s32 	%p33, %r3, 1;
	and.b16  	%rs4, %rs37, 4;
	setp.eq.s16 	%p34, %rs4, 0;
	and.pred  	%p35, %p33, %p34;
	@%p35 bra 	$L__BB0_39;

	ld.param.u64 	%rd112, [addexchange_param_13];
	cvta.to.global.u64 	%rd77, %rd112;
	add.s64 	%rd79, %rd77, %rd34;
	ld.global.nc.f32 	%f130, [%rd79];
	mul.f32 	%f46, %f5, %f130;
	setp.leu.f32 	%p36, %f46, 0f00000000;
	@%p36 bra 	$L__BB0_39;

	add.s32 	%r22, %r3, -1;
	@%p34 bra 	$L__BB0_36;
	bra.uni 	$L__BB0_35;

$L__BB0_36:
	max.s32 	%r109, %r22, 0;
	bra.uni 	$L__BB0_37;

$L__BB0_35:
	rem.s32 	%r84, %r22, %r32;
	add.s32 	%r85, %r84, %r32;
	rem.s32 	%r109, %r85, %r32;

$L__BB0_37:
	mad.lo.s32 	%r86, %r109, %r31, %r2;
	mad.lo.s32 	%r87, %r86, %r30, %r1;
	cvt.s64.s32 	%rd11, %r87;
	mul.wide.s32 	%rd80, %r87, 4;
	add.s64 	%rd81, %rd5, %rd80;
	add.s64 	%rd82, %rd4, %rd80;
	add.s64 	%rd83, %rd3, %rd80;
	ld.global.nc.f32 	%f47, [%rd81];
	ld.global.nc.f32 	%f48, [%rd82];
	mul.f32 	%f131, %f48, %f48;
	fma.rn.f32 	%f132, %f47, %f47, %f131;
	ld.global.nc.f32 	%f49, [%rd83];
	fma.rn.f32 	%f133, %f49, %f49, %f132;
	setp.eq.f32 	%p38, %f133, 0f00000000;
	@%p38 bra 	$L__BB0_39;

	ld.param.f32 	%f167, [addexchange_param_19];
	add.s64 	%rd84, %rd2, %rd11;
	ld.global.nc.u8 	%rs26, [%rd84];
	min.u16 	%rs29, %rs26, %rs1;
	max.u16 	%rs30, %rs26, %rs1;
	cvt.u32.u16 	%r88, %rs30;
	add.s32 	%r89, %r88, 1;
	mul.lo.s32 	%r90, %r89, %r88;
	shr.u32 	%r91, %r90, 1;
	cvt.u32.u16 	%r92, %rs29;
	add.s32 	%r93, %r91, %r92;
	mul.wide.s32 	%rd85, %r93, 4;
	add.s64 	%rd86, %rd1, %rd85;
	mul.f32 	%f134, %f46, %f167;
	ld.global.nc.f32 	%f135, [%rd86];
	mul.f32 	%f136, %f134, %f135;
	sub.f32 	%f137, %f47, %f1;
	sub.f32 	%f138, %f48, %f2;
	sub.f32 	%f139, %f49, %f3;
	fma.rn.f32 	%f175, %f137, %f136, %f175;
	fma.rn.f32 	%f174, %f138, %f136, %f174;
	fma.rn.f32 	%f173, %f139, %f136, %f173;

$L__BB0_39:
	add.s32 	%r26, %r3, 1;
	setp.ge.s32 	%p39, %r26, %r32;
	and.pred  	%p41, %p39, %p34;
	@%p41 bra 	$L__BB0_46;

	ld.param.u64 	%rd113, [addexchange_param_14];
	cvta.to.global.u64 	%rd87, %rd113;
	add.s64 	%rd89, %rd87, %rd34;
	ld.global.nc.f32 	%f140, [%rd89];
	mul.f32 	%f56, %f5, %f140;
	setp.leu.f32 	%p42, %f56, 0f00000000;
	@%p42 bra 	$L__BB0_46;

	@%p34 bra 	$L__BB0_43;
	bra.uni 	$L__BB0_42;

$L__BB0_43:
	add.s32 	%r96, %r32, -1;
	min.s32 	%r110, %r26, %r96;
	bra.uni 	$L__BB0_44;

$L__BB0_42:
	rem.s32 	%r94, %r26, %r32;
	add.s32 	%r95, %r94, %r32;
	rem.s32 	%r110, %r95, %r32;

$L__BB0_44:
	mad.lo.s32 	%r97, %r110, %r31, %r2;
	mad.lo.s32 	%r98, %r97, %r30, %r1;
	cvt.s64.s32 	%rd12, %r98;
	mul.wide.s32 	%rd90, %r98, 4;
	add.s64 	%rd91, %rd5, %rd90;
	add.s64 	%rd92, %rd4, %rd90;
	add.s64 	%rd93, %rd3, %rd90;
	ld.global.nc.f32 	%f57, [%rd91];
	ld.global.nc.f32 	%f58, [%rd92];
	mul.f32 	%f141, %f58, %f58;
	fma.rn.f32 	%f142, %f57, %f57, %f141;
	ld.global.nc.f32 	%f59, [%rd93];
	fma.rn.f32 	%f143, %f59, %f59, %f142;
	setp.eq.f32 	%p44, %f143, 0f00000000;
	@%p44 bra 	$L__BB0_46;

	ld.param.f32 	%f166, [addexchange_param_19];
	add.s64 	%rd94, %rd2, %rd12;
	ld.global.nc.u8 	%rs31, [%rd94];
	min.u16 	%rs34, %rs31, %rs1;
	max.u16 	%rs35, %rs31, %rs1;
	cvt.u32.u16 	%r99, %rs35;
	add.s32 	%r100, %r99, 1;
	mul.lo.s32 	%r101, %r100, %r99;
	shr.u32 	%r102, %r101, 1;
	cvt.u32.u16 	%r103, %rs34;
	add.s32 	%r104, %r102, %r103;
	mul.wide.s32 	%rd95, %r104, 4;
	add.s64 	%rd96, %rd1, %rd95;
	mul.f32 	%f144, %f56, %f166;
	ld.global.nc.f32 	%f145, [%rd96];
	mul.f32 	%f146, %f144, %f145;
	sub.f32 	%f147, %f57, %f1;
	sub.f32 	%f148, %f58, %f2;
	sub.f32 	%f149, %f59, %f3;
	fma.rn.f32 	%f175, %f147, %f146, %f175;
	fma.rn.f32 	%f174, %f148, %f146, %f174;
	fma.rn.f32 	%f173, %f149, %f146, %f173;

$L__BB0_46:
	ld.param.f32 	%f188, [addexchange_param_7];
	setp.eq.s64 	%p45, %rd16, 0;
	@%p45 bra 	$L__BB0_48;

	ld.param.f32 	%f169, [addexchange_param_7];
	cvta.to.global.u64 	%rd97, %rd16;
	add.s64 	%rd99, %rd97, %rd34;
	ld.global.nc.f32 	%f150, [%rd99];
	mul.f32 	%f188, %f150, %f169;

$L__BB0_48:
	setp.eq.f32 	%p46, %f188, 0f00000000;
	mov.f32 	%f189, 0f00000000;
	@%p46 bra 	$L__BB0_50;

	rcp.rn.f32 	%f189, %f188;

$L__BB0_50:
	cvta.to.global.u64 	%rd100, %rd13;
	add.s64 	%rd102, %rd100, %rd34;
	ld.global.f32 	%f152, [%rd102];
	fma.rn.f32 	%f153, %f175, %f189, %f152;
	st.global.f32 	[%rd102], %f153;
	cvta.to.global.u64 	%rd103, %rd14;
	add.s64 	%rd104, %rd103, %rd34;
	ld.global.f32 	%f154, [%rd104];
	fma.rn.f32 	%f155, %f174, %f189, %f154;
	st.global.f32 	[%rd104], %f155;
	cvta.to.global.u64 	%rd105, %rd15;
	add.s64 	%rd106, %rd105, %rd34;
	ld.global.f32 	%f156, [%rd106];
	fma.rn.f32 	%f157, %f173, %f189, %f156;
	st.global.f32 	[%rd106], %f157;

$L__BB0_51:
	ret;

}

`
	)
