package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for setemergentmagneticfieldsolidangle kernel
var setemergentmagneticfieldsolidangleCode cu.Function

// Stores the arguments for setemergentmagneticfieldsolidangle kernel invocation
type setemergentmagneticfieldsolidangleArgsT struct {
	argFx unsafe.Pointer
	argFy unsafe.Pointer
	argFz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argPrefactor float32
	argIcycz float32
	argIczcx float32
	argIcxcy float32
	argNx int
	argNy int
	argNz int
	argPBC byte
	argptr [14]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for setemergentmagneticfieldsolidangle kernel invocation
var setemergentmagneticfieldsolidangleArgs setemergentmagneticfieldsolidangleArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	setemergentmagneticfieldsolidangleArgs.argptr[0] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argFx)
	setemergentmagneticfieldsolidangleArgs.argptr[1] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argFy)
	setemergentmagneticfieldsolidangleArgs.argptr[2] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argFz)
	setemergentmagneticfieldsolidangleArgs.argptr[3] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argMx)
	setemergentmagneticfieldsolidangleArgs.argptr[4] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argMy)
	setemergentmagneticfieldsolidangleArgs.argptr[5] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argMz)
	setemergentmagneticfieldsolidangleArgs.argptr[6] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argPrefactor)
	setemergentmagneticfieldsolidangleArgs.argptr[7] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argIcycz)
	setemergentmagneticfieldsolidangleArgs.argptr[8] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argIczcx)
	setemergentmagneticfieldsolidangleArgs.argptr[9] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argIcxcy)
	setemergentmagneticfieldsolidangleArgs.argptr[10] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argNx)
	setemergentmagneticfieldsolidangleArgs.argptr[11] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argNy)
	setemergentmagneticfieldsolidangleArgs.argptr[12] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argNz)
	setemergentmagneticfieldsolidangleArgs.argptr[13] = unsafe.Pointer(&setemergentmagneticfieldsolidangleArgs.argPBC)
	}

// Wrapper for setemergentmagneticfieldsolidangle CUDA kernel, asynchronous.
func kSetemergentmagneticfieldsolidangleAsync(Fx unsafe.Pointer, Fy unsafe.Pointer, Fz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, prefactor float32, icycz float32, iczcx float32, icxcy float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("setemergentmagneticfieldsolidangle")
	}

	setemergentmagneticfieldsolidangleArgs.Lock()
	defer setemergentmagneticfieldsolidangleArgs.Unlock()

	if setemergentmagneticfieldsolidangleCode == 0 {
		setemergentmagneticfieldsolidangleCode = fatbinLoad(setemergentmagneticfieldsolidangleMap, "setemergentmagneticfieldsolidangle")
	}

	setemergentmagneticfieldsolidangleArgs.argFx = Fx
	setemergentmagneticfieldsolidangleArgs.argFy = Fy
	setemergentmagneticfieldsolidangleArgs.argFz = Fz
	setemergentmagneticfieldsolidangleArgs.argMx = mx
	setemergentmagneticfieldsolidangleArgs.argMy = my
	setemergentmagneticfieldsolidangleArgs.argMz = mz
	setemergentmagneticfieldsolidangleArgs.argPrefactor = prefactor
	setemergentmagneticfieldsolidangleArgs.argIcycz = icycz
	setemergentmagneticfieldsolidangleArgs.argIczcx = iczcx
	setemergentmagneticfieldsolidangleArgs.argIcxcy = icxcy
	setemergentmagneticfieldsolidangleArgs.argNx = Nx
	setemergentmagneticfieldsolidangleArgs.argNy = Ny
	setemergentmagneticfieldsolidangleArgs.argNz = Nz
	setemergentmagneticfieldsolidangleArgs.argPBC = PBC
	
	args := setemergentmagneticfieldsolidangleArgs.argptr[:]
	cu.LaunchKernel(setemergentmagneticfieldsolidangleCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("setemergentmagneticfieldsolidangle")
	}
}

// maps compute capability on PTX code for setemergentmagneticfieldsolidangle kernel.
var setemergentmagneticfieldsolidangleMap = map[int]string{
	0: "",
	52: setemergentmagneticfieldsolidanglePtx52,
}

// setemergentmagneticfieldsolidangle PTX code for various compute capabilities.
const (
	setemergentmagneticfieldsolidanglePtx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	setemergentmagneticfieldsolidangle

.visible .entry setemergentmagneticfieldsolidangle(
	.param .u64 setemergentmagneticfieldsolidangle_param_0,
	.param .u64 setemergentmagneticfieldsolidangle_param_1,
	.param .u64 setemergentmagneticfieldsolidangle_param_2,
	.param .u64 setemergentmagneticfieldsolidangle_param_3,
	.param .u64 setemergentmagneticfieldsolidangle_param_4,
	.param .u64 setemergentmagneticfieldsolidangle_param_5,
	.param .f32 setemergentmagneticfieldsolidangle_param_6,
	.param .f32 setemergentmagneticfieldsolidangle_param_7,
	.param .f32 setemergentmagneticfieldsolidangle_param_8,
	.param .f32 setemergentmagneticfieldsolidangle_param_9,
	.param .u32 setemergentmagneticfieldsolidangle_param_10,
	.param .u32 setemergentmagneticfieldsolidangle_param_11,
	.param .u32 setemergentmagneticfieldsolidangle_param_12,
	.param .u8 setemergentmagneticfieldsolidangle_param_13
)
{
	.reg .pred 	%p<211>;
	.reg .b16 	%rs<36>;
	.reg .f32 	%f<879>;
	.reg .b32 	%r<467>;
	.reg .b64 	%rd<116>;


	ld.param.u64 	%rd7, [setemergentmagneticfieldsolidangle_param_0];
	ld.param.u64 	%rd8, [setemergentmagneticfieldsolidangle_param_1];
	ld.param.u64 	%rd9, [setemergentmagneticfieldsolidangle_param_2];
	ld.param.u64 	%rd10, [setemergentmagneticfieldsolidangle_param_3];
	ld.param.u64 	%rd11, [setemergentmagneticfieldsolidangle_param_4];
	ld.param.u64 	%rd12, [setemergentmagneticfieldsolidangle_param_5];
	ld.param.u32 	%r149, [setemergentmagneticfieldsolidangle_param_10];
	ld.param.u32 	%r150, [setemergentmagneticfieldsolidangle_param_11];
	ld.param.u32 	%r151, [setemergentmagneticfieldsolidangle_param_12];
	ld.param.u8 	%rs4, [setemergentmagneticfieldsolidangle_param_13];
	cvta.to.global.u64 	%rd1, %rd12;
	cvta.to.global.u64 	%rd2, %rd11;
	cvta.to.global.u64 	%rd3, %rd10;
	mov.u32 	%r152, %ntid.x;
	mov.u32 	%r153, %ctaid.x;
	mov.u32 	%r154, %tid.x;
	mad.lo.s32 	%r1, %r152, %r153, %r154;
	mov.u32 	%r155, %ntid.y;
	mov.u32 	%r156, %ctaid.y;
	mov.u32 	%r157, %tid.y;
	mad.lo.s32 	%r2, %r155, %r156, %r157;
	mov.u32 	%r158, %ntid.z;
	mov.u32 	%r159, %ctaid.z;
	mov.u32 	%r160, %tid.z;
	mad.lo.s32 	%r3, %r158, %r159, %r160;
	setp.ge.s32	%p9, %r2, %r150;
	setp.ge.s32	%p10, %r1, %r149;
	or.pred  	%p11, %p9, %p10;
	setp.ge.s32	%p12, %r3, %r151;
	or.pred  	%p13, %p11, %p12;
	@%p13 bra 	BB0_202;

	cvta.to.global.u64 	%rd13, %rd9;
	cvta.to.global.u64 	%rd14, %rd8;
	cvta.to.global.u64 	%rd15, %rd7;
	mul.lo.s32 	%r4, %r3, %r150;
	add.s32 	%r161, %r4, %r2;
	mul.lo.s32 	%r5, %r161, %r149;
	add.s32 	%r162, %r5, %r1;
	mul.wide.s32 	%rd16, %r162, 4;
	add.s64 	%rd17, %rd3, %rd16;
	add.s64 	%rd18, %rd2, %rd16;
	add.s64 	%rd19, %rd1, %rd16;
	ld.global.nc.f32 	%f1, [%rd17];
	ld.global.nc.f32 	%f2, [%rd18];
	mul.f32 	%f152, %f2, %f2;
	fma.rn.f32 	%f153, %f1, %f1, %f152;
	ld.global.nc.f32 	%f3, [%rd19];
	fma.rn.f32 	%f154, %f3, %f3, %f153;
	setp.eq.f32	%p14, %f154, 0f00000000;
	add.s64 	%rd4, %rd15, %rd16;
	add.s64 	%rd5, %rd14, %rd16;
	add.s64 	%rd6, %rd13, %rd16;
	@%p14 bra 	BB0_201;
	bra.uni 	BB0_2;

BB0_201:
	mov.u32 	%r430, 0;
	st.global.u32 	[%rd4], %r430;
	st.global.u32 	[%rd5], %r430;
	st.global.u32 	[%rd6], %r430;
	bra.uni 	BB0_202;

BB0_2:
	and.b16  	%rs1, %rs4, 2;
	setp.eq.s16	%p15, %rs1, 0;
	add.s32 	%r6, %r2, 1;
	@%p15 bra 	BB0_4;

	rem.s32 	%r163, %r6, %r150;
	add.s32 	%r164, %r163, %r150;
	rem.s32 	%r431, %r164, %r150;
	bra.uni 	BB0_5;

BB0_4:
	add.s32 	%r165, %r150, -1;
	min.s32 	%r431, %r6, %r165;

BB0_5:
	and.b16  	%rs2, %rs4, 4;
	setp.eq.s16	%p16, %rs2, 0;
	add.s32 	%r10, %r3, 1;
	@%p16 bra 	BB0_7;

	rem.s32 	%r166, %r10, %r151;
	add.s32 	%r167, %r166, %r151;
	rem.s32 	%r432, %r167, %r151;
	bra.uni 	BB0_8;

BB0_7:
	add.s32 	%r168, %r151, -1;
	min.s32 	%r432, %r10, %r168;

BB0_8:
	add.s32 	%r14, %r2, -1;
	@%p15 bra 	BB0_10;

	rem.s32 	%r169, %r14, %r150;
	add.s32 	%r170, %r169, %r150;
	rem.s32 	%r433, %r170, %r150;
	bra.uni 	BB0_11;

BB0_10:
	mov.u32 	%r171, 0;
	max.s32 	%r433, %r14, %r171;

BB0_11:
	add.s32 	%r18, %r3, -1;
	@%p16 bra 	BB0_13;

	rem.s32 	%r172, %r18, %r151;
	add.s32 	%r173, %r172, %r151;
	rem.s32 	%r434, %r173, %r151;
	bra.uni 	BB0_14;

BB0_13:
	mov.u32 	%r174, 0;
	max.s32 	%r434, %r18, %r174;

BB0_14:
	add.s32 	%r175, %r431, %r4;
	mad.lo.s32 	%r176, %r175, %r149, %r1;
	mad.lo.s32 	%r177, %r432, %r150, %r2;
	mad.lo.s32 	%r178, %r177, %r149, %r1;
	add.s32 	%r179, %r433, %r4;
	mad.lo.s32 	%r180, %r179, %r149, %r1;
	mad.lo.s32 	%r181, %r434, %r150, %r2;
	mad.lo.s32 	%r182, %r181, %r149, %r1;
	mul.wide.s32 	%rd20, %r176, 4;
	add.s64 	%rd21, %rd3, %rd20;
	ld.global.nc.f32 	%f4, [%rd21];
	add.s64 	%rd22, %rd2, %rd20;
	ld.global.nc.f32 	%f5, [%rd22];
	add.s64 	%rd23, %rd1, %rd20;
	ld.global.nc.f32 	%f6, [%rd23];
	mul.wide.s32 	%rd24, %r178, 4;
	add.s64 	%rd25, %rd3, %rd24;
	ld.global.nc.f32 	%f7, [%rd25];
	add.s64 	%rd26, %rd2, %rd24;
	ld.global.nc.f32 	%f8, [%rd26];
	add.s64 	%rd27, %rd1, %rd24;
	ld.global.nc.f32 	%f9, [%rd27];
	mul.wide.s32 	%rd28, %r180, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.nc.f32 	%f10, [%rd29];
	add.s64 	%rd30, %rd2, %rd28;
	ld.global.nc.f32 	%f11, [%rd30];
	add.s64 	%rd31, %rd1, %rd28;
	ld.global.nc.f32 	%f12, [%rd31];
	mul.wide.s32 	%rd32, %r182, 4;
	add.s64 	%rd33, %rd3, %rd32;
	ld.global.nc.f32 	%f13, [%rd33];
	add.s64 	%rd34, %rd2, %rd32;
	ld.global.nc.f32 	%f14, [%rd34];
	add.s64 	%rd35, %rd1, %rd32;
	ld.global.nc.f32 	%f15, [%rd35];
	setp.ne.s16	%p20, %rs1, 0;
	setp.ge.s32	%p21, %r6, %r150;
	setp.lt.s32	%p22, %r6, %r150;
	or.pred  	%p1, %p22, %p20;
	mov.f32 	%f858, 0f00000000;
	and.pred  	%p23, %p21, %p15;
	@%p23 bra 	BB0_28;

	setp.ge.s32	%p24, %r10, %r151;
	and.pred  	%p26, %p24, %p16;
	@%p26 bra 	BB0_28;

	@%p16 bra 	BB0_18;

	rem.s32 	%r183, %r10, %r151;
	add.s32 	%r184, %r183, %r151;
	rem.s32 	%r435, %r184, %r151;
	bra.uni 	BB0_19;

BB0_18:
	add.s32 	%r185, %r151, -1;
	min.s32 	%r435, %r10, %r185;

BB0_19:
	@%p15 bra 	BB0_21;

	rem.s32 	%r186, %r6, %r150;
	add.s32 	%r187, %r186, %r150;
	rem.s32 	%r436, %r187, %r150;
	bra.uni 	BB0_22;

BB0_21:
	add.s32 	%r188, %r150, -1;
	min.s32 	%r436, %r6, %r188;

BB0_22:
	mad.lo.s32 	%r189, %r435, %r150, %r436;
	mad.lo.s32 	%r190, %r189, %r149, %r1;
	mul.wide.s32 	%rd36, %r190, 4;
	add.s64 	%rd37, %rd3, %rd36;
	add.s64 	%rd38, %rd2, %rd36;
	add.s64 	%rd39, %rd1, %rd36;
	ld.global.nc.f32 	%f157, [%rd37];
	ld.global.nc.f32 	%f158, [%rd38];
	mul.f32 	%f159, %f158, %f158;
	fma.rn.f32 	%f160, %f157, %f157, %f159;
	ld.global.nc.f32 	%f161, [%rd39];
	fma.rn.f32 	%f16, %f161, %f161, %f160;
	mul.f32 	%f162, %f6, %f8;
	mul.f32 	%f163, %f5, %f9;
	sub.f32 	%f164, %f163, %f162;
	mul.f32 	%f165, %f4, %f9;
	mul.f32 	%f166, %f6, %f7;
	sub.f32 	%f167, %f166, %f165;
	mul.f32 	%f168, %f5, %f7;
	mul.f32 	%f169, %f4, %f8;
	sub.f32 	%f170, %f169, %f168;
	mul.f32 	%f171, %f2, %f167;
	fma.rn.f32 	%f172, %f1, %f164, %f171;
	fma.rn.f32 	%f173, %f3, %f170, %f172;
	mul.f32 	%f174, %f2, %f5;
	fma.rn.f32 	%f175, %f1, %f4, %f174;
	fma.rn.f32 	%f176, %f3, %f6, %f175;
	add.f32 	%f177, %f176, 0f3F800000;
	mul.f32 	%f178, %f2, %f8;
	fma.rn.f32 	%f179, %f1, %f7, %f178;
	fma.rn.f32 	%f180, %f3, %f9, %f179;
	add.f32 	%f181, %f177, %f180;
	mul.f32 	%f182, %f5, %f8;
	fma.rn.f32 	%f183, %f4, %f7, %f182;
	fma.rn.f32 	%f184, %f6, %f9, %f183;
	add.f32 	%f185, %f184, %f181;
	abs.f32 	%f17, %f185;
	abs.f32 	%f18, %f173;
	setp.eq.f32	%p29, %f17, 0f00000000;
	setp.eq.f32	%p30, %f18, 0f00000000;
	and.pred  	%p31, %p29, %p30;
	mov.b32 	 %r28, %f185;
	mov.b32 	 %r191, %f173;
	and.b32  	%r29, %r191, -2147483648;
	@%p31 bra 	BB0_26;
	bra.uni 	BB0_23;

BB0_26:
	shr.s32 	%r198, %r28, 31;
	and.b32  	%r199, %r198, 1078530011;
	or.b32  	%r200, %r199, %r29;
	mov.b32 	 %f855, %r200;
	bra.uni 	BB0_27;

BB0_23:
	setp.eq.f32	%p32, %f17, 0f7F800000;
	setp.eq.f32	%p33, %f18, 0f7F800000;
	and.pred  	%p34, %p32, %p33;
	@%p34 bra 	BB0_25;
	bra.uni 	BB0_24;

BB0_25:
	shr.s32 	%r194, %r28, 31;
	and.b32  	%r195, %r194, 13483017;
	add.s32 	%r196, %r195, 1061752795;
	or.b32  	%r197, %r196, %r29;
	mov.b32 	 %f855, %r197;
	bra.uni 	BB0_27;

BB0_24:
	max.f32 	%f186, %f18, %f17;
	min.f32 	%f187, %f18, %f17;
	div.rn.f32 	%f188, %f187, %f186;
	mul.rn.f32 	%f189, %f188, %f188;
	mov.f32 	%f190, 0fC0B59883;
	mov.f32 	%f191, 0fBF52C7EA;
	fma.rn.f32 	%f192, %f189, %f191, %f190;
	mov.f32 	%f193, 0fC0D21907;
	fma.rn.f32 	%f194, %f192, %f189, %f193;
	mul.f32 	%f195, %f189, %f194;
	mul.f32 	%f196, %f188, %f195;
	add.f32 	%f197, %f189, 0f41355DC0;
	mov.f32 	%f198, 0f41E6BD60;
	fma.rn.f32 	%f199, %f197, %f189, %f198;
	mov.f32 	%f200, 0f419D92C8;
	fma.rn.f32 	%f201, %f199, %f189, %f200;
	rcp.rn.f32 	%f202, %f201;
	fma.rn.f32 	%f203, %f196, %f202, %f188;
	mov.f32 	%f204, 0f3FC90FDB;
	sub.f32 	%f205, %f204, %f203;
	setp.gt.f32	%p35, %f18, %f17;
	selp.f32	%f206, %f205, %f203, %p35;
	mov.f32 	%f207, 0f40490FDB;
	sub.f32 	%f208, %f207, %f206;
	setp.lt.s32	%p36, %r28, 0;
	selp.f32	%f209, %f208, %f206, %p36;
	mov.b32 	 %r192, %f209;
	or.b32  	%r193, %r192, %r29;
	mov.b32 	 %f210, %r193;
	add.f32 	%f211, %f17, %f18;
	setp.gtu.f32	%p37, %f211, 0f7F800000;
	selp.f32	%f855, %f211, %f210, %p37;

BB0_27:
	add.f32 	%f212, %f855, %f855;
	setp.eq.f32	%p38, %f16, 0f00000000;
	selp.f32	%f213, 0f3F800000, 0f3F000000, %p38;
	fma.rn.f32 	%f858, %f213, %f212, 0f00000000;

BB0_28:
	setp.lt.s32	%p39, %r14, 0;
	setp.gt.s32	%p40, %r14, -1;
	or.pred  	%p2, %p40, %p20;
	and.pred  	%p43, %p39, %p15;
	@%p43 bra 	BB0_42;

	setp.ge.s32	%p44, %r10, %r151;
	and.pred  	%p46, %p44, %p16;
	@%p46 bra 	BB0_42;

	@%p16 bra 	BB0_32;

	rem.s32 	%r201, %r10, %r151;
	add.s32 	%r202, %r201, %r151;
	rem.s32 	%r437, %r202, %r151;
	bra.uni 	BB0_33;

BB0_32:
	add.s32 	%r203, %r151, -1;
	min.s32 	%r437, %r10, %r203;

BB0_33:
	@%p15 bra 	BB0_35;

	rem.s32 	%r204, %r14, %r150;
	add.s32 	%r205, %r204, %r150;
	rem.s32 	%r438, %r205, %r150;
	bra.uni 	BB0_36;

BB0_35:
	mov.u32 	%r206, 0;
	max.s32 	%r438, %r14, %r206;

BB0_36:
	mad.lo.s32 	%r207, %r437, %r150, %r438;
	mad.lo.s32 	%r208, %r207, %r149, %r1;
	mul.wide.s32 	%rd40, %r208, 4;
	add.s64 	%rd41, %rd3, %rd40;
	add.s64 	%rd42, %rd2, %rd40;
	add.s64 	%rd43, %rd1, %rd40;
	ld.global.nc.f32 	%f214, [%rd41];
	ld.global.nc.f32 	%f215, [%rd42];
	mul.f32 	%f216, %f215, %f215;
	fma.rn.f32 	%f217, %f214, %f214, %f216;
	ld.global.nc.f32 	%f218, [%rd43];
	fma.rn.f32 	%f25, %f218, %f218, %f217;
	mul.f32 	%f219, %f9, %f11;
	mul.f32 	%f220, %f8, %f12;
	sub.f32 	%f221, %f220, %f219;
	mul.f32 	%f222, %f7, %f12;
	mul.f32 	%f223, %f9, %f10;
	sub.f32 	%f224, %f223, %f222;
	mul.f32 	%f225, %f8, %f10;
	mul.f32 	%f226, %f7, %f11;
	sub.f32 	%f227, %f226, %f225;
	mul.f32 	%f228, %f2, %f224;
	fma.rn.f32 	%f229, %f1, %f221, %f228;
	fma.rn.f32 	%f230, %f3, %f227, %f229;
	mul.f32 	%f231, %f2, %f8;
	fma.rn.f32 	%f232, %f1, %f7, %f231;
	fma.rn.f32 	%f233, %f3, %f9, %f232;
	add.f32 	%f234, %f233, 0f3F800000;
	mul.f32 	%f235, %f2, %f11;
	fma.rn.f32 	%f236, %f1, %f10, %f235;
	fma.rn.f32 	%f237, %f3, %f12, %f236;
	add.f32 	%f238, %f234, %f237;
	mul.f32 	%f239, %f8, %f11;
	fma.rn.f32 	%f240, %f7, %f10, %f239;
	fma.rn.f32 	%f241, %f9, %f12, %f240;
	add.f32 	%f242, %f241, %f238;
	abs.f32 	%f26, %f242;
	abs.f32 	%f27, %f230;
	setp.eq.f32	%p49, %f26, 0f00000000;
	setp.eq.f32	%p50, %f27, 0f00000000;
	and.pred  	%p51, %p49, %p50;
	mov.b32 	 %r36, %f242;
	mov.b32 	 %r209, %f230;
	and.b32  	%r37, %r209, -2147483648;
	@%p51 bra 	BB0_40;
	bra.uni 	BB0_37;

BB0_40:
	shr.s32 	%r216, %r36, 31;
	and.b32  	%r217, %r216, 1078530011;
	or.b32  	%r218, %r217, %r37;
	mov.b32 	 %f857, %r218;
	bra.uni 	BB0_41;

BB0_37:
	setp.eq.f32	%p52, %f26, 0f7F800000;
	setp.eq.f32	%p53, %f27, 0f7F800000;
	and.pred  	%p54, %p52, %p53;
	@%p54 bra 	BB0_39;
	bra.uni 	BB0_38;

BB0_39:
	shr.s32 	%r212, %r36, 31;
	and.b32  	%r213, %r212, 13483017;
	add.s32 	%r214, %r213, 1061752795;
	or.b32  	%r215, %r214, %r37;
	mov.b32 	 %f857, %r215;
	bra.uni 	BB0_41;

BB0_38:
	max.f32 	%f243, %f27, %f26;
	min.f32 	%f244, %f27, %f26;
	div.rn.f32 	%f245, %f244, %f243;
	mul.rn.f32 	%f246, %f245, %f245;
	mov.f32 	%f247, 0fC0B59883;
	mov.f32 	%f248, 0fBF52C7EA;
	fma.rn.f32 	%f249, %f246, %f248, %f247;
	mov.f32 	%f250, 0fC0D21907;
	fma.rn.f32 	%f251, %f249, %f246, %f250;
	mul.f32 	%f252, %f246, %f251;
	mul.f32 	%f253, %f245, %f252;
	add.f32 	%f254, %f246, 0f41355DC0;
	mov.f32 	%f255, 0f41E6BD60;
	fma.rn.f32 	%f256, %f254, %f246, %f255;
	mov.f32 	%f257, 0f419D92C8;
	fma.rn.f32 	%f258, %f256, %f246, %f257;
	rcp.rn.f32 	%f259, %f258;
	fma.rn.f32 	%f260, %f253, %f259, %f245;
	mov.f32 	%f261, 0f3FC90FDB;
	sub.f32 	%f262, %f261, %f260;
	setp.gt.f32	%p55, %f27, %f26;
	selp.f32	%f263, %f262, %f260, %p55;
	mov.f32 	%f264, 0f40490FDB;
	sub.f32 	%f265, %f264, %f263;
	setp.lt.s32	%p56, %r36, 0;
	selp.f32	%f266, %f265, %f263, %p56;
	mov.b32 	 %r210, %f266;
	or.b32  	%r211, %r210, %r37;
	mov.b32 	 %f267, %r211;
	add.f32 	%f268, %f26, %f27;
	setp.gtu.f32	%p57, %f268, 0f7F800000;
	selp.f32	%f857, %f268, %f267, %p57;

BB0_41:
	add.f32 	%f269, %f857, %f857;
	setp.eq.f32	%p58, %f25, 0f00000000;
	selp.f32	%f270, 0f3F800000, 0f3F000000, %p58;
	fma.rn.f32 	%f858, %f270, %f269, %f858;

BB0_42:
	@!%p2 bra 	BB0_56;
	bra.uni 	BB0_43;

BB0_43:
	setp.lt.s32	%p59, %r18, 0;
	and.pred  	%p61, %p59, %p16;
	@%p61 bra 	BB0_56;

	@%p16 bra 	BB0_46;

	rem.s32 	%r219, %r18, %r151;
	add.s32 	%r220, %r219, %r151;
	rem.s32 	%r439, %r220, %r151;
	bra.uni 	BB0_47;

BB0_46:
	mov.u32 	%r221, 0;
	max.s32 	%r439, %r18, %r221;

BB0_47:
	@%p15 bra 	BB0_49;

	rem.s32 	%r222, %r14, %r150;
	add.s32 	%r223, %r222, %r150;
	rem.s32 	%r440, %r223, %r150;
	bra.uni 	BB0_50;

BB0_49:
	mov.u32 	%r224, 0;
	max.s32 	%r440, %r14, %r224;

BB0_50:
	mad.lo.s32 	%r225, %r439, %r150, %r440;
	mad.lo.s32 	%r226, %r225, %r149, %r1;
	mul.wide.s32 	%rd44, %r226, 4;
	add.s64 	%rd45, %rd3, %rd44;
	add.s64 	%rd46, %rd2, %rd44;
	add.s64 	%rd47, %rd1, %rd44;
	ld.global.nc.f32 	%f271, [%rd45];
	ld.global.nc.f32 	%f272, [%rd46];
	mul.f32 	%f273, %f272, %f272;
	fma.rn.f32 	%f274, %f271, %f271, %f273;
	ld.global.nc.f32 	%f275, [%rd47];
	fma.rn.f32 	%f34, %f275, %f275, %f274;
	mul.f32 	%f276, %f12, %f14;
	mul.f32 	%f277, %f11, %f15;
	sub.f32 	%f278, %f277, %f276;
	mul.f32 	%f279, %f10, %f15;
	mul.f32 	%f280, %f12, %f13;
	sub.f32 	%f281, %f280, %f279;
	mul.f32 	%f282, %f11, %f13;
	mul.f32 	%f283, %f10, %f14;
	sub.f32 	%f284, %f283, %f282;
	mul.f32 	%f285, %f2, %f281;
	fma.rn.f32 	%f286, %f1, %f278, %f285;
	fma.rn.f32 	%f287, %f3, %f284, %f286;
	mul.f32 	%f288, %f2, %f11;
	fma.rn.f32 	%f289, %f1, %f10, %f288;
	fma.rn.f32 	%f290, %f3, %f12, %f289;
	add.f32 	%f291, %f290, 0f3F800000;
	mul.f32 	%f292, %f2, %f14;
	fma.rn.f32 	%f293, %f1, %f13, %f292;
	fma.rn.f32 	%f294, %f3, %f15, %f293;
	add.f32 	%f295, %f291, %f294;
	mul.f32 	%f296, %f11, %f14;
	fma.rn.f32 	%f297, %f10, %f13, %f296;
	fma.rn.f32 	%f298, %f12, %f15, %f297;
	add.f32 	%f299, %f298, %f295;
	abs.f32 	%f35, %f299;
	abs.f32 	%f36, %f287;
	setp.eq.f32	%p64, %f35, 0f00000000;
	setp.eq.f32	%p65, %f36, 0f00000000;
	and.pred  	%p66, %p64, %p65;
	mov.b32 	 %r44, %f299;
	mov.b32 	 %r227, %f287;
	and.b32  	%r45, %r227, -2147483648;
	@%p66 bra 	BB0_54;
	bra.uni 	BB0_51;

BB0_54:
	shr.s32 	%r234, %r44, 31;
	and.b32  	%r235, %r234, 1078530011;
	or.b32  	%r236, %r235, %r45;
	mov.b32 	 %f859, %r236;
	bra.uni 	BB0_55;

BB0_51:
	setp.eq.f32	%p67, %f35, 0f7F800000;
	setp.eq.f32	%p68, %f36, 0f7F800000;
	and.pred  	%p69, %p67, %p68;
	@%p69 bra 	BB0_53;
	bra.uni 	BB0_52;

BB0_53:
	shr.s32 	%r230, %r44, 31;
	and.b32  	%r231, %r230, 13483017;
	add.s32 	%r232, %r231, 1061752795;
	or.b32  	%r233, %r232, %r45;
	mov.b32 	 %f859, %r233;
	bra.uni 	BB0_55;

BB0_52:
	max.f32 	%f300, %f36, %f35;
	min.f32 	%f301, %f36, %f35;
	div.rn.f32 	%f302, %f301, %f300;
	mul.rn.f32 	%f303, %f302, %f302;
	mov.f32 	%f304, 0fC0B59883;
	mov.f32 	%f305, 0fBF52C7EA;
	fma.rn.f32 	%f306, %f303, %f305, %f304;
	mov.f32 	%f307, 0fC0D21907;
	fma.rn.f32 	%f308, %f306, %f303, %f307;
	mul.f32 	%f309, %f303, %f308;
	mul.f32 	%f310, %f302, %f309;
	add.f32 	%f311, %f303, 0f41355DC0;
	mov.f32 	%f312, 0f41E6BD60;
	fma.rn.f32 	%f313, %f311, %f303, %f312;
	mov.f32 	%f314, 0f419D92C8;
	fma.rn.f32 	%f315, %f313, %f303, %f314;
	rcp.rn.f32 	%f316, %f315;
	fma.rn.f32 	%f317, %f310, %f316, %f302;
	mov.f32 	%f318, 0f3FC90FDB;
	sub.f32 	%f319, %f318, %f317;
	setp.gt.f32	%p70, %f36, %f35;
	selp.f32	%f320, %f319, %f317, %p70;
	mov.f32 	%f321, 0f40490FDB;
	sub.f32 	%f322, %f321, %f320;
	setp.lt.s32	%p71, %r44, 0;
	selp.f32	%f323, %f322, %f320, %p71;
	mov.b32 	 %r228, %f323;
	or.b32  	%r229, %r228, %r45;
	mov.b32 	 %f324, %r229;
	add.f32 	%f325, %f35, %f36;
	setp.gtu.f32	%p72, %f325, 0f7F800000;
	selp.f32	%f859, %f325, %f324, %p72;

BB0_55:
	add.f32 	%f326, %f859, %f859;
	setp.eq.f32	%p73, %f34, 0f00000000;
	selp.f32	%f327, 0f3F800000, 0f3F000000, %p73;
	fma.rn.f32 	%f858, %f327, %f326, %f858;

BB0_56:
	@!%p1 bra 	BB0_70;
	bra.uni 	BB0_57;

BB0_57:
	setp.lt.s32	%p74, %r18, 0;
	and.pred  	%p76, %p74, %p16;
	@%p76 bra 	BB0_70;

	@%p16 bra 	BB0_60;

	rem.s32 	%r237, %r18, %r151;
	add.s32 	%r238, %r237, %r151;
	rem.s32 	%r441, %r238, %r151;
	bra.uni 	BB0_61;

BB0_60:
	mov.u32 	%r239, 0;
	max.s32 	%r441, %r18, %r239;

BB0_61:
	@%p15 bra 	BB0_63;

	rem.s32 	%r240, %r6, %r150;
	add.s32 	%r241, %r240, %r150;
	rem.s32 	%r442, %r241, %r150;
	bra.uni 	BB0_64;

BB0_63:
	add.s32 	%r242, %r150, -1;
	min.s32 	%r442, %r6, %r242;

BB0_64:
	mad.lo.s32 	%r243, %r441, %r150, %r442;
	mad.lo.s32 	%r244, %r243, %r149, %r1;
	mul.wide.s32 	%rd48, %r244, 4;
	add.s64 	%rd49, %rd3, %rd48;
	add.s64 	%rd50, %rd2, %rd48;
	add.s64 	%rd51, %rd1, %rd48;
	ld.global.nc.f32 	%f328, [%rd49];
	ld.global.nc.f32 	%f329, [%rd50];
	mul.f32 	%f330, %f329, %f329;
	fma.rn.f32 	%f331, %f328, %f328, %f330;
	ld.global.nc.f32 	%f332, [%rd51];
	fma.rn.f32 	%f43, %f332, %f332, %f331;
	mul.f32 	%f333, %f5, %f15;
	mul.f32 	%f334, %f6, %f14;
	sub.f32 	%f335, %f334, %f333;
	mul.f32 	%f336, %f6, %f13;
	mul.f32 	%f337, %f4, %f15;
	sub.f32 	%f338, %f337, %f336;
	mul.f32 	%f339, %f4, %f14;
	mul.f32 	%f340, %f5, %f13;
	sub.f32 	%f341, %f340, %f339;
	mul.f32 	%f342, %f2, %f338;
	fma.rn.f32 	%f343, %f1, %f335, %f342;
	fma.rn.f32 	%f344, %f3, %f341, %f343;
	mul.f32 	%f345, %f2, %f14;
	fma.rn.f32 	%f346, %f1, %f13, %f345;
	fma.rn.f32 	%f347, %f3, %f15, %f346;
	add.f32 	%f348, %f347, 0f3F800000;
	mul.f32 	%f349, %f2, %f5;
	fma.rn.f32 	%f350, %f1, %f4, %f349;
	fma.rn.f32 	%f351, %f3, %f6, %f350;
	add.f32 	%f352, %f351, %f348;
	mul.f32 	%f353, %f5, %f14;
	fma.rn.f32 	%f354, %f4, %f13, %f353;
	fma.rn.f32 	%f355, %f6, %f15, %f354;
	add.f32 	%f356, %f355, %f352;
	abs.f32 	%f44, %f356;
	abs.f32 	%f45, %f344;
	setp.eq.f32	%p79, %f44, 0f00000000;
	setp.eq.f32	%p80, %f45, 0f00000000;
	and.pred  	%p81, %p79, %p80;
	mov.b32 	 %r52, %f356;
	mov.b32 	 %r245, %f344;
	and.b32  	%r53, %r245, -2147483648;
	@%p81 bra 	BB0_68;
	bra.uni 	BB0_65;

BB0_68:
	shr.s32 	%r252, %r52, 31;
	and.b32  	%r253, %r252, 1078530011;
	or.b32  	%r254, %r253, %r53;
	mov.b32 	 %f861, %r254;
	bra.uni 	BB0_69;

BB0_65:
	setp.eq.f32	%p82, %f44, 0f7F800000;
	setp.eq.f32	%p83, %f45, 0f7F800000;
	and.pred  	%p84, %p82, %p83;
	@%p84 bra 	BB0_67;
	bra.uni 	BB0_66;

BB0_67:
	shr.s32 	%r248, %r52, 31;
	and.b32  	%r249, %r248, 13483017;
	add.s32 	%r250, %r249, 1061752795;
	or.b32  	%r251, %r250, %r53;
	mov.b32 	 %f861, %r251;
	bra.uni 	BB0_69;

BB0_66:
	max.f32 	%f357, %f45, %f44;
	min.f32 	%f358, %f45, %f44;
	div.rn.f32 	%f359, %f358, %f357;
	mul.rn.f32 	%f360, %f359, %f359;
	mov.f32 	%f361, 0fC0B59883;
	mov.f32 	%f362, 0fBF52C7EA;
	fma.rn.f32 	%f363, %f360, %f362, %f361;
	mov.f32 	%f364, 0fC0D21907;
	fma.rn.f32 	%f365, %f363, %f360, %f364;
	mul.f32 	%f366, %f360, %f365;
	mul.f32 	%f367, %f359, %f366;
	add.f32 	%f368, %f360, 0f41355DC0;
	mov.f32 	%f369, 0f41E6BD60;
	fma.rn.f32 	%f370, %f368, %f360, %f369;
	mov.f32 	%f371, 0f419D92C8;
	fma.rn.f32 	%f372, %f370, %f360, %f371;
	rcp.rn.f32 	%f373, %f372;
	fma.rn.f32 	%f374, %f367, %f373, %f359;
	mov.f32 	%f375, 0f3FC90FDB;
	sub.f32 	%f376, %f375, %f374;
	setp.gt.f32	%p85, %f45, %f44;
	selp.f32	%f377, %f376, %f374, %p85;
	mov.f32 	%f378, 0f40490FDB;
	sub.f32 	%f379, %f378, %f377;
	setp.lt.s32	%p86, %r52, 0;
	selp.f32	%f380, %f379, %f377, %p86;
	mov.b32 	 %r246, %f380;
	or.b32  	%r247, %r246, %r53;
	mov.b32 	 %f381, %r247;
	add.f32 	%f382, %f44, %f45;
	setp.gtu.f32	%p87, %f382, 0f7F800000;
	selp.f32	%f861, %f382, %f381, %p87;

BB0_69:
	add.f32 	%f383, %f861, %f861;
	setp.eq.f32	%p88, %f43, 0f00000000;
	selp.f32	%f384, 0f3F800000, 0f3F000000, %p88;
	fma.rn.f32 	%f858, %f384, %f383, %f858;

BB0_70:
	@%p16 bra 	BB0_72;

	rem.s32 	%r255, %r10, %r151;
	add.s32 	%r256, %r255, %r151;
	rem.s32 	%r443, %r256, %r151;
	bra.uni 	BB0_73;

BB0_72:
	add.s32 	%r257, %r151, -1;
	min.s32 	%r443, %r10, %r257;

BB0_73:
	ld.param.u8 	%rs35, [setemergentmagneticfieldsolidangle_param_13];
	and.b16  	%rs3, %rs35, 1;
	setp.eq.s16	%p90, %rs3, 0;
	add.s32 	%r57, %r1, 1;
	@%p90 bra 	BB0_75;

	rem.s32 	%r258, %r57, %r149;
	add.s32 	%r259, %r258, %r149;
	rem.s32 	%r444, %r259, %r149;
	bra.uni 	BB0_76;

BB0_75:
	add.s32 	%r260, %r149, -1;
	min.s32 	%r444, %r57, %r260;

BB0_76:
	@%p16 bra 	BB0_78;

	rem.s32 	%r261, %r18, %r151;
	add.s32 	%r262, %r261, %r151;
	rem.s32 	%r445, %r262, %r151;
	bra.uni 	BB0_79;

BB0_78:
	mov.u32 	%r263, 0;
	max.s32 	%r445, %r18, %r263;

BB0_79:
	add.s32 	%r64, %r1, -1;
	@%p90 bra 	BB0_81;

	rem.s32 	%r264, %r64, %r149;
	add.s32 	%r265, %r264, %r149;
	rem.s32 	%r446, %r265, %r149;
	bra.uni 	BB0_82;

BB0_81:
	mov.u32 	%r266, 0;
	max.s32 	%r446, %r64, %r266;

BB0_82:
	mad.lo.s32 	%r267, %r443, %r150, %r2;
	mad.lo.s32 	%r268, %r267, %r149, %r1;
	add.s32 	%r269, %r444, %r5;
	mad.lo.s32 	%r270, %r445, %r150, %r2;
	mad.lo.s32 	%r271, %r270, %r149, %r1;
	mul.wide.s32 	%rd52, %r268, 4;
	add.s64 	%rd53, %rd3, %rd52;
	ld.global.nc.f32 	%f52, [%rd53];
	add.s64 	%rd54, %rd2, %rd52;
	ld.global.nc.f32 	%f53, [%rd54];
	add.s64 	%rd55, %rd1, %rd52;
	ld.global.nc.f32 	%f54, [%rd55];
	mul.wide.s32 	%rd56, %r269, 4;
	add.s64 	%rd57, %rd3, %rd56;
	ld.global.nc.f32 	%f55, [%rd57];
	add.s64 	%rd58, %rd2, %rd56;
	ld.global.nc.f32 	%f56, [%rd58];
	add.s64 	%rd59, %rd1, %rd56;
	ld.global.nc.f32 	%f57, [%rd59];
	mul.wide.s32 	%rd60, %r271, 4;
	add.s64 	%rd61, %rd3, %rd60;
	ld.global.nc.f32 	%f58, [%rd61];
	add.s64 	%rd62, %rd2, %rd60;
	ld.global.nc.f32 	%f59, [%rd62];
	add.s64 	%rd63, %rd1, %rd60;
	ld.global.nc.f32 	%f60, [%rd63];
	add.s32 	%r272, %r446, %r5;
	mul.wide.s32 	%rd64, %r272, 4;
	add.s64 	%rd65, %rd3, %rd64;
	ld.global.nc.f32 	%f61, [%rd65];
	add.s64 	%rd66, %rd2, %rd64;
	ld.global.nc.f32 	%f62, [%rd66];
	add.s64 	%rd67, %rd1, %rd64;
	ld.global.nc.f32 	%f63, [%rd67];
	setp.ge.s32	%p94, %r10, %r151;
	mov.f32 	%f866, 0f00000000;
	and.pred  	%p95, %p94, %p16;
	@%p95 bra 	BB0_96;

	setp.ge.s32	%p96, %r57, %r149;
	and.pred  	%p98, %p96, %p90;
	@%p98 bra 	BB0_96;

	@%p16 bra 	BB0_86;

	rem.s32 	%r273, %r10, %r151;
	add.s32 	%r274, %r273, %r151;
	rem.s32 	%r447, %r274, %r151;
	bra.uni 	BB0_87;

BB0_86:
	add.s32 	%r275, %r151, -1;
	min.s32 	%r447, %r10, %r275;

BB0_87:
	@%p90 bra 	BB0_89;

	rem.s32 	%r276, %r57, %r149;
	add.s32 	%r277, %r276, %r149;
	rem.s32 	%r448, %r277, %r149;
	bra.uni 	BB0_90;

BB0_89:
	add.s32 	%r278, %r149, -1;
	min.s32 	%r448, %r57, %r278;

BB0_90:
	mad.lo.s32 	%r279, %r447, %r150, %r2;
	mad.lo.s32 	%r280, %r279, %r149, %r448;
	mul.wide.s32 	%rd68, %r280, 4;
	add.s64 	%rd69, %rd3, %rd68;
	add.s64 	%rd70, %rd2, %rd68;
	add.s64 	%rd71, %rd1, %rd68;
	ld.global.nc.f32 	%f387, [%rd69];
	ld.global.nc.f32 	%f388, [%rd70];
	mul.f32 	%f389, %f388, %f388;
	fma.rn.f32 	%f390, %f387, %f387, %f389;
	ld.global.nc.f32 	%f391, [%rd71];
	fma.rn.f32 	%f64, %f391, %f391, %f390;
	mul.f32 	%f392, %f54, %f56;
	mul.f32 	%f393, %f53, %f57;
	sub.f32 	%f394, %f393, %f392;
	mul.f32 	%f395, %f52, %f57;
	mul.f32 	%f396, %f54, %f55;
	sub.f32 	%f397, %f396, %f395;
	mul.f32 	%f398, %f53, %f55;
	mul.f32 	%f399, %f52, %f56;
	sub.f32 	%f400, %f399, %f398;
	mul.f32 	%f401, %f2, %f397;
	fma.rn.f32 	%f402, %f1, %f394, %f401;
	fma.rn.f32 	%f403, %f3, %f400, %f402;
	mul.f32 	%f404, %f2, %f53;
	fma.rn.f32 	%f405, %f1, %f52, %f404;
	fma.rn.f32 	%f406, %f3, %f54, %f405;
	add.f32 	%f407, %f406, 0f3F800000;
	mul.f32 	%f408, %f2, %f56;
	fma.rn.f32 	%f409, %f1, %f55, %f408;
	fma.rn.f32 	%f410, %f3, %f57, %f409;
	add.f32 	%f411, %f407, %f410;
	mul.f32 	%f412, %f53, %f56;
	fma.rn.f32 	%f413, %f52, %f55, %f412;
	fma.rn.f32 	%f414, %f54, %f57, %f413;
	add.f32 	%f415, %f414, %f411;
	abs.f32 	%f65, %f415;
	abs.f32 	%f66, %f403;
	setp.eq.f32	%p101, %f65, 0f00000000;
	setp.eq.f32	%p102, %f66, 0f00000000;
	and.pred  	%p103, %p101, %p102;
	mov.b32 	 %r74, %f415;
	mov.b32 	 %r281, %f403;
	and.b32  	%r75, %r281, -2147483648;
	@%p103 bra 	BB0_94;
	bra.uni 	BB0_91;

BB0_94:
	shr.s32 	%r288, %r74, 31;
	and.b32  	%r289, %r288, 1078530011;
	or.b32  	%r290, %r289, %r75;
	mov.b32 	 %f863, %r290;
	bra.uni 	BB0_95;

BB0_91:
	setp.eq.f32	%p104, %f65, 0f7F800000;
	setp.eq.f32	%p105, %f66, 0f7F800000;
	and.pred  	%p106, %p104, %p105;
	@%p106 bra 	BB0_93;
	bra.uni 	BB0_92;

BB0_93:
	shr.s32 	%r284, %r74, 31;
	and.b32  	%r285, %r284, 13483017;
	add.s32 	%r286, %r285, 1061752795;
	or.b32  	%r287, %r286, %r75;
	mov.b32 	 %f863, %r287;
	bra.uni 	BB0_95;

BB0_92:
	max.f32 	%f416, %f66, %f65;
	min.f32 	%f417, %f66, %f65;
	div.rn.f32 	%f418, %f417, %f416;
	mul.rn.f32 	%f419, %f418, %f418;
	mov.f32 	%f420, 0fC0B59883;
	mov.f32 	%f421, 0fBF52C7EA;
	fma.rn.f32 	%f422, %f419, %f421, %f420;
	mov.f32 	%f423, 0fC0D21907;
	fma.rn.f32 	%f424, %f422, %f419, %f423;
	mul.f32 	%f425, %f419, %f424;
	mul.f32 	%f426, %f418, %f425;
	add.f32 	%f427, %f419, 0f41355DC0;
	mov.f32 	%f428, 0f41E6BD60;
	fma.rn.f32 	%f429, %f427, %f419, %f428;
	mov.f32 	%f430, 0f419D92C8;
	fma.rn.f32 	%f431, %f429, %f419, %f430;
	rcp.rn.f32 	%f432, %f431;
	fma.rn.f32 	%f433, %f426, %f432, %f418;
	mov.f32 	%f434, 0f3FC90FDB;
	sub.f32 	%f435, %f434, %f433;
	setp.gt.f32	%p107, %f66, %f65;
	selp.f32	%f436, %f435, %f433, %p107;
	mov.f32 	%f437, 0f40490FDB;
	sub.f32 	%f438, %f437, %f436;
	setp.lt.s32	%p108, %r74, 0;
	selp.f32	%f439, %f438, %f436, %p108;
	mov.b32 	 %r282, %f439;
	or.b32  	%r283, %r282, %r75;
	mov.b32 	 %f440, %r283;
	add.f32 	%f441, %f65, %f66;
	setp.gtu.f32	%p109, %f441, 0f7F800000;
	selp.f32	%f863, %f441, %f440, %p109;

BB0_95:
	add.f32 	%f442, %f863, %f863;
	setp.eq.f32	%p110, %f64, 0f00000000;
	selp.f32	%f443, 0f3F800000, 0f3F000000, %p110;
	fma.rn.f32 	%f866, %f443, %f442, 0f00000000;

BB0_96:
	setp.lt.s32	%p111, %r18, 0;
	and.pred  	%p113, %p111, %p16;
	@%p113 bra 	BB0_110;

	setp.ge.s32	%p114, %r57, %r149;
	and.pred  	%p116, %p114, %p90;
	@%p116 bra 	BB0_110;

	@%p16 bra 	BB0_100;

	rem.s32 	%r291, %r18, %r151;
	add.s32 	%r292, %r291, %r151;
	rem.s32 	%r449, %r292, %r151;
	bra.uni 	BB0_101;

BB0_100:
	mov.u32 	%r293, 0;
	max.s32 	%r449, %r18, %r293;

BB0_101:
	@%p90 bra 	BB0_103;

	rem.s32 	%r294, %r57, %r149;
	add.s32 	%r295, %r294, %r149;
	rem.s32 	%r450, %r295, %r149;
	bra.uni 	BB0_104;

BB0_103:
	add.s32 	%r296, %r149, -1;
	min.s32 	%r450, %r57, %r296;

BB0_104:
	mad.lo.s32 	%r297, %r449, %r150, %r2;
	mad.lo.s32 	%r298, %r297, %r149, %r450;
	mul.wide.s32 	%rd72, %r298, 4;
	add.s64 	%rd73, %rd3, %rd72;
	add.s64 	%rd74, %rd2, %rd72;
	add.s64 	%rd75, %rd1, %rd72;
	ld.global.nc.f32 	%f444, [%rd73];
	ld.global.nc.f32 	%f445, [%rd74];
	mul.f32 	%f446, %f445, %f445;
	fma.rn.f32 	%f447, %f444, %f444, %f446;
	ld.global.nc.f32 	%f448, [%rd75];
	fma.rn.f32 	%f73, %f448, %f448, %f447;
	mul.f32 	%f449, %f57, %f59;
	mul.f32 	%f450, %f56, %f60;
	sub.f32 	%f451, %f450, %f449;
	mul.f32 	%f452, %f55, %f60;
	mul.f32 	%f453, %f57, %f58;
	sub.f32 	%f454, %f453, %f452;
	mul.f32 	%f455, %f56, %f58;
	mul.f32 	%f456, %f55, %f59;
	sub.f32 	%f457, %f456, %f455;
	mul.f32 	%f458, %f2, %f454;
	fma.rn.f32 	%f459, %f1, %f451, %f458;
	fma.rn.f32 	%f460, %f3, %f457, %f459;
	mul.f32 	%f461, %f2, %f56;
	fma.rn.f32 	%f462, %f1, %f55, %f461;
	fma.rn.f32 	%f463, %f3, %f57, %f462;
	add.f32 	%f464, %f463, 0f3F800000;
	mul.f32 	%f465, %f2, %f59;
	fma.rn.f32 	%f466, %f1, %f58, %f465;
	fma.rn.f32 	%f467, %f3, %f60, %f466;
	add.f32 	%f468, %f464, %f467;
	mul.f32 	%f469, %f56, %f59;
	fma.rn.f32 	%f470, %f55, %f58, %f469;
	fma.rn.f32 	%f471, %f57, %f60, %f470;
	add.f32 	%f472, %f471, %f468;
	abs.f32 	%f74, %f472;
	abs.f32 	%f75, %f460;
	setp.eq.f32	%p119, %f74, 0f00000000;
	setp.eq.f32	%p120, %f75, 0f00000000;
	and.pred  	%p121, %p119, %p120;
	mov.b32 	 %r82, %f472;
	mov.b32 	 %r299, %f460;
	and.b32  	%r83, %r299, -2147483648;
	@%p121 bra 	BB0_108;
	bra.uni 	BB0_105;

BB0_108:
	shr.s32 	%r306, %r82, 31;
	and.b32  	%r307, %r306, 1078530011;
	or.b32  	%r308, %r307, %r83;
	mov.b32 	 %f865, %r308;
	bra.uni 	BB0_109;

BB0_105:
	setp.eq.f32	%p122, %f74, 0f7F800000;
	setp.eq.f32	%p123, %f75, 0f7F800000;
	and.pred  	%p124, %p122, %p123;
	@%p124 bra 	BB0_107;
	bra.uni 	BB0_106;

BB0_107:
	shr.s32 	%r302, %r82, 31;
	and.b32  	%r303, %r302, 13483017;
	add.s32 	%r304, %r303, 1061752795;
	or.b32  	%r305, %r304, %r83;
	mov.b32 	 %f865, %r305;
	bra.uni 	BB0_109;

BB0_106:
	max.f32 	%f473, %f75, %f74;
	min.f32 	%f474, %f75, %f74;
	div.rn.f32 	%f475, %f474, %f473;
	mul.rn.f32 	%f476, %f475, %f475;
	mov.f32 	%f477, 0fC0B59883;
	mov.f32 	%f478, 0fBF52C7EA;
	fma.rn.f32 	%f479, %f476, %f478, %f477;
	mov.f32 	%f480, 0fC0D21907;
	fma.rn.f32 	%f481, %f479, %f476, %f480;
	mul.f32 	%f482, %f476, %f481;
	mul.f32 	%f483, %f475, %f482;
	add.f32 	%f484, %f476, 0f41355DC0;
	mov.f32 	%f485, 0f41E6BD60;
	fma.rn.f32 	%f486, %f484, %f476, %f485;
	mov.f32 	%f487, 0f419D92C8;
	fma.rn.f32 	%f488, %f486, %f476, %f487;
	rcp.rn.f32 	%f489, %f488;
	fma.rn.f32 	%f490, %f483, %f489, %f475;
	mov.f32 	%f491, 0f3FC90FDB;
	sub.f32 	%f492, %f491, %f490;
	setp.gt.f32	%p125, %f75, %f74;
	selp.f32	%f493, %f492, %f490, %p125;
	mov.f32 	%f494, 0f40490FDB;
	sub.f32 	%f495, %f494, %f493;
	setp.lt.s32	%p126, %r82, 0;
	selp.f32	%f496, %f495, %f493, %p126;
	mov.b32 	 %r300, %f496;
	or.b32  	%r301, %r300, %r83;
	mov.b32 	 %f497, %r301;
	add.f32 	%f498, %f74, %f75;
	setp.gtu.f32	%p127, %f498, 0f7F800000;
	selp.f32	%f865, %f498, %f497, %p127;

BB0_109:
	add.f32 	%f499, %f865, %f865;
	setp.eq.f32	%p128, %f73, 0f00000000;
	selp.f32	%f500, 0f3F800000, 0f3F000000, %p128;
	fma.rn.f32 	%f866, %f500, %f499, %f866;

BB0_110:
	setp.lt.s32	%p130, %r64, 0;
	and.pred  	%p3, %p130, %p90;
	not.pred 	%p4, %p2;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_123;

	@%p16 bra 	BB0_113;

	rem.s32 	%r309, %r18, %r151;
	add.s32 	%r310, %r309, %r151;
	rem.s32 	%r451, %r310, %r151;
	bra.uni 	BB0_114;

BB0_113:
	mov.u32 	%r311, 0;
	max.s32 	%r451, %r18, %r311;

BB0_114:
	@%p90 bra 	BB0_116;

	rem.s32 	%r312, %r64, %r149;
	add.s32 	%r313, %r312, %r149;
	rem.s32 	%r452, %r313, %r149;
	bra.uni 	BB0_117;

BB0_116:
	mov.u32 	%r314, 0;
	max.s32 	%r452, %r64, %r314;

BB0_117:
	mad.lo.s32 	%r315, %r451, %r150, %r2;
	mad.lo.s32 	%r316, %r315, %r149, %r452;
	mul.wide.s32 	%rd76, %r316, 4;
	add.s64 	%rd77, %rd3, %rd76;
	add.s64 	%rd78, %rd2, %rd76;
	add.s64 	%rd79, %rd1, %rd76;
	ld.global.nc.f32 	%f501, [%rd77];
	ld.global.nc.f32 	%f502, [%rd78];
	mul.f32 	%f503, %f502, %f502;
	fma.rn.f32 	%f504, %f501, %f501, %f503;
	ld.global.nc.f32 	%f505, [%rd79];
	fma.rn.f32 	%f82, %f505, %f505, %f504;
	mul.f32 	%f506, %f60, %f62;
	mul.f32 	%f507, %f59, %f63;
	sub.f32 	%f508, %f507, %f506;
	mul.f32 	%f509, %f58, %f63;
	mul.f32 	%f510, %f60, %f61;
	sub.f32 	%f511, %f510, %f509;
	mul.f32 	%f512, %f59, %f61;
	mul.f32 	%f513, %f58, %f62;
	sub.f32 	%f514, %f513, %f512;
	mul.f32 	%f515, %f2, %f511;
	fma.rn.f32 	%f516, %f1, %f508, %f515;
	fma.rn.f32 	%f517, %f3, %f514, %f516;
	mul.f32 	%f518, %f2, %f59;
	fma.rn.f32 	%f519, %f1, %f58, %f518;
	fma.rn.f32 	%f520, %f3, %f60, %f519;
	add.f32 	%f521, %f520, 0f3F800000;
	mul.f32 	%f522, %f2, %f62;
	fma.rn.f32 	%f523, %f1, %f61, %f522;
	fma.rn.f32 	%f524, %f3, %f63, %f523;
	add.f32 	%f525, %f521, %f524;
	mul.f32 	%f526, %f59, %f62;
	fma.rn.f32 	%f527, %f58, %f61, %f526;
	fma.rn.f32 	%f528, %f60, %f63, %f527;
	add.f32 	%f529, %f528, %f525;
	abs.f32 	%f83, %f529;
	abs.f32 	%f84, %f517;
	setp.eq.f32	%p133, %f83, 0f00000000;
	setp.eq.f32	%p134, %f84, 0f00000000;
	and.pred  	%p135, %p133, %p134;
	mov.b32 	 %r90, %f529;
	mov.b32 	 %r317, %f517;
	and.b32  	%r91, %r317, -2147483648;
	@%p135 bra 	BB0_121;
	bra.uni 	BB0_118;

BB0_121:
	shr.s32 	%r324, %r90, 31;
	and.b32  	%r325, %r324, 1078530011;
	or.b32  	%r326, %r325, %r91;
	mov.b32 	 %f867, %r326;
	bra.uni 	BB0_122;

BB0_118:
	setp.eq.f32	%p136, %f83, 0f7F800000;
	setp.eq.f32	%p137, %f84, 0f7F800000;
	and.pred  	%p138, %p136, %p137;
	@%p138 bra 	BB0_120;
	bra.uni 	BB0_119;

BB0_120:
	shr.s32 	%r320, %r90, 31;
	and.b32  	%r321, %r320, 13483017;
	add.s32 	%r322, %r321, 1061752795;
	or.b32  	%r323, %r322, %r91;
	mov.b32 	 %f867, %r323;
	bra.uni 	BB0_122;

BB0_119:
	max.f32 	%f530, %f84, %f83;
	min.f32 	%f531, %f84, %f83;
	div.rn.f32 	%f532, %f531, %f530;
	mul.rn.f32 	%f533, %f532, %f532;
	mov.f32 	%f534, 0fC0B59883;
	mov.f32 	%f535, 0fBF52C7EA;
	fma.rn.f32 	%f536, %f533, %f535, %f534;
	mov.f32 	%f537, 0fC0D21907;
	fma.rn.f32 	%f538, %f536, %f533, %f537;
	mul.f32 	%f539, %f533, %f538;
	mul.f32 	%f540, %f532, %f539;
	add.f32 	%f541, %f533, 0f41355DC0;
	mov.f32 	%f542, 0f41E6BD60;
	fma.rn.f32 	%f543, %f541, %f533, %f542;
	mov.f32 	%f544, 0f419D92C8;
	fma.rn.f32 	%f545, %f543, %f533, %f544;
	rcp.rn.f32 	%f546, %f545;
	fma.rn.f32 	%f547, %f540, %f546, %f532;
	mov.f32 	%f548, 0f3FC90FDB;
	sub.f32 	%f549, %f548, %f547;
	setp.gt.f32	%p139, %f84, %f83;
	selp.f32	%f550, %f549, %f547, %p139;
	mov.f32 	%f551, 0f40490FDB;
	sub.f32 	%f552, %f551, %f550;
	setp.lt.s32	%p140, %r90, 0;
	selp.f32	%f553, %f552, %f550, %p140;
	mov.b32 	 %r318, %f553;
	or.b32  	%r319, %r318, %r91;
	mov.b32 	 %f554, %r319;
	add.f32 	%f555, %f83, %f84;
	setp.gtu.f32	%p141, %f555, 0f7F800000;
	selp.f32	%f867, %f555, %f554, %p141;

BB0_122:
	add.f32 	%f556, %f867, %f867;
	setp.eq.f32	%p142, %f82, 0f00000000;
	selp.f32	%f557, 0f3F800000, 0f3F000000, %p142;
	fma.rn.f32 	%f866, %f557, %f556, %f866;

BB0_123:
	setp.ge.s32	%p143, %r57, %r149;
	and.pred  	%p6, %p143, %p90;
	or.pred  	%p7, %p6, %p4;
	@%p7 bra 	BB0_136;

	@%p16 bra 	BB0_126;

	rem.s32 	%r327, %r10, %r151;
	add.s32 	%r328, %r327, %r151;
	rem.s32 	%r453, %r328, %r151;
	bra.uni 	BB0_127;

BB0_126:
	add.s32 	%r329, %r151, -1;
	min.s32 	%r453, %r10, %r329;

BB0_127:
	mad.lo.s32 	%r95, %r453, %r150, %r2;
	@%p90 bra 	BB0_129;

	rem.s32 	%r330, %r64, %r149;
	add.s32 	%r331, %r330, %r149;
	rem.s32 	%r454, %r331, %r149;
	bra.uni 	BB0_130;

BB0_129:
	mov.u32 	%r332, 0;
	max.s32 	%r454, %r64, %r332;

BB0_130:
	mad.lo.s32 	%r333, %r95, %r149, %r454;
	mul.wide.s32 	%rd80, %r333, 4;
	add.s64 	%rd81, %rd3, %rd80;
	add.s64 	%rd82, %rd2, %rd80;
	add.s64 	%rd83, %rd1, %rd80;
	ld.global.nc.f32 	%f558, [%rd81];
	ld.global.nc.f32 	%f559, [%rd82];
	mul.f32 	%f560, %f559, %f559;
	fma.rn.f32 	%f561, %f558, %f558, %f560;
	ld.global.nc.f32 	%f562, [%rd83];
	fma.rn.f32 	%f91, %f562, %f562, %f561;
	mul.f32 	%f563, %f53, %f63;
	mul.f32 	%f564, %f54, %f62;
	sub.f32 	%f565, %f564, %f563;
	mul.f32 	%f566, %f54, %f61;
	mul.f32 	%f567, %f52, %f63;
	sub.f32 	%f568, %f567, %f566;
	mul.f32 	%f569, %f52, %f62;
	mul.f32 	%f570, %f53, %f61;
	sub.f32 	%f571, %f570, %f569;
	mul.f32 	%f572, %f2, %f568;
	fma.rn.f32 	%f573, %f1, %f565, %f572;
	fma.rn.f32 	%f574, %f3, %f571, %f573;
	mul.f32 	%f575, %f2, %f62;
	fma.rn.f32 	%f576, %f1, %f61, %f575;
	fma.rn.f32 	%f577, %f3, %f63, %f576;
	add.f32 	%f578, %f577, 0f3F800000;
	mul.f32 	%f579, %f2, %f53;
	fma.rn.f32 	%f580, %f1, %f52, %f579;
	fma.rn.f32 	%f581, %f3, %f54, %f580;
	add.f32 	%f582, %f581, %f578;
	mul.f32 	%f583, %f53, %f62;
	fma.rn.f32 	%f584, %f52, %f61, %f583;
	fma.rn.f32 	%f585, %f54, %f63, %f584;
	add.f32 	%f586, %f585, %f582;
	abs.f32 	%f92, %f586;
	abs.f32 	%f93, %f574;
	setp.eq.f32	%p147, %f92, 0f00000000;
	setp.eq.f32	%p148, %f93, 0f00000000;
	and.pred  	%p149, %p147, %p148;
	mov.b32 	 %r99, %f586;
	mov.b32 	 %r334, %f574;
	and.b32  	%r100, %r334, -2147483648;
	@%p149 bra 	BB0_134;
	bra.uni 	BB0_131;

BB0_134:
	shr.s32 	%r341, %r99, 31;
	and.b32  	%r342, %r341, 1078530011;
	or.b32  	%r343, %r342, %r100;
	mov.b32 	 %f869, %r343;
	bra.uni 	BB0_135;

BB0_131:
	setp.eq.f32	%p150, %f92, 0f7F800000;
	setp.eq.f32	%p151, %f93, 0f7F800000;
	and.pred  	%p152, %p150, %p151;
	@%p152 bra 	BB0_133;
	bra.uni 	BB0_132;

BB0_133:
	shr.s32 	%r337, %r99, 31;
	and.b32  	%r338, %r337, 13483017;
	add.s32 	%r339, %r338, 1061752795;
	or.b32  	%r340, %r339, %r100;
	mov.b32 	 %f869, %r340;
	bra.uni 	BB0_135;

BB0_132:
	max.f32 	%f587, %f93, %f92;
	min.f32 	%f588, %f93, %f92;
	div.rn.f32 	%f589, %f588, %f587;
	mul.rn.f32 	%f590, %f589, %f589;
	mov.f32 	%f591, 0fC0B59883;
	mov.f32 	%f592, 0fBF52C7EA;
	fma.rn.f32 	%f593, %f590, %f592, %f591;
	mov.f32 	%f594, 0fC0D21907;
	fma.rn.f32 	%f595, %f593, %f590, %f594;
	mul.f32 	%f596, %f590, %f595;
	mul.f32 	%f597, %f589, %f596;
	add.f32 	%f598, %f590, 0f41355DC0;
	mov.f32 	%f599, 0f41E6BD60;
	fma.rn.f32 	%f600, %f598, %f590, %f599;
	mov.f32 	%f601, 0f419D92C8;
	fma.rn.f32 	%f602, %f600, %f590, %f601;
	rcp.rn.f32 	%f603, %f602;
	fma.rn.f32 	%f604, %f597, %f603, %f589;
	mov.f32 	%f605, 0f3FC90FDB;
	sub.f32 	%f606, %f605, %f604;
	setp.gt.f32	%p153, %f93, %f92;
	selp.f32	%f607, %f606, %f604, %p153;
	mov.f32 	%f608, 0f40490FDB;
	sub.f32 	%f609, %f608, %f607;
	setp.lt.s32	%p154, %r99, 0;
	selp.f32	%f610, %f609, %f607, %p154;
	mov.b32 	 %r335, %f610;
	or.b32  	%r336, %r335, %r100;
	mov.b32 	 %f611, %r336;
	add.f32 	%f612, %f92, %f93;
	setp.gtu.f32	%p155, %f612, 0f7F800000;
	selp.f32	%f869, %f612, %f611, %p155;

BB0_135:
	add.f32 	%f613, %f869, %f869;
	setp.eq.f32	%p156, %f91, 0f00000000;
	selp.f32	%f614, 0f3F800000, 0f3F000000, %p156;
	fma.rn.f32 	%f866, %f614, %f613, %f866;

BB0_136:
	@%p90 bra 	BB0_138;

	rem.s32 	%r344, %r57, %r149;
	add.s32 	%r345, %r344, %r149;
	rem.s32 	%r455, %r345, %r149;
	bra.uni 	BB0_139;

BB0_138:
	add.s32 	%r346, %r149, -1;
	min.s32 	%r455, %r57, %r346;

BB0_139:
	@%p15 bra 	BB0_141;

	rem.s32 	%r347, %r6, %r150;
	add.s32 	%r348, %r347, %r150;
	rem.s32 	%r456, %r348, %r150;
	bra.uni 	BB0_142;

BB0_141:
	add.s32 	%r349, %r150, -1;
	min.s32 	%r456, %r6, %r349;

BB0_142:
	@%p90 bra 	BB0_144;

	rem.s32 	%r350, %r64, %r149;
	add.s32 	%r351, %r350, %r149;
	rem.s32 	%r457, %r351, %r149;
	bra.uni 	BB0_145;

BB0_144:
	mov.u32 	%r352, 0;
	max.s32 	%r457, %r64, %r352;

BB0_145:
	add.s32 	%r110, %r455, %r5;
	add.s32 	%r353, %r456, %r4;
	mad.lo.s32 	%r111, %r353, %r149, %r1;
	add.s32 	%r112, %r457, %r5;
	@%p15 bra 	BB0_147;

	rem.s32 	%r354, %r14, %r150;
	add.s32 	%r355, %r354, %r150;
	rem.s32 	%r458, %r355, %r150;
	bra.uni 	BB0_148;

BB0_147:
	mov.u32 	%r356, 0;
	max.s32 	%r458, %r14, %r356;

BB0_148:
	add.s32 	%r357, %r458, %r4;
	mad.lo.s32 	%r358, %r357, %r149, %r1;
	mul.wide.s32 	%rd84, %r110, 4;
	add.s64 	%rd85, %rd3, %rd84;
	ld.global.nc.f32 	%f100, [%rd85];
	add.s64 	%rd86, %rd2, %rd84;
	ld.global.nc.f32 	%f101, [%rd86];
	add.s64 	%rd87, %rd1, %rd84;
	ld.global.nc.f32 	%f102, [%rd87];
	mul.wide.s32 	%rd88, %r111, 4;
	add.s64 	%rd89, %rd3, %rd88;
	ld.global.nc.f32 	%f103, [%rd89];
	add.s64 	%rd90, %rd2, %rd88;
	ld.global.nc.f32 	%f104, [%rd90];
	add.s64 	%rd91, %rd1, %rd88;
	ld.global.nc.f32 	%f105, [%rd91];
	mul.wide.s32 	%rd92, %r112, 4;
	add.s64 	%rd93, %rd3, %rd92;
	ld.global.nc.f32 	%f106, [%rd93];
	add.s64 	%rd94, %rd2, %rd92;
	ld.global.nc.f32 	%f107, [%rd94];
	add.s64 	%rd95, %rd1, %rd92;
	ld.global.nc.f32 	%f108, [%rd95];
	mul.wide.s32 	%rd96, %r358, 4;
	add.s64 	%rd97, %rd3, %rd96;
	ld.global.nc.f32 	%f109, [%rd97];
	add.s64 	%rd98, %rd2, %rd96;
	ld.global.nc.f32 	%f110, [%rd98];
	add.s64 	%rd99, %rd1, %rd96;
	ld.global.nc.f32 	%f111, [%rd99];
	not.pred 	%p8, %p1;
	or.pred  	%p161, %p6, %p8;
	mov.f32 	%f874, 0f00000000;
	@%p161 bra 	BB0_161;

	@%p15 bra 	BB0_151;

	rem.s32 	%r359, %r6, %r150;
	add.s32 	%r360, %r359, %r150;
	rem.s32 	%r459, %r360, %r150;
	bra.uni 	BB0_152;

BB0_151:
	add.s32 	%r361, %r150, -1;
	min.s32 	%r459, %r6, %r361;

BB0_152:
	@%p90 bra 	BB0_154;

	rem.s32 	%r362, %r57, %r149;
	add.s32 	%r363, %r362, %r149;
	rem.s32 	%r460, %r363, %r149;
	bra.uni 	BB0_155;

BB0_154:
	add.s32 	%r364, %r149, -1;
	min.s32 	%r460, %r57, %r364;

BB0_155:
	add.s32 	%r365, %r459, %r4;
	mad.lo.s32 	%r366, %r365, %r149, %r460;
	mul.wide.s32 	%rd100, %r366, 4;
	add.s64 	%rd101, %rd3, %rd100;
	add.s64 	%rd102, %rd2, %rd100;
	add.s64 	%rd103, %rd1, %rd100;
	ld.global.nc.f32 	%f616, [%rd101];
	ld.global.nc.f32 	%f617, [%rd102];
	mul.f32 	%f618, %f617, %f617;
	fma.rn.f32 	%f619, %f616, %f616, %f618;
	ld.global.nc.f32 	%f620, [%rd103];
	fma.rn.f32 	%f112, %f620, %f620, %f619;
	mul.f32 	%f621, %f102, %f104;
	mul.f32 	%f622, %f101, %f105;
	sub.f32 	%f623, %f622, %f621;
	mul.f32 	%f624, %f100, %f105;
	mul.f32 	%f625, %f102, %f103;
	sub.f32 	%f626, %f625, %f624;
	mul.f32 	%f627, %f101, %f103;
	mul.f32 	%f628, %f100, %f104;
	sub.f32 	%f629, %f628, %f627;
	mul.f32 	%f630, %f2, %f626;
	fma.rn.f32 	%f631, %f1, %f623, %f630;
	fma.rn.f32 	%f632, %f3, %f629, %f631;
	mul.f32 	%f633, %f2, %f101;
	fma.rn.f32 	%f634, %f1, %f100, %f633;
	fma.rn.f32 	%f635, %f3, %f102, %f634;
	add.f32 	%f636, %f635, 0f3F800000;
	mul.f32 	%f637, %f2, %f104;
	fma.rn.f32 	%f638, %f1, %f103, %f637;
	fma.rn.f32 	%f639, %f3, %f105, %f638;
	add.f32 	%f640, %f636, %f639;
	mul.f32 	%f641, %f101, %f104;
	fma.rn.f32 	%f642, %f100, %f103, %f641;
	fma.rn.f32 	%f643, %f102, %f105, %f642;
	add.f32 	%f644, %f643, %f640;
	abs.f32 	%f113, %f644;
	abs.f32 	%f114, %f632;
	setp.eq.f32	%p164, %f113, 0f00000000;
	setp.eq.f32	%p165, %f114, 0f00000000;
	and.pred  	%p166, %p164, %p165;
	mov.b32 	 %r122, %f644;
	mov.b32 	 %r367, %f632;
	and.b32  	%r123, %r367, -2147483648;
	@%p166 bra 	BB0_159;
	bra.uni 	BB0_156;

BB0_159:
	shr.s32 	%r374, %r122, 31;
	and.b32  	%r375, %r374, 1078530011;
	or.b32  	%r376, %r375, %r123;
	mov.b32 	 %f871, %r376;
	bra.uni 	BB0_160;

BB0_156:
	setp.eq.f32	%p167, %f113, 0f7F800000;
	setp.eq.f32	%p168, %f114, 0f7F800000;
	and.pred  	%p169, %p167, %p168;
	@%p169 bra 	BB0_158;
	bra.uni 	BB0_157;

BB0_158:
	shr.s32 	%r370, %r122, 31;
	and.b32  	%r371, %r370, 13483017;
	add.s32 	%r372, %r371, 1061752795;
	or.b32  	%r373, %r372, %r123;
	mov.b32 	 %f871, %r373;
	bra.uni 	BB0_160;

BB0_157:
	max.f32 	%f645, %f114, %f113;
	min.f32 	%f646, %f114, %f113;
	div.rn.f32 	%f647, %f646, %f645;
	mul.rn.f32 	%f648, %f647, %f647;
	mov.f32 	%f649, 0fC0B59883;
	mov.f32 	%f650, 0fBF52C7EA;
	fma.rn.f32 	%f651, %f648, %f650, %f649;
	mov.f32 	%f652, 0fC0D21907;
	fma.rn.f32 	%f653, %f651, %f648, %f652;
	mul.f32 	%f654, %f648, %f653;
	mul.f32 	%f655, %f647, %f654;
	add.f32 	%f656, %f648, 0f41355DC0;
	mov.f32 	%f657, 0f41E6BD60;
	fma.rn.f32 	%f658, %f656, %f648, %f657;
	mov.f32 	%f659, 0f419D92C8;
	fma.rn.f32 	%f660, %f658, %f648, %f659;
	rcp.rn.f32 	%f661, %f660;
	fma.rn.f32 	%f662, %f655, %f661, %f647;
	mov.f32 	%f663, 0f3FC90FDB;
	sub.f32 	%f664, %f663, %f662;
	setp.gt.f32	%p170, %f114, %f113;
	selp.f32	%f665, %f664, %f662, %p170;
	mov.f32 	%f666, 0f40490FDB;
	sub.f32 	%f667, %f666, %f665;
	setp.lt.s32	%p171, %r122, 0;
	selp.f32	%f668, %f667, %f665, %p171;
	mov.b32 	 %r368, %f668;
	or.b32  	%r369, %r368, %r123;
	mov.b32 	 %f669, %r369;
	add.f32 	%f670, %f113, %f114;
	setp.gtu.f32	%p172, %f670, 0f7F800000;
	selp.f32	%f871, %f670, %f669, %p172;

BB0_160:
	add.f32 	%f671, %f871, %f871;
	setp.eq.f32	%p173, %f112, 0f00000000;
	selp.f32	%f672, 0f3F800000, 0f3F000000, %p173;
	fma.rn.f32 	%f874, %f672, %f671, 0f00000000;

BB0_161:
	or.pred  	%p174, %p3, %p8;
	@%p174 bra 	BB0_174;

	@%p15 bra 	BB0_164;

	rem.s32 	%r377, %r6, %r150;
	add.s32 	%r378, %r377, %r150;
	rem.s32 	%r461, %r378, %r150;
	bra.uni 	BB0_165;

BB0_164:
	add.s32 	%r379, %r150, -1;
	min.s32 	%r461, %r6, %r379;

BB0_165:
	@%p90 bra 	BB0_167;

	rem.s32 	%r380, %r64, %r149;
	add.s32 	%r381, %r380, %r149;
	rem.s32 	%r462, %r381, %r149;
	bra.uni 	BB0_168;

BB0_167:
	mov.u32 	%r382, 0;
	max.s32 	%r462, %r64, %r382;

BB0_168:
	add.s32 	%r383, %r461, %r4;
	mad.lo.s32 	%r384, %r383, %r149, %r462;
	mul.wide.s32 	%rd104, %r384, 4;
	add.s64 	%rd105, %rd3, %rd104;
	add.s64 	%rd106, %rd2, %rd104;
	add.s64 	%rd107, %rd1, %rd104;
	ld.global.nc.f32 	%f673, [%rd105];
	ld.global.nc.f32 	%f674, [%rd106];
	mul.f32 	%f675, %f674, %f674;
	fma.rn.f32 	%f676, %f673, %f673, %f675;
	ld.global.nc.f32 	%f677, [%rd107];
	fma.rn.f32 	%f121, %f677, %f677, %f676;
	mul.f32 	%f678, %f105, %f107;
	mul.f32 	%f679, %f104, %f108;
	sub.f32 	%f680, %f679, %f678;
	mul.f32 	%f681, %f103, %f108;
	mul.f32 	%f682, %f105, %f106;
	sub.f32 	%f683, %f682, %f681;
	mul.f32 	%f684, %f104, %f106;
	mul.f32 	%f685, %f103, %f107;
	sub.f32 	%f686, %f685, %f684;
	mul.f32 	%f687, %f2, %f683;
	fma.rn.f32 	%f688, %f1, %f680, %f687;
	fma.rn.f32 	%f689, %f3, %f686, %f688;
	mul.f32 	%f690, %f2, %f104;
	fma.rn.f32 	%f691, %f1, %f103, %f690;
	fma.rn.f32 	%f692, %f3, %f105, %f691;
	add.f32 	%f693, %f692, 0f3F800000;
	mul.f32 	%f694, %f2, %f107;
	fma.rn.f32 	%f695, %f1, %f106, %f694;
	fma.rn.f32 	%f696, %f3, %f108, %f695;
	add.f32 	%f697, %f693, %f696;
	mul.f32 	%f698, %f104, %f107;
	fma.rn.f32 	%f699, %f103, %f106, %f698;
	fma.rn.f32 	%f700, %f105, %f108, %f699;
	add.f32 	%f701, %f700, %f697;
	abs.f32 	%f122, %f701;
	abs.f32 	%f123, %f689;
	setp.eq.f32	%p177, %f122, 0f00000000;
	setp.eq.f32	%p178, %f123, 0f00000000;
	and.pred  	%p179, %p177, %p178;
	mov.b32 	 %r130, %f701;
	mov.b32 	 %r385, %f689;
	and.b32  	%r131, %r385, -2147483648;
	@%p179 bra 	BB0_172;
	bra.uni 	BB0_169;

BB0_172:
	shr.s32 	%r392, %r130, 31;
	and.b32  	%r393, %r392, 1078530011;
	or.b32  	%r394, %r393, %r131;
	mov.b32 	 %f873, %r394;
	bra.uni 	BB0_173;

BB0_169:
	setp.eq.f32	%p180, %f122, 0f7F800000;
	setp.eq.f32	%p181, %f123, 0f7F800000;
	and.pred  	%p182, %p180, %p181;
	@%p182 bra 	BB0_171;
	bra.uni 	BB0_170;

BB0_171:
	shr.s32 	%r388, %r130, 31;
	and.b32  	%r389, %r388, 13483017;
	add.s32 	%r390, %r389, 1061752795;
	or.b32  	%r391, %r390, %r131;
	mov.b32 	 %f873, %r391;
	bra.uni 	BB0_173;

BB0_170:
	max.f32 	%f702, %f123, %f122;
	min.f32 	%f703, %f123, %f122;
	div.rn.f32 	%f704, %f703, %f702;
	mul.rn.f32 	%f705, %f704, %f704;
	mov.f32 	%f706, 0fC0B59883;
	mov.f32 	%f707, 0fBF52C7EA;
	fma.rn.f32 	%f708, %f705, %f707, %f706;
	mov.f32 	%f709, 0fC0D21907;
	fma.rn.f32 	%f710, %f708, %f705, %f709;
	mul.f32 	%f711, %f705, %f710;
	mul.f32 	%f712, %f704, %f711;
	add.f32 	%f713, %f705, 0f41355DC0;
	mov.f32 	%f714, 0f41E6BD60;
	fma.rn.f32 	%f715, %f713, %f705, %f714;
	mov.f32 	%f716, 0f419D92C8;
	fma.rn.f32 	%f717, %f715, %f705, %f716;
	rcp.rn.f32 	%f718, %f717;
	fma.rn.f32 	%f719, %f712, %f718, %f704;
	mov.f32 	%f720, 0f3FC90FDB;
	sub.f32 	%f721, %f720, %f719;
	setp.gt.f32	%p183, %f123, %f122;
	selp.f32	%f722, %f721, %f719, %p183;
	mov.f32 	%f723, 0f40490FDB;
	sub.f32 	%f724, %f723, %f722;
	setp.lt.s32	%p184, %r130, 0;
	selp.f32	%f725, %f724, %f722, %p184;
	mov.b32 	 %r386, %f725;
	or.b32  	%r387, %r386, %r131;
	mov.b32 	 %f726, %r387;
	add.f32 	%f727, %f122, %f123;
	setp.gtu.f32	%p185, %f727, 0f7F800000;
	selp.f32	%f873, %f727, %f726, %p185;

BB0_173:
	add.f32 	%f728, %f873, %f873;
	setp.eq.f32	%p186, %f121, 0f00000000;
	selp.f32	%f729, 0f3F800000, 0f3F000000, %p186;
	fma.rn.f32 	%f874, %f729, %f728, %f874;

BB0_174:
	@%p5 bra 	BB0_187;

	@%p15 bra 	BB0_177;

	rem.s32 	%r395, %r14, %r150;
	add.s32 	%r396, %r395, %r150;
	rem.s32 	%r463, %r396, %r150;
	bra.uni 	BB0_178;

BB0_177:
	mov.u32 	%r397, 0;
	max.s32 	%r463, %r14, %r397;

BB0_178:
	@%p90 bra 	BB0_180;

	rem.s32 	%r398, %r64, %r149;
	add.s32 	%r399, %r398, %r149;
	rem.s32 	%r464, %r399, %r149;
	bra.uni 	BB0_181;

BB0_180:
	mov.u32 	%r400, 0;
	max.s32 	%r464, %r64, %r400;

BB0_181:
	add.s32 	%r401, %r463, %r4;
	mad.lo.s32 	%r402, %r401, %r149, %r464;
	mul.wide.s32 	%rd108, %r402, 4;
	add.s64 	%rd109, %rd3, %rd108;
	add.s64 	%rd110, %rd2, %rd108;
	add.s64 	%rd111, %rd1, %rd108;
	ld.global.nc.f32 	%f730, [%rd109];
	ld.global.nc.f32 	%f731, [%rd110];
	mul.f32 	%f732, %f731, %f731;
	fma.rn.f32 	%f733, %f730, %f730, %f732;
	ld.global.nc.f32 	%f734, [%rd111];
	fma.rn.f32 	%f130, %f734, %f734, %f733;
	mul.f32 	%f735, %f108, %f110;
	mul.f32 	%f736, %f107, %f111;
	sub.f32 	%f737, %f736, %f735;
	mul.f32 	%f738, %f106, %f111;
	mul.f32 	%f739, %f108, %f109;
	sub.f32 	%f740, %f739, %f738;
	mul.f32 	%f741, %f107, %f109;
	mul.f32 	%f742, %f106, %f110;
	sub.f32 	%f743, %f742, %f741;
	mul.f32 	%f744, %f2, %f740;
	fma.rn.f32 	%f745, %f1, %f737, %f744;
	fma.rn.f32 	%f746, %f3, %f743, %f745;
	mul.f32 	%f747, %f2, %f107;
	fma.rn.f32 	%f748, %f1, %f106, %f747;
	fma.rn.f32 	%f749, %f3, %f108, %f748;
	add.f32 	%f750, %f749, 0f3F800000;
	mul.f32 	%f751, %f2, %f110;
	fma.rn.f32 	%f752, %f1, %f109, %f751;
	fma.rn.f32 	%f753, %f3, %f111, %f752;
	add.f32 	%f754, %f750, %f753;
	mul.f32 	%f755, %f107, %f110;
	fma.rn.f32 	%f756, %f106, %f109, %f755;
	fma.rn.f32 	%f757, %f108, %f111, %f756;
	add.f32 	%f758, %f757, %f754;
	abs.f32 	%f131, %f758;
	abs.f32 	%f132, %f746;
	setp.eq.f32	%p189, %f131, 0f00000000;
	setp.eq.f32	%p190, %f132, 0f00000000;
	and.pred  	%p191, %p189, %p190;
	mov.b32 	 %r138, %f758;
	mov.b32 	 %r403, %f746;
	and.b32  	%r139, %r403, -2147483648;
	@%p191 bra 	BB0_185;
	bra.uni 	BB0_182;

BB0_185:
	shr.s32 	%r410, %r138, 31;
	and.b32  	%r411, %r410, 1078530011;
	or.b32  	%r412, %r411, %r139;
	mov.b32 	 %f875, %r412;
	bra.uni 	BB0_186;

BB0_182:
	setp.eq.f32	%p192, %f131, 0f7F800000;
	setp.eq.f32	%p193, %f132, 0f7F800000;
	and.pred  	%p194, %p192, %p193;
	@%p194 bra 	BB0_184;
	bra.uni 	BB0_183;

BB0_184:
	shr.s32 	%r406, %r138, 31;
	and.b32  	%r407, %r406, 13483017;
	add.s32 	%r408, %r407, 1061752795;
	or.b32  	%r409, %r408, %r139;
	mov.b32 	 %f875, %r409;
	bra.uni 	BB0_186;

BB0_183:
	max.f32 	%f759, %f132, %f131;
	min.f32 	%f760, %f132, %f131;
	div.rn.f32 	%f761, %f760, %f759;
	mul.rn.f32 	%f762, %f761, %f761;
	mov.f32 	%f763, 0fC0B59883;
	mov.f32 	%f764, 0fBF52C7EA;
	fma.rn.f32 	%f765, %f762, %f764, %f763;
	mov.f32 	%f766, 0fC0D21907;
	fma.rn.f32 	%f767, %f765, %f762, %f766;
	mul.f32 	%f768, %f762, %f767;
	mul.f32 	%f769, %f761, %f768;
	add.f32 	%f770, %f762, 0f41355DC0;
	mov.f32 	%f771, 0f41E6BD60;
	fma.rn.f32 	%f772, %f770, %f762, %f771;
	mov.f32 	%f773, 0f419D92C8;
	fma.rn.f32 	%f774, %f772, %f762, %f773;
	rcp.rn.f32 	%f775, %f774;
	fma.rn.f32 	%f776, %f769, %f775, %f761;
	mov.f32 	%f777, 0f3FC90FDB;
	sub.f32 	%f778, %f777, %f776;
	setp.gt.f32	%p195, %f132, %f131;
	selp.f32	%f779, %f778, %f776, %p195;
	mov.f32 	%f780, 0f40490FDB;
	sub.f32 	%f781, %f780, %f779;
	setp.lt.s32	%p196, %r138, 0;
	selp.f32	%f782, %f781, %f779, %p196;
	mov.b32 	 %r404, %f782;
	or.b32  	%r405, %r404, %r139;
	mov.b32 	 %f783, %r405;
	add.f32 	%f784, %f131, %f132;
	setp.gtu.f32	%p197, %f784, 0f7F800000;
	selp.f32	%f875, %f784, %f783, %p197;

BB0_186:
	add.f32 	%f785, %f875, %f875;
	setp.eq.f32	%p198, %f130, 0f00000000;
	selp.f32	%f786, 0f3F800000, 0f3F000000, %p198;
	fma.rn.f32 	%f874, %f786, %f785, %f874;

BB0_187:
	@%p7 bra 	BB0_200;

	@%p15 bra 	BB0_190;

	rem.s32 	%r413, %r14, %r150;
	add.s32 	%r414, %r413, %r150;
	rem.s32 	%r465, %r414, %r150;
	bra.uni 	BB0_191;

BB0_190:
	mov.u32 	%r415, 0;
	max.s32 	%r465, %r14, %r415;

BB0_191:
	add.s32 	%r143, %r465, %r4;
	@%p90 bra 	BB0_193;

	rem.s32 	%r416, %r57, %r149;
	add.s32 	%r417, %r416, %r149;
	rem.s32 	%r466, %r417, %r149;
	bra.uni 	BB0_194;

BB0_193:
	add.s32 	%r418, %r149, -1;
	min.s32 	%r466, %r57, %r418;

BB0_194:
	mad.lo.s32 	%r419, %r143, %r149, %r466;
	mul.wide.s32 	%rd112, %r419, 4;
	add.s64 	%rd113, %rd3, %rd112;
	add.s64 	%rd114, %rd2, %rd112;
	add.s64 	%rd115, %rd1, %rd112;
	ld.global.nc.f32 	%f787, [%rd113];
	ld.global.nc.f32 	%f788, [%rd114];
	mul.f32 	%f789, %f788, %f788;
	fma.rn.f32 	%f790, %f787, %f787, %f789;
	ld.global.nc.f32 	%f791, [%rd115];
	fma.rn.f32 	%f139, %f791, %f791, %f790;
	mul.f32 	%f792, %f101, %f111;
	mul.f32 	%f793, %f102, %f110;
	sub.f32 	%f794, %f793, %f792;
	mul.f32 	%f795, %f102, %f109;
	mul.f32 	%f796, %f100, %f111;
	sub.f32 	%f797, %f796, %f795;
	mul.f32 	%f798, %f100, %f110;
	mul.f32 	%f799, %f101, %f109;
	sub.f32 	%f800, %f799, %f798;
	mul.f32 	%f801, %f2, %f797;
	fma.rn.f32 	%f802, %f1, %f794, %f801;
	fma.rn.f32 	%f803, %f3, %f800, %f802;
	mul.f32 	%f804, %f2, %f110;
	fma.rn.f32 	%f805, %f1, %f109, %f804;
	fma.rn.f32 	%f806, %f3, %f111, %f805;
	add.f32 	%f807, %f806, 0f3F800000;
	mul.f32 	%f808, %f2, %f101;
	fma.rn.f32 	%f809, %f1, %f100, %f808;
	fma.rn.f32 	%f810, %f3, %f102, %f809;
	add.f32 	%f811, %f810, %f807;
	mul.f32 	%f812, %f101, %f110;
	fma.rn.f32 	%f813, %f100, %f109, %f812;
	fma.rn.f32 	%f814, %f102, %f111, %f813;
	add.f32 	%f815, %f814, %f811;
	abs.f32 	%f140, %f815;
	abs.f32 	%f141, %f803;
	setp.eq.f32	%p201, %f140, 0f00000000;
	setp.eq.f32	%p202, %f141, 0f00000000;
	and.pred  	%p203, %p201, %p202;
	mov.b32 	 %r147, %f815;
	mov.b32 	 %r420, %f803;
	and.b32  	%r148, %r420, -2147483648;
	@%p203 bra 	BB0_198;
	bra.uni 	BB0_195;

BB0_198:
	shr.s32 	%r427, %r147, 31;
	and.b32  	%r428, %r427, 1078530011;
	or.b32  	%r429, %r428, %r148;
	mov.b32 	 %f877, %r429;
	bra.uni 	BB0_199;

BB0_195:
	setp.eq.f32	%p204, %f140, 0f7F800000;
	setp.eq.f32	%p205, %f141, 0f7F800000;
	and.pred  	%p206, %p204, %p205;
	@%p206 bra 	BB0_197;
	bra.uni 	BB0_196;

BB0_197:
	shr.s32 	%r423, %r147, 31;
	and.b32  	%r424, %r423, 13483017;
	add.s32 	%r425, %r424, 1061752795;
	or.b32  	%r426, %r425, %r148;
	mov.b32 	 %f877, %r426;
	bra.uni 	BB0_199;

BB0_196:
	max.f32 	%f816, %f141, %f140;
	min.f32 	%f817, %f141, %f140;
	div.rn.f32 	%f818, %f817, %f816;
	mul.rn.f32 	%f819, %f818, %f818;
	mov.f32 	%f820, 0fC0B59883;
	mov.f32 	%f821, 0fBF52C7EA;
	fma.rn.f32 	%f822, %f819, %f821, %f820;
	mov.f32 	%f823, 0fC0D21907;
	fma.rn.f32 	%f824, %f822, %f819, %f823;
	mul.f32 	%f825, %f819, %f824;
	mul.f32 	%f826, %f818, %f825;
	add.f32 	%f827, %f819, 0f41355DC0;
	mov.f32 	%f828, 0f41E6BD60;
	fma.rn.f32 	%f829, %f827, %f819, %f828;
	mov.f32 	%f830, 0f419D92C8;
	fma.rn.f32 	%f831, %f829, %f819, %f830;
	rcp.rn.f32 	%f832, %f831;
	fma.rn.f32 	%f833, %f826, %f832, %f818;
	mov.f32 	%f834, 0f3FC90FDB;
	sub.f32 	%f835, %f834, %f833;
	setp.gt.f32	%p207, %f141, %f140;
	selp.f32	%f836, %f835, %f833, %p207;
	mov.f32 	%f837, 0f40490FDB;
	sub.f32 	%f838, %f837, %f836;
	setp.lt.s32	%p208, %r147, 0;
	selp.f32	%f839, %f838, %f836, %p208;
	mov.b32 	 %r421, %f839;
	or.b32  	%r422, %r421, %r148;
	mov.b32 	 %f840, %r422;
	add.f32 	%f841, %f140, %f141;
	setp.gtu.f32	%p209, %f841, 0f7F800000;
	selp.f32	%f877, %f841, %f840, %p209;

BB0_199:
	add.f32 	%f842, %f877, %f877;
	setp.eq.f32	%p210, %f139, 0f00000000;
	selp.f32	%f843, 0f3F800000, 0f3F000000, %p210;
	fma.rn.f32 	%f874, %f843, %f842, %f874;

BB0_200:
	ld.param.f32 	%f854, [setemergentmagneticfieldsolidangle_param_9];
	ld.param.f32 	%f853, [setemergentmagneticfieldsolidangle_param_8];
	ld.param.f32 	%f852, [setemergentmagneticfieldsolidangle_param_7];
	ld.param.f32 	%f851, [setemergentmagneticfieldsolidangle_param_6];
	add.f32 	%f844, %f851, %f851;
	mul.f32 	%f845, %f844, %f852;
	mul.f32 	%f846, %f845, %f858;
	st.global.f32 	[%rd4], %f846;
	mul.f32 	%f847, %f844, %f853;
	mul.f32 	%f848, %f847, %f866;
	st.global.f32 	[%rd5], %f848;
	mul.f32 	%f849, %f844, %f854;
	mul.f32 	%f850, %f849, %f874;
	st.global.f32 	[%rd6], %f850;

BB0_202:
	ret;
}


`
	)
