package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for setemergentmagneticfieldfivepoint kernel
var setemergentmagneticfieldfivepointCode cu.Function

// Stores the arguments for setemergentmagneticfieldfivepoint kernel invocation
type setemergentmagneticfieldfivepointArgsT struct {
	argFx unsafe.Pointer
	argFy unsafe.Pointer
	argFz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argPrefactor float32
	argIcycz float32
	argIczcx float32
	argIcxcy float32
	argNx int
	argNy int
	argNz int
	argPBC byte
	argptr [14]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for setemergentmagneticfieldfivepoint kernel invocation
var setemergentmagneticfieldfivepointArgs setemergentmagneticfieldfivepointArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	setemergentmagneticfieldfivepointArgs.argptr[0] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argFx)
	setemergentmagneticfieldfivepointArgs.argptr[1] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argFy)
	setemergentmagneticfieldfivepointArgs.argptr[2] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argFz)
	setemergentmagneticfieldfivepointArgs.argptr[3] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argMx)
	setemergentmagneticfieldfivepointArgs.argptr[4] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argMy)
	setemergentmagneticfieldfivepointArgs.argptr[5] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argMz)
	setemergentmagneticfieldfivepointArgs.argptr[6] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argPrefactor)
	setemergentmagneticfieldfivepointArgs.argptr[7] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argIcycz)
	setemergentmagneticfieldfivepointArgs.argptr[8] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argIczcx)
	setemergentmagneticfieldfivepointArgs.argptr[9] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argIcxcy)
	setemergentmagneticfieldfivepointArgs.argptr[10] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argNx)
	setemergentmagneticfieldfivepointArgs.argptr[11] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argNy)
	setemergentmagneticfieldfivepointArgs.argptr[12] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argNz)
	setemergentmagneticfieldfivepointArgs.argptr[13] = unsafe.Pointer(&setemergentmagneticfieldfivepointArgs.argPBC)
	}

// Wrapper for setemergentmagneticfieldfivepoint CUDA kernel, asynchronous.
func kSetemergentmagneticfieldfivepointAsync(Fx unsafe.Pointer, Fy unsafe.Pointer, Fz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, prefactor float32, icycz float32, iczcx float32, icxcy float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("setemergentmagneticfieldfivepoint")
	}

	setemergentmagneticfieldfivepointArgs.Lock()
	defer setemergentmagneticfieldfivepointArgs.Unlock()

	if setemergentmagneticfieldfivepointCode == 0 {
		setemergentmagneticfieldfivepointCode = fatbinLoad(setemergentmagneticfieldfivepointMap, "setemergentmagneticfieldfivepoint")
	}

	setemergentmagneticfieldfivepointArgs.argFx = Fx
	setemergentmagneticfieldfivepointArgs.argFy = Fy
	setemergentmagneticfieldfivepointArgs.argFz = Fz
	setemergentmagneticfieldfivepointArgs.argMx = mx
	setemergentmagneticfieldfivepointArgs.argMy = my
	setemergentmagneticfieldfivepointArgs.argMz = mz
	setemergentmagneticfieldfivepointArgs.argPrefactor = prefactor
	setemergentmagneticfieldfivepointArgs.argIcycz = icycz
	setemergentmagneticfieldfivepointArgs.argIczcx = iczcx
	setemergentmagneticfieldfivepointArgs.argIcxcy = icxcy
	setemergentmagneticfieldfivepointArgs.argNx = Nx
	setemergentmagneticfieldfivepointArgs.argNy = Ny
	setemergentmagneticfieldfivepointArgs.argNz = Nz
	setemergentmagneticfieldfivepointArgs.argPBC = PBC
	
	args := setemergentmagneticfieldfivepointArgs.argptr[:]
	cu.LaunchKernel(setemergentmagneticfieldfivepointCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("setemergentmagneticfieldfivepoint")
	}
}

// maps compute capability on PTX code for setemergentmagneticfieldfivepoint kernel.
var setemergentmagneticfieldfivepointMap = map[int]string{
	0: "",
	52: setemergentmagneticfieldfivepointPtx52,
}

// setemergentmagneticfieldfivepoint PTX code for various compute capabilities.
const (
	setemergentmagneticfieldfivepointPtx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	setemergentmagneticfieldfivepoint

.visible .entry setemergentmagneticfieldfivepoint(
	.param .u64 setemergentmagneticfieldfivepoint_param_0,
	.param .u64 setemergentmagneticfieldfivepoint_param_1,
	.param .u64 setemergentmagneticfieldfivepoint_param_2,
	.param .u64 setemergentmagneticfieldfivepoint_param_3,
	.param .u64 setemergentmagneticfieldfivepoint_param_4,
	.param .u64 setemergentmagneticfieldfivepoint_param_5,
	.param .f32 setemergentmagneticfieldfivepoint_param_6,
	.param .f32 setemergentmagneticfieldfivepoint_param_7,
	.param .f32 setemergentmagneticfieldfivepoint_param_8,
	.param .f32 setemergentmagneticfieldfivepoint_param_9,
	.param .u32 setemergentmagneticfieldfivepoint_param_10,
	.param .u32 setemergentmagneticfieldfivepoint_param_11,
	.param .u32 setemergentmagneticfieldfivepoint_param_12,
	.param .u8 setemergentmagneticfieldfivepoint_param_13
)
{
	.reg .pred 	%p<112>;
	.reg .b16 	%rs<19>;
	.reg .f32 	%f<420>;
	.reg .b32 	%r<137>;
	.reg .b64 	%rd<68>;


	ld.param.u64 	%rd7, [setemergentmagneticfieldfivepoint_param_0];
	ld.param.u64 	%rd8, [setemergentmagneticfieldfivepoint_param_1];
	ld.param.u64 	%rd9, [setemergentmagneticfieldfivepoint_param_2];
	ld.param.u64 	%rd10, [setemergentmagneticfieldfivepoint_param_3];
	ld.param.u64 	%rd11, [setemergentmagneticfieldfivepoint_param_4];
	ld.param.u64 	%rd12, [setemergentmagneticfieldfivepoint_param_5];
	ld.param.f32 	%f151, [setemergentmagneticfieldfivepoint_param_6];
	ld.param.f32 	%f152, [setemergentmagneticfieldfivepoint_param_7];
	ld.param.f32 	%f153, [setemergentmagneticfieldfivepoint_param_8];
	ld.param.f32 	%f154, [setemergentmagneticfieldfivepoint_param_9];
	ld.param.u32 	%r57, [setemergentmagneticfieldfivepoint_param_10];
	ld.param.u32 	%r58, [setemergentmagneticfieldfivepoint_param_11];
	ld.param.u32 	%r59, [setemergentmagneticfieldfivepoint_param_12];
	ld.param.u8 	%rs4, [setemergentmagneticfieldfivepoint_param_13];
	cvta.to.global.u64 	%rd1, %rd12;
	cvta.to.global.u64 	%rd2, %rd11;
	cvta.to.global.u64 	%rd3, %rd10;
	mov.u32 	%r60, %ntid.x;
	mov.u32 	%r61, %ctaid.x;
	mov.u32 	%r62, %tid.x;
	mad.lo.s32 	%r1, %r60, %r61, %r62;
	mov.u32 	%r63, %ntid.y;
	mov.u32 	%r64, %ctaid.y;
	mov.u32 	%r65, %tid.y;
	mad.lo.s32 	%r2, %r63, %r64, %r65;
	mov.u32 	%r66, %ntid.z;
	mov.u32 	%r67, %ctaid.z;
	mov.u32 	%r68, %tid.z;
	mad.lo.s32 	%r3, %r66, %r67, %r68;
	setp.ge.s32	%p4, %r2, %r58;
	setp.ge.s32	%p5, %r1, %r57;
	or.pred  	%p6, %p4, %p5;
	setp.ge.s32	%p7, %r3, %r59;
	or.pred  	%p8, %p6, %p7;
	@%p8 bra 	BB0_106;

	cvta.to.global.u64 	%rd13, %rd9;
	cvta.to.global.u64 	%rd14, %rd8;
	cvta.to.global.u64 	%rd15, %rd7;
	mul.lo.s32 	%r4, %r3, %r58;
	add.s32 	%r69, %r4, %r2;
	mul.lo.s32 	%r5, %r69, %r57;
	add.s32 	%r70, %r5, %r1;
	mul.wide.s32 	%rd16, %r70, 4;
	add.s64 	%rd17, %rd3, %rd16;
	add.s64 	%rd18, %rd2, %rd16;
	add.s64 	%rd19, %rd1, %rd16;
	ld.global.nc.f32 	%f1, [%rd17];
	ld.global.nc.f32 	%f2, [%rd18];
	mul.f32 	%f155, %f2, %f2;
	fma.rn.f32 	%f156, %f1, %f1, %f155;
	ld.global.nc.f32 	%f3, [%rd19];
	fma.rn.f32 	%f157, %f3, %f3, %f156;
	setp.eq.f32	%p9, %f157, 0f00000000;
	add.s64 	%rd4, %rd15, %rd16;
	add.s64 	%rd5, %rd14, %rd16;
	add.s64 	%rd6, %rd13, %rd16;
	@%p9 bra 	BB0_105;
	bra.uni 	BB0_2;

BB0_105:
	mov.u32 	%r124, 0;
	st.global.u32 	[%rd4], %r124;
	st.global.u32 	[%rd5], %r124;
	st.global.u32 	[%rd6], %r124;
	bra.uni 	BB0_106;

BB0_2:
	and.b16  	%rs1, %rs4, 1;
	setp.eq.s16	%p10, %rs1, 0;
	add.s32 	%r6, %r1, -2;
	@%p10 bra 	BB0_4;

	rem.s32 	%r71, %r6, %r57;
	add.s32 	%r72, %r71, %r57;
	rem.s32 	%r125, %r72, %r57;
	bra.uni 	BB0_5;

BB0_4:
	mov.u32 	%r73, 0;
	max.s32 	%r125, %r6, %r73;

BB0_5:
	setp.lt.s32	%p12, %r6, 0;
	mov.f32 	%f7, 0f00000000;
	and.pred  	%p13, %p12, %p10;
	mov.f32 	%f8, %f7;
	mov.f32 	%f9, %f7;
	@%p13 bra 	BB0_7;

	add.s32 	%r74, %r125, %r5;
	mul.wide.s32 	%rd20, %r74, 4;
	add.s64 	%rd21, %rd3, %rd20;
	ld.global.nc.f32 	%f7, [%rd21];
	add.s64 	%rd22, %rd2, %rd20;
	ld.global.nc.f32 	%f8, [%rd22];
	add.s64 	%rd23, %rd1, %rd20;
	ld.global.nc.f32 	%f9, [%rd23];

BB0_7:
	add.s32 	%r10, %r1, -1;
	@%p10 bra 	BB0_9;

	rem.s32 	%r75, %r10, %r57;
	add.s32 	%r76, %r75, %r57;
	rem.s32 	%r126, %r76, %r57;
	bra.uni 	BB0_10;

BB0_9:
	mov.u32 	%r77, 0;
	max.s32 	%r126, %r10, %r77;

BB0_10:
	setp.lt.s32	%p15, %r10, 0;
	mov.f32 	%f13, 0f00000000;
	and.pred  	%p17, %p15, %p10;
	mov.f32 	%f14, %f13;
	mov.f32 	%f15, %f13;
	@%p17 bra 	BB0_12;

	add.s32 	%r78, %r126, %r5;
	mul.wide.s32 	%rd24, %r78, 4;
	add.s64 	%rd25, %rd3, %rd24;
	ld.global.nc.f32 	%f13, [%rd25];
	add.s64 	%rd26, %rd2, %rd24;
	ld.global.nc.f32 	%f14, [%rd26];
	add.s64 	%rd27, %rd1, %rd24;
	ld.global.nc.f32 	%f15, [%rd27];

BB0_12:
	add.s32 	%r14, %r1, 1;
	@%p10 bra 	BB0_14;

	rem.s32 	%r79, %r14, %r57;
	add.s32 	%r80, %r79, %r57;
	rem.s32 	%r127, %r80, %r57;
	bra.uni 	BB0_15;

BB0_14:
	add.s32 	%r81, %r57, -1;
	min.s32 	%r127, %r14, %r81;

BB0_15:
	setp.ge.s32	%p19, %r14, %r57;
	mov.f32 	%f19, 0f00000000;
	and.pred  	%p21, %p19, %p10;
	mov.f32 	%f20, %f19;
	mov.f32 	%f21, %f19;
	@%p21 bra 	BB0_17;

	add.s32 	%r82, %r127, %r5;
	mul.wide.s32 	%rd28, %r82, 4;
	add.s64 	%rd29, %rd3, %rd28;
	ld.global.nc.f32 	%f19, [%rd29];
	add.s64 	%rd30, %rd2, %rd28;
	ld.global.nc.f32 	%f20, [%rd30];
	add.s64 	%rd31, %rd1, %rd28;
	ld.global.nc.f32 	%f21, [%rd31];

BB0_17:
	add.s32 	%r18, %r1, 2;
	@%p10 bra 	BB0_19;

	rem.s32 	%r83, %r18, %r57;
	add.s32 	%r84, %r83, %r57;
	rem.s32 	%r128, %r84, %r57;
	bra.uni 	BB0_20;

BB0_19:
	add.s32 	%r85, %r57, -1;
	min.s32 	%r128, %r18, %r85;

BB0_20:
	add.s32 	%r22, %r128, %r5;
	setp.ge.s32	%p23, %r18, %r57;
	mov.f32 	%f25, 0f00000000;
	and.pred  	%p25, %p23, %p10;
	mov.f32 	%f26, %f25;
	mov.f32 	%f27, %f25;
	@%p25 bra 	BB0_22;

	mul.wide.s32 	%rd32, %r22, 4;
	add.s64 	%rd33, %rd3, %rd32;
	ld.global.nc.f32 	%f25, [%rd33];
	add.s64 	%rd34, %rd2, %rd32;
	ld.global.nc.f32 	%f26, [%rd34];
	add.s64 	%rd35, %rd1, %rd32;
	ld.global.nc.f32 	%f27, [%rd35];

BB0_22:
	mul.f32 	%f170, %f20, %f20;
	fma.rn.f32 	%f171, %f19, %f19, %f170;
	fma.rn.f32 	%f28, %f21, %f21, %f171;
	setp.neu.f32	%p26, %f28, 0f00000000;
	@%p26 bra 	BB0_24;

	mul.f32 	%f175, %f14, %f14;
	fma.rn.f32 	%f176, %f13, %f13, %f175;
	fma.rn.f32 	%f177, %f15, %f15, %f176;
	setp.eq.f32	%p27, %f177, 0f00000000;
	mov.f32 	%f387, 0f00000000;
	mov.f32 	%f388, %f387;
	mov.f32 	%f389, %f387;
	@%p27 bra 	BB0_36;

BB0_24:
	mul.f32 	%f178, %f8, %f8;
	fma.rn.f32 	%f179, %f7, %f7, %f178;
	fma.rn.f32 	%f29, %f9, %f9, %f179;
	setp.eq.f32	%p28, %f29, 0f00000000;
	mul.f32 	%f180, %f26, %f26;
	fma.rn.f32 	%f181, %f25, %f25, %f180;
	fma.rn.f32 	%f30, %f27, %f27, %f181;
	setp.eq.f32	%p29, %f30, 0f00000000;
	or.pred  	%p30, %p28, %p29;
	and.pred  	%p32, %p30, %p26;
	@!%p32 bra 	BB0_26;
	bra.uni 	BB0_25;

BB0_25:
	mul.f32 	%f182, %f14, %f14;
	fma.rn.f32 	%f183, %f13, %f13, %f182;
	fma.rn.f32 	%f184, %f15, %f15, %f183;
	setp.neu.f32	%p33, %f184, 0f00000000;
	@%p33 bra 	BB0_35;
	bra.uni 	BB0_26;

BB0_35:
	sub.f32 	%f213, %f19, %f13;
	mul.f32 	%f387, %f213, 0f3F000000;
	sub.f32 	%f214, %f20, %f14;
	mul.f32 	%f388, %f214, 0f3F000000;
	sub.f32 	%f215, %f21, %f15;
	mul.f32 	%f389, %f215, 0f3F000000;
	bra.uni 	BB0_36;

BB0_26:
	setp.neu.f32	%p34, %f29, 0f00000000;
	or.pred  	%p35, %p26, %p34;
	@%p35 bra 	BB0_28;
	bra.uni 	BB0_27;

BB0_28:
	mul.f32 	%f185, %f14, %f14;
	fma.rn.f32 	%f186, %f13, %f13, %f185;
	fma.rn.f32 	%f34, %f15, %f15, %f186;
	setp.neu.f32	%p36, %f34, 0f00000000;
	setp.neu.f32	%p37, %f30, 0f00000000;
	or.pred  	%p38, %p36, %p37;
	@%p38 bra 	BB0_30;
	bra.uni 	BB0_29;

BB0_30:
	or.pred  	%p40, %p28, %p26;
	@%p40 bra 	BB0_32;
	bra.uni 	BB0_31;

BB0_32:
	or.pred  	%p43, %p29, %p36;
	@%p43 bra 	BB0_34;
	bra.uni 	BB0_33;

BB0_34:
	sub.f32 	%f204, %f19, %f13;
	sub.f32 	%f205, %f20, %f14;
	sub.f32 	%f206, %f21, %f15;
	sub.f32 	%f207, %f7, %f25;
	mul.f32 	%f208, %f207, 0f3DAAAAAB;
	sub.f32 	%f209, %f8, %f26;
	mul.f32 	%f210, %f209, 0f3DAAAAAB;
	sub.f32 	%f211, %f9, %f27;
	mul.f32 	%f212, %f211, 0f3DAAAAAB;
	fma.rn.f32 	%f387, %f204, 0f3F2AAAAB, %f208;
	fma.rn.f32 	%f388, %f205, 0f3F2AAAAB, %f210;
	fma.rn.f32 	%f389, %f206, 0f3F2AAAAB, %f212;
	bra.uni 	BB0_36;

BB0_27:
	sub.f32 	%f387, %f1, %f13;
	sub.f32 	%f388, %f2, %f14;
	sub.f32 	%f389, %f3, %f15;
	bra.uni 	BB0_36;

BB0_29:
	sub.f32 	%f387, %f19, %f1;
	sub.f32 	%f388, %f20, %f2;
	sub.f32 	%f389, %f21, %f3;
	bra.uni 	BB0_36;

BB0_31:
	mul.f32 	%f187, %f13, 0fC0000000;
	fma.rn.f32 	%f188, %f7, 0f3F000000, %f187;
	add.f32 	%f189, %f14, %f14;
	mul.f32 	%f190, %f8, 0f3F000000;
	sub.f32 	%f191, %f190, %f189;
	add.f32 	%f192, %f15, %f15;
	mul.f32 	%f193, %f9, 0f3F000000;
	sub.f32 	%f194, %f193, %f192;
	fma.rn.f32 	%f387, %f1, 0f3FC00000, %f188;
	fma.rn.f32 	%f388, %f2, 0f3FC00000, %f191;
	fma.rn.f32 	%f389, %f3, 0f3FC00000, %f194;
	bra.uni 	BB0_36;

BB0_33:
	mul.f32 	%f195, %f25, 0fBF000000;
	fma.rn.f32 	%f196, %f19, 0f40000000, %f195;
	mul.f32 	%f197, %f26, 0fBF000000;
	fma.rn.f32 	%f198, %f20, 0f40000000, %f197;
	mul.f32 	%f199, %f27, 0fBF000000;
	fma.rn.f32 	%f200, %f21, 0f40000000, %f199;
	mul.f32 	%f201, %f1, 0f3FC00000;
	sub.f32 	%f387, %f196, %f201;
	mul.f32 	%f202, %f2, 0f3FC00000;
	sub.f32 	%f388, %f198, %f202;
	mul.f32 	%f203, %f3, 0f3FC00000;
	sub.f32 	%f389, %f200, %f203;

BB0_36:
	and.b16  	%rs2, %rs4, 2;
	setp.eq.s16	%p44, %rs2, 0;
	add.s32 	%r23, %r2, -2;
	@%p44 bra 	BB0_38;

	rem.s32 	%r86, %r23, %r58;
	add.s32 	%r87, %r86, %r58;
	rem.s32 	%r129, %r87, %r58;
	bra.uni 	BB0_39;

BB0_38:
	mov.u32 	%r88, 0;
	max.s32 	%r129, %r23, %r88;

BB0_39:
	setp.lt.s32	%p46, %r23, 0;
	mov.f32 	%f56, 0f00000000;
	and.pred  	%p47, %p46, %p44;
	mov.f32 	%f57, %f56;
	mov.f32 	%f58, %f56;
	@%p47 bra 	BB0_41;

	add.s32 	%r89, %r129, %r4;
	mad.lo.s32 	%r90, %r89, %r57, %r1;
	mul.wide.s32 	%rd36, %r90, 4;
	add.s64 	%rd37, %rd3, %rd36;
	ld.global.nc.f32 	%f56, [%rd37];
	add.s64 	%rd38, %rd2, %rd36;
	ld.global.nc.f32 	%f57, [%rd38];
	add.s64 	%rd39, %rd1, %rd36;
	ld.global.nc.f32 	%f58, [%rd39];

BB0_41:
	add.s32 	%r27, %r2, -1;
	@%p44 bra 	BB0_43;

	rem.s32 	%r91, %r27, %r58;
	add.s32 	%r92, %r91, %r58;
	rem.s32 	%r130, %r92, %r58;
	bra.uni 	BB0_44;

BB0_43:
	mov.u32 	%r93, 0;
	max.s32 	%r130, %r27, %r93;

BB0_44:
	setp.lt.s32	%p49, %r27, 0;
	mov.f32 	%f62, 0f00000000;
	and.pred  	%p51, %p49, %p44;
	mov.f32 	%f63, %f62;
	mov.f32 	%f64, %f62;
	@%p51 bra 	BB0_46;

	add.s32 	%r94, %r130, %r4;
	mad.lo.s32 	%r95, %r94, %r57, %r1;
	mul.wide.s32 	%rd40, %r95, 4;
	add.s64 	%rd41, %rd3, %rd40;
	ld.global.nc.f32 	%f62, [%rd41];
	add.s64 	%rd42, %rd2, %rd40;
	ld.global.nc.f32 	%f63, [%rd42];
	add.s64 	%rd43, %rd1, %rd40;
	ld.global.nc.f32 	%f64, [%rd43];

BB0_46:
	add.s32 	%r31, %r2, 1;
	@%p44 bra 	BB0_48;

	rem.s32 	%r96, %r31, %r58;
	add.s32 	%r97, %r96, %r58;
	rem.s32 	%r131, %r97, %r58;
	bra.uni 	BB0_49;

BB0_48:
	add.s32 	%r98, %r58, -1;
	min.s32 	%r131, %r31, %r98;

BB0_49:
	setp.ge.s32	%p53, %r31, %r58;
	mov.f32 	%f68, 0f00000000;
	and.pred  	%p55, %p53, %p44;
	mov.f32 	%f69, %f68;
	mov.f32 	%f70, %f68;
	@%p55 bra 	BB0_51;

	add.s32 	%r99, %r131, %r4;
	mad.lo.s32 	%r100, %r99, %r57, %r1;
	mul.wide.s32 	%rd44, %r100, 4;
	add.s64 	%rd45, %rd3, %rd44;
	ld.global.nc.f32 	%f68, [%rd45];
	add.s64 	%rd46, %rd2, %rd44;
	ld.global.nc.f32 	%f69, [%rd46];
	add.s64 	%rd47, %rd1, %rd44;
	ld.global.nc.f32 	%f70, [%rd47];

BB0_51:
	add.s32 	%r35, %r2, 2;
	@%p44 bra 	BB0_53;

	rem.s32 	%r101, %r35, %r58;
	add.s32 	%r102, %r101, %r58;
	rem.s32 	%r132, %r102, %r58;
	bra.uni 	BB0_54;

BB0_53:
	add.s32 	%r103, %r58, -1;
	min.s32 	%r132, %r35, %r103;

BB0_54:
	add.s32 	%r39, %r132, %r4;
	setp.ge.s32	%p57, %r35, %r58;
	mov.f32 	%f74, 0f00000000;
	and.pred  	%p59, %p57, %p44;
	mov.f32 	%f75, %f74;
	mov.f32 	%f76, %f74;
	@%p59 bra 	BB0_56;

	mad.lo.s32 	%r104, %r39, %r57, %r1;
	mul.wide.s32 	%rd48, %r104, 4;
	add.s64 	%rd49, %rd3, %rd48;
	ld.global.nc.f32 	%f74, [%rd49];
	add.s64 	%rd50, %rd2, %rd48;
	ld.global.nc.f32 	%f75, [%rd50];
	add.s64 	%rd51, %rd1, %rd48;
	ld.global.nc.f32 	%f76, [%rd51];

BB0_56:
	mul.f32 	%f228, %f69, %f69;
	fma.rn.f32 	%f229, %f68, %f68, %f228;
	fma.rn.f32 	%f77, %f70, %f70, %f229;
	setp.neu.f32	%p60, %f77, 0f00000000;
	@%p60 bra 	BB0_58;

	mul.f32 	%f233, %f63, %f63;
	fma.rn.f32 	%f234, %f62, %f62, %f233;
	fma.rn.f32 	%f235, %f64, %f64, %f234;
	setp.eq.f32	%p61, %f235, 0f00000000;
	mov.f32 	%f402, 0f00000000;
	mov.f32 	%f403, %f402;
	mov.f32 	%f404, %f402;
	@%p61 bra 	BB0_70;

BB0_58:
	mul.f32 	%f236, %f57, %f57;
	fma.rn.f32 	%f237, %f56, %f56, %f236;
	fma.rn.f32 	%f78, %f58, %f58, %f237;
	setp.eq.f32	%p62, %f78, 0f00000000;
	mul.f32 	%f238, %f75, %f75;
	fma.rn.f32 	%f239, %f74, %f74, %f238;
	fma.rn.f32 	%f79, %f76, %f76, %f239;
	setp.eq.f32	%p63, %f79, 0f00000000;
	or.pred  	%p64, %p62, %p63;
	and.pred  	%p66, %p64, %p60;
	@!%p66 bra 	BB0_60;
	bra.uni 	BB0_59;

BB0_59:
	mul.f32 	%f240, %f63, %f63;
	fma.rn.f32 	%f241, %f62, %f62, %f240;
	fma.rn.f32 	%f242, %f64, %f64, %f241;
	setp.neu.f32	%p67, %f242, 0f00000000;
	@%p67 bra 	BB0_69;
	bra.uni 	BB0_60;

BB0_69:
	sub.f32 	%f271, %f68, %f62;
	mul.f32 	%f402, %f271, 0f3F000000;
	sub.f32 	%f272, %f69, %f63;
	mul.f32 	%f403, %f272, 0f3F000000;
	sub.f32 	%f273, %f70, %f64;
	mul.f32 	%f404, %f273, 0f3F000000;
	bra.uni 	BB0_70;

BB0_60:
	setp.neu.f32	%p68, %f78, 0f00000000;
	or.pred  	%p69, %p60, %p68;
	@%p69 bra 	BB0_62;
	bra.uni 	BB0_61;

BB0_62:
	mul.f32 	%f243, %f63, %f63;
	fma.rn.f32 	%f244, %f62, %f62, %f243;
	fma.rn.f32 	%f83, %f64, %f64, %f244;
	setp.neu.f32	%p70, %f83, 0f00000000;
	setp.neu.f32	%p71, %f79, 0f00000000;
	or.pred  	%p72, %p70, %p71;
	@%p72 bra 	BB0_64;
	bra.uni 	BB0_63;

BB0_64:
	or.pred  	%p74, %p62, %p60;
	@%p74 bra 	BB0_66;
	bra.uni 	BB0_65;

BB0_66:
	or.pred  	%p77, %p63, %p70;
	@%p77 bra 	BB0_68;
	bra.uni 	BB0_67;

BB0_68:
	sub.f32 	%f262, %f68, %f62;
	sub.f32 	%f263, %f69, %f63;
	sub.f32 	%f264, %f70, %f64;
	sub.f32 	%f265, %f56, %f74;
	mul.f32 	%f266, %f265, 0f3DAAAAAB;
	sub.f32 	%f267, %f57, %f75;
	mul.f32 	%f268, %f267, 0f3DAAAAAB;
	sub.f32 	%f269, %f58, %f76;
	mul.f32 	%f270, %f269, 0f3DAAAAAB;
	fma.rn.f32 	%f402, %f262, 0f3F2AAAAB, %f266;
	fma.rn.f32 	%f403, %f263, 0f3F2AAAAB, %f268;
	fma.rn.f32 	%f404, %f264, 0f3F2AAAAB, %f270;
	bra.uni 	BB0_70;

BB0_61:
	sub.f32 	%f402, %f1, %f62;
	sub.f32 	%f403, %f2, %f63;
	sub.f32 	%f404, %f3, %f64;
	bra.uni 	BB0_70;

BB0_63:
	sub.f32 	%f402, %f68, %f1;
	sub.f32 	%f403, %f69, %f2;
	sub.f32 	%f404, %f70, %f3;
	bra.uni 	BB0_70;

BB0_65:
	mul.f32 	%f245, %f62, 0fC0000000;
	fma.rn.f32 	%f246, %f56, 0f3F000000, %f245;
	add.f32 	%f247, %f63, %f63;
	mul.f32 	%f248, %f57, 0f3F000000;
	sub.f32 	%f249, %f248, %f247;
	add.f32 	%f250, %f64, %f64;
	mul.f32 	%f251, %f58, 0f3F000000;
	sub.f32 	%f252, %f251, %f250;
	fma.rn.f32 	%f402, %f1, 0f3FC00000, %f246;
	fma.rn.f32 	%f403, %f2, 0f3FC00000, %f249;
	fma.rn.f32 	%f404, %f3, 0f3FC00000, %f252;
	bra.uni 	BB0_70;

BB0_67:
	mul.f32 	%f253, %f74, 0fBF000000;
	fma.rn.f32 	%f254, %f68, 0f40000000, %f253;
	mul.f32 	%f255, %f75, 0fBF000000;
	fma.rn.f32 	%f256, %f69, 0f40000000, %f255;
	mul.f32 	%f257, %f76, 0fBF000000;
	fma.rn.f32 	%f258, %f70, 0f40000000, %f257;
	mul.f32 	%f259, %f1, 0f3FC00000;
	sub.f32 	%f402, %f254, %f259;
	mul.f32 	%f260, %f2, 0f3FC00000;
	sub.f32 	%f403, %f256, %f260;
	mul.f32 	%f261, %f3, 0f3FC00000;
	sub.f32 	%f404, %f258, %f261;

BB0_70:
	and.b16  	%rs3, %rs4, 4;
	setp.eq.s16	%p78, %rs3, 0;
	add.s32 	%r40, %r3, -2;
	@%p78 bra 	BB0_72;

	rem.s32 	%r105, %r40, %r59;
	add.s32 	%r106, %r105, %r59;
	rem.s32 	%r133, %r106, %r59;
	bra.uni 	BB0_73;

BB0_72:
	mov.u32 	%r107, 0;
	max.s32 	%r133, %r40, %r107;

BB0_73:
	setp.lt.s32	%p80, %r40, 0;
	mov.f32 	%f105, 0f00000000;
	and.pred  	%p81, %p80, %p78;
	mov.f32 	%f106, %f105;
	mov.f32 	%f107, %f105;
	@%p81 bra 	BB0_75;

	mad.lo.s32 	%r108, %r133, %r58, %r2;
	mad.lo.s32 	%r109, %r108, %r57, %r1;
	mul.wide.s32 	%rd52, %r109, 4;
	add.s64 	%rd53, %rd3, %rd52;
	ld.global.nc.f32 	%f105, [%rd53];
	add.s64 	%rd54, %rd2, %rd52;
	ld.global.nc.f32 	%f106, [%rd54];
	add.s64 	%rd55, %rd1, %rd52;
	ld.global.nc.f32 	%f107, [%rd55];

BB0_75:
	add.s32 	%r44, %r3, -1;
	@%p78 bra 	BB0_77;

	rem.s32 	%r110, %r44, %r59;
	add.s32 	%r111, %r110, %r59;
	rem.s32 	%r134, %r111, %r59;
	bra.uni 	BB0_78;

BB0_77:
	mov.u32 	%r112, 0;
	max.s32 	%r134, %r44, %r112;

BB0_78:
	setp.lt.s32	%p83, %r44, 0;
	mov.f32 	%f111, 0f00000000;
	and.pred  	%p85, %p83, %p78;
	mov.f32 	%f112, %f111;
	mov.f32 	%f113, %f111;
	@%p85 bra 	BB0_80;

	mad.lo.s32 	%r113, %r134, %r58, %r2;
	mad.lo.s32 	%r114, %r113, %r57, %r1;
	mul.wide.s32 	%rd56, %r114, 4;
	add.s64 	%rd57, %rd3, %rd56;
	ld.global.nc.f32 	%f111, [%rd57];
	add.s64 	%rd58, %rd2, %rd56;
	ld.global.nc.f32 	%f112, [%rd58];
	add.s64 	%rd59, %rd1, %rd56;
	ld.global.nc.f32 	%f113, [%rd59];

BB0_80:
	add.s32 	%r48, %r3, 1;
	@%p78 bra 	BB0_82;

	rem.s32 	%r115, %r48, %r59;
	add.s32 	%r116, %r115, %r59;
	rem.s32 	%r135, %r116, %r59;
	bra.uni 	BB0_83;

BB0_82:
	add.s32 	%r117, %r59, -1;
	min.s32 	%r135, %r48, %r117;

BB0_83:
	setp.ge.s32	%p87, %r48, %r59;
	mov.f32 	%f117, 0f00000000;
	and.pred  	%p89, %p87, %p78;
	mov.f32 	%f118, %f117;
	mov.f32 	%f119, %f117;
	@%p89 bra 	BB0_85;

	mad.lo.s32 	%r118, %r135, %r58, %r2;
	mad.lo.s32 	%r119, %r118, %r57, %r1;
	mul.wide.s32 	%rd60, %r119, 4;
	add.s64 	%rd61, %rd3, %rd60;
	ld.global.nc.f32 	%f117, [%rd61];
	add.s64 	%rd62, %rd2, %rd60;
	ld.global.nc.f32 	%f118, [%rd62];
	add.s64 	%rd63, %rd1, %rd60;
	ld.global.nc.f32 	%f119, [%rd63];

BB0_85:
	add.s32 	%r52, %r3, 2;
	@%p78 bra 	BB0_87;

	rem.s32 	%r120, %r52, %r59;
	add.s32 	%r121, %r120, %r59;
	rem.s32 	%r136, %r121, %r59;
	bra.uni 	BB0_88;

BB0_87:
	add.s32 	%r122, %r59, -1;
	min.s32 	%r136, %r52, %r122;

BB0_88:
	mad.lo.s32 	%r123, %r136, %r58, %r2;
	mad.lo.s32 	%r56, %r123, %r57, %r1;
	setp.ge.s32	%p91, %r52, %r59;
	mov.f32 	%f123, 0f00000000;
	and.pred  	%p93, %p91, %p78;
	mov.f32 	%f124, %f123;
	mov.f32 	%f125, %f123;
	@%p93 bra 	BB0_90;

	mul.wide.s32 	%rd64, %r56, 4;
	add.s64 	%rd65, %rd3, %rd64;
	ld.global.nc.f32 	%f123, [%rd65];
	add.s64 	%rd66, %rd2, %rd64;
	ld.global.nc.f32 	%f124, [%rd66];
	add.s64 	%rd67, %rd1, %rd64;
	ld.global.nc.f32 	%f125, [%rd67];

BB0_90:
	mul.f32 	%f286, %f118, %f118;
	fma.rn.f32 	%f287, %f117, %f117, %f286;
	fma.rn.f32 	%f126, %f119, %f119, %f287;
	setp.neu.f32	%p94, %f126, 0f00000000;
	@%p94 bra 	BB0_92;

	mul.f32 	%f291, %f112, %f112;
	fma.rn.f32 	%f292, %f111, %f111, %f291;
	fma.rn.f32 	%f293, %f113, %f113, %f292;
	setp.eq.f32	%p95, %f293, 0f00000000;
	mov.f32 	%f417, 0f00000000;
	mov.f32 	%f418, %f417;
	mov.f32 	%f419, %f417;
	@%p95 bra 	BB0_104;

BB0_92:
	mul.f32 	%f294, %f106, %f106;
	fma.rn.f32 	%f295, %f105, %f105, %f294;
	fma.rn.f32 	%f127, %f107, %f107, %f295;
	setp.eq.f32	%p96, %f127, 0f00000000;
	mul.f32 	%f296, %f124, %f124;
	fma.rn.f32 	%f297, %f123, %f123, %f296;
	fma.rn.f32 	%f128, %f125, %f125, %f297;
	setp.eq.f32	%p97, %f128, 0f00000000;
	or.pred  	%p98, %p96, %p97;
	and.pred  	%p100, %p98, %p94;
	@!%p100 bra 	BB0_94;
	bra.uni 	BB0_93;

BB0_93:
	mul.f32 	%f298, %f112, %f112;
	fma.rn.f32 	%f299, %f111, %f111, %f298;
	fma.rn.f32 	%f300, %f113, %f113, %f299;
	setp.neu.f32	%p101, %f300, 0f00000000;
	@%p101 bra 	BB0_103;
	bra.uni 	BB0_94;

BB0_103:
	sub.f32 	%f329, %f117, %f111;
	mul.f32 	%f417, %f329, 0f3F000000;
	sub.f32 	%f330, %f118, %f112;
	mul.f32 	%f418, %f330, 0f3F000000;
	sub.f32 	%f331, %f119, %f113;
	mul.f32 	%f419, %f331, 0f3F000000;
	bra.uni 	BB0_104;

BB0_94:
	setp.neu.f32	%p102, %f127, 0f00000000;
	or.pred  	%p103, %p94, %p102;
	@%p103 bra 	BB0_96;
	bra.uni 	BB0_95;

BB0_96:
	mul.f32 	%f301, %f112, %f112;
	fma.rn.f32 	%f302, %f111, %f111, %f301;
	fma.rn.f32 	%f132, %f113, %f113, %f302;
	setp.neu.f32	%p104, %f132, 0f00000000;
	setp.neu.f32	%p105, %f128, 0f00000000;
	or.pred  	%p106, %p104, %p105;
	@%p106 bra 	BB0_98;
	bra.uni 	BB0_97;

BB0_98:
	or.pred  	%p108, %p96, %p94;
	@%p108 bra 	BB0_100;
	bra.uni 	BB0_99;

BB0_100:
	or.pred  	%p111, %p97, %p104;
	@%p111 bra 	BB0_102;
	bra.uni 	BB0_101;

BB0_102:
	sub.f32 	%f320, %f117, %f111;
	sub.f32 	%f321, %f118, %f112;
	sub.f32 	%f322, %f119, %f113;
	sub.f32 	%f323, %f105, %f123;
	mul.f32 	%f324, %f323, 0f3DAAAAAB;
	sub.f32 	%f325, %f106, %f124;
	mul.f32 	%f326, %f325, 0f3DAAAAAB;
	sub.f32 	%f327, %f107, %f125;
	mul.f32 	%f328, %f327, 0f3DAAAAAB;
	fma.rn.f32 	%f417, %f320, 0f3F2AAAAB, %f324;
	fma.rn.f32 	%f418, %f321, 0f3F2AAAAB, %f326;
	fma.rn.f32 	%f419, %f322, 0f3F2AAAAB, %f328;
	bra.uni 	BB0_104;

BB0_95:
	sub.f32 	%f417, %f1, %f111;
	sub.f32 	%f418, %f2, %f112;
	sub.f32 	%f419, %f3, %f113;
	bra.uni 	BB0_104;

BB0_97:
	sub.f32 	%f417, %f117, %f1;
	sub.f32 	%f418, %f118, %f2;
	sub.f32 	%f419, %f119, %f3;
	bra.uni 	BB0_104;

BB0_99:
	mul.f32 	%f303, %f111, 0fC0000000;
	fma.rn.f32 	%f304, %f105, 0f3F000000, %f303;
	add.f32 	%f305, %f112, %f112;
	mul.f32 	%f306, %f106, 0f3F000000;
	sub.f32 	%f307, %f306, %f305;
	add.f32 	%f308, %f113, %f113;
	mul.f32 	%f309, %f107, 0f3F000000;
	sub.f32 	%f310, %f309, %f308;
	fma.rn.f32 	%f417, %f1, 0f3FC00000, %f304;
	fma.rn.f32 	%f418, %f2, 0f3FC00000, %f307;
	fma.rn.f32 	%f419, %f3, 0f3FC00000, %f310;
	bra.uni 	BB0_104;

BB0_101:
	mul.f32 	%f311, %f123, 0fBF000000;
	fma.rn.f32 	%f312, %f117, 0f40000000, %f311;
	mul.f32 	%f313, %f124, 0fBF000000;
	fma.rn.f32 	%f314, %f118, 0f40000000, %f313;
	mul.f32 	%f315, %f125, 0fBF000000;
	fma.rn.f32 	%f316, %f119, 0f40000000, %f315;
	mul.f32 	%f317, %f1, 0f3FC00000;
	sub.f32 	%f417, %f312, %f317;
	mul.f32 	%f318, %f2, 0f3FC00000;
	sub.f32 	%f418, %f314, %f318;
	mul.f32 	%f319, %f3, 0f3FC00000;
	sub.f32 	%f419, %f316, %f319;

BB0_104:
	mul.f32 	%f332, %f404, %f418;
	mul.f32 	%f333, %f403, %f419;
	sub.f32 	%f334, %f333, %f332;
	mul.f32 	%f335, %f402, %f419;
	mul.f32 	%f336, %f404, %f417;
	sub.f32 	%f337, %f336, %f335;
	mul.f32 	%f338, %f403, %f417;
	mul.f32 	%f339, %f402, %f418;
	sub.f32 	%f340, %f339, %f338;
	mul.f32 	%f341, %f388, %f419;
	mul.f32 	%f342, %f389, %f418;
	sub.f32 	%f343, %f342, %f341;
	mul.f32 	%f344, %f389, %f417;
	mul.f32 	%f345, %f387, %f419;
	sub.f32 	%f346, %f345, %f344;
	mul.f32 	%f347, %f387, %f418;
	mul.f32 	%f348, %f388, %f417;
	sub.f32 	%f349, %f348, %f347;
	mul.f32 	%f350, %f389, %f403;
	mul.f32 	%f351, %f388, %f404;
	sub.f32 	%f352, %f351, %f350;
	mul.f32 	%f353, %f387, %f404;
	mul.f32 	%f354, %f389, %f402;
	sub.f32 	%f355, %f354, %f353;
	mul.f32 	%f356, %f388, %f402;
	mul.f32 	%f357, %f387, %f403;
	sub.f32 	%f358, %f357, %f356;
	add.f32 	%f359, %f151, %f151;
	mul.f32 	%f360, %f359, %f152;
	mul.f32 	%f361, %f2, %f337;
	fma.rn.f32 	%f362, %f1, %f334, %f361;
	fma.rn.f32 	%f363, %f3, %f340, %f362;
	mul.f32 	%f364, %f360, %f363;
	st.global.f32 	[%rd4], %f364;
	mul.f32 	%f365, %f359, %f153;
	mul.f32 	%f366, %f2, %f346;
	fma.rn.f32 	%f367, %f1, %f343, %f366;
	fma.rn.f32 	%f368, %f3, %f349, %f367;
	mul.f32 	%f369, %f365, %f368;
	st.global.f32 	[%rd5], %f369;
	mul.f32 	%f370, %f359, %f154;
	mul.f32 	%f371, %f2, %f355;
	fma.rn.f32 	%f372, %f1, %f352, %f371;
	fma.rn.f32 	%f373, %f3, %f358, %f372;
	mul.f32 	%f374, %f370, %f373;
	st.global.f32 	[%rd6], %f374;

BB0_106:
	ret;
}


`
	)
