package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for scaleemergentfield kernel
var scaleemergentfieldCode cu.Function

// Stores the arguments for scaleemergentfield kernel invocation
type scaleemergentfieldArgsT struct {
	argFxScale unsafe.Pointer
	argFyScale unsafe.Pointer
	argFzScale unsafe.Pointer
	argFx unsafe.Pointer
	argFy unsafe.Pointer
	argFz unsafe.Pointer
	argCx float32
	argCy float32
	argCz float32
	argNx int
	argNy int
	argNz int
	argptr [12]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for scaleemergentfield kernel invocation
var scaleemergentfieldArgs scaleemergentfieldArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	scaleemergentfieldArgs.argptr[0] = unsafe.Pointer(&scaleemergentfieldArgs.argFxScale)
	scaleemergentfieldArgs.argptr[1] = unsafe.Pointer(&scaleemergentfieldArgs.argFyScale)
	scaleemergentfieldArgs.argptr[2] = unsafe.Pointer(&scaleemergentfieldArgs.argFzScale)
	scaleemergentfieldArgs.argptr[3] = unsafe.Pointer(&scaleemergentfieldArgs.argFx)
	scaleemergentfieldArgs.argptr[4] = unsafe.Pointer(&scaleemergentfieldArgs.argFy)
	scaleemergentfieldArgs.argptr[5] = unsafe.Pointer(&scaleemergentfieldArgs.argFz)
	scaleemergentfieldArgs.argptr[6] = unsafe.Pointer(&scaleemergentfieldArgs.argCx)
	scaleemergentfieldArgs.argptr[7] = unsafe.Pointer(&scaleemergentfieldArgs.argCy)
	scaleemergentfieldArgs.argptr[8] = unsafe.Pointer(&scaleemergentfieldArgs.argCz)
	scaleemergentfieldArgs.argptr[9] = unsafe.Pointer(&scaleemergentfieldArgs.argNx)
	scaleemergentfieldArgs.argptr[10] = unsafe.Pointer(&scaleemergentfieldArgs.argNy)
	scaleemergentfieldArgs.argptr[11] = unsafe.Pointer(&scaleemergentfieldArgs.argNz)
	}

// Wrapper for scaleemergentfield CUDA kernel, asynchronous.
func kScaleemergentfieldAsync(Fx_scale unsafe.Pointer, Fy_scale unsafe.Pointer, Fz_scale unsafe.Pointer, Fx unsafe.Pointer, Fy unsafe.Pointer, Fz unsafe.Pointer, cx float32, cy float32, cz float32, Nx int, Ny int, Nz int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("scaleemergentfield")
	}

	scaleemergentfieldArgs.Lock()
	defer scaleemergentfieldArgs.Unlock()

	if scaleemergentfieldCode == 0 {
		scaleemergentfieldCode = fatbinLoad(scaleemergentfieldMap, "scaleemergentfield")
	}

	scaleemergentfieldArgs.argFxScale = Fx_scale
	scaleemergentfieldArgs.argFyScale = Fy_scale
	scaleemergentfieldArgs.argFzScale = Fz_scale
	scaleemergentfieldArgs.argFx = Fx
	scaleemergentfieldArgs.argFy = Fy
	scaleemergentfieldArgs.argFz = Fz
	scaleemergentfieldArgs.argCx = cx
	scaleemergentfieldArgs.argCy = cy
	scaleemergentfieldArgs.argCz = cz
	scaleemergentfieldArgs.argNx = Nx
	scaleemergentfieldArgs.argNy = Ny
	scaleemergentfieldArgs.argNz = Nz
	
	args := scaleemergentfieldArgs.argptr[:]
	cu.LaunchKernel(scaleemergentfieldCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("scaleemergentfield")
	}
}

// maps compute capability on PTX code for scaleemergentfield kernel.
var scaleemergentfieldMap = map[int]string{
	0: "",
	52: scaleemergentfieldPtx52,
}

// scaleemergentfield PTX code for various compute capabilities.
const (
	scaleemergentfieldPtx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	scaleemergentfield

.visible .entry scaleemergentfield(
	.param .u64 scaleemergentfield_param_0,
	.param .u64 scaleemergentfield_param_1,
	.param .u64 scaleemergentfield_param_2,
	.param .u64 scaleemergentfield_param_3,
	.param .u64 scaleemergentfield_param_4,
	.param .u64 scaleemergentfield_param_5,
	.param .f32 scaleemergentfield_param_6,
	.param .f32 scaleemergentfield_param_7,
	.param .f32 scaleemergentfield_param_8,
	.param .u32 scaleemergentfield_param_9,
	.param .u32 scaleemergentfield_param_10,
	.param .u32 scaleemergentfield_param_11
)
{
	.reg .pred 	%p<6>;
	.reg .f32 	%f<13>;
	.reg .b32 	%r<18>;
	.reg .b64 	%rd<20>;


	ld.param.u64 	%rd1, [scaleemergentfield_param_0];
	ld.param.u64 	%rd2, [scaleemergentfield_param_1];
	ld.param.u64 	%rd3, [scaleemergentfield_param_2];
	ld.param.u64 	%rd4, [scaleemergentfield_param_3];
	ld.param.u64 	%rd5, [scaleemergentfield_param_4];
	ld.param.u64 	%rd6, [scaleemergentfield_param_5];
	ld.param.f32 	%f1, [scaleemergentfield_param_6];
	ld.param.f32 	%f2, [scaleemergentfield_param_7];
	ld.param.f32 	%f3, [scaleemergentfield_param_8];
	ld.param.u32 	%r4, [scaleemergentfield_param_9];
	ld.param.u32 	%r5, [scaleemergentfield_param_10];
	ld.param.u32 	%r6, [scaleemergentfield_param_11];
	mov.u32 	%r7, %ctaid.x;
	mov.u32 	%r8, %ntid.x;
	mov.u32 	%r9, %tid.x;
	mad.lo.s32 	%r1, %r8, %r7, %r9;
	mov.u32 	%r10, %ntid.y;
	mov.u32 	%r11, %ctaid.y;
	mov.u32 	%r12, %tid.y;
	mad.lo.s32 	%r2, %r10, %r11, %r12;
	mov.u32 	%r13, %ntid.z;
	mov.u32 	%r14, %ctaid.z;
	mov.u32 	%r15, %tid.z;
	mad.lo.s32 	%r3, %r13, %r14, %r15;
	setp.ge.s32	%p1, %r2, %r5;
	setp.ge.s32	%p2, %r1, %r4;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r3, %r6;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_2;

	cvta.to.global.u64 	%rd7, %rd4;
	mad.lo.s32 	%r16, %r3, %r5, %r2;
	mad.lo.s32 	%r17, %r16, %r4, %r1;
	mul.wide.s32 	%rd8, %r17, 4;
	add.s64 	%rd9, %rd7, %rd8;
	ld.global.nc.f32 	%f4, [%rd9];
	mul.f32 	%f5, %f4, %f2;
	mul.f32 	%f6, %f5, %f3;
	cvta.to.global.u64 	%rd10, %rd1;
	add.s64 	%rd11, %rd10, %rd8;
	st.global.f32 	[%rd11], %f6;
	cvta.to.global.u64 	%rd12, %rd5;
	add.s64 	%rd13, %rd12, %rd8;
	ld.global.nc.f32 	%f7, [%rd13];
	mul.f32 	%f8, %f7, %f1;
	mul.f32 	%f9, %f8, %f3;
	cvta.to.global.u64 	%rd14, %rd2;
	add.s64 	%rd15, %rd14, %rd8;
	st.global.f32 	[%rd15], %f9;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd8;
	ld.global.nc.f32 	%f10, [%rd17];
	mul.f32 	%f11, %f10, %f1;
	mul.f32 	%f12, %f11, %f2;
	cvta.to.global.u64 	%rd18, %rd3;
	add.s64 	%rd19, %rd18, %rd8;
	st.global.f32 	[%rd19], %f12;

BB0_2:
	ret;
}


`
	)
