package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for setvectorpotential kernel
var setvectorpotentialCode cu.Function

// Stores the arguments for setvectorpotential kernel invocation
type setvectorpotentialArgsT struct {
	argAx unsafe.Pointer
	argAy unsafe.Pointer
	argAz unsafe.Pointer
	argFx unsafe.Pointer
	argFy unsafe.Pointer
	argFz unsafe.Pointer
	argCy float32
	argNx int
	argNy int
	argNz int
	argPBC byte
	argptr [11]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for setvectorpotential kernel invocation
var setvectorpotentialArgs setvectorpotentialArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	setvectorpotentialArgs.argptr[0] = unsafe.Pointer(&setvectorpotentialArgs.argAx)
	setvectorpotentialArgs.argptr[1] = unsafe.Pointer(&setvectorpotentialArgs.argAy)
	setvectorpotentialArgs.argptr[2] = unsafe.Pointer(&setvectorpotentialArgs.argAz)
	setvectorpotentialArgs.argptr[3] = unsafe.Pointer(&setvectorpotentialArgs.argFx)
	setvectorpotentialArgs.argptr[4] = unsafe.Pointer(&setvectorpotentialArgs.argFy)
	setvectorpotentialArgs.argptr[5] = unsafe.Pointer(&setvectorpotentialArgs.argFz)
	setvectorpotentialArgs.argptr[6] = unsafe.Pointer(&setvectorpotentialArgs.argCy)
	setvectorpotentialArgs.argptr[7] = unsafe.Pointer(&setvectorpotentialArgs.argNx)
	setvectorpotentialArgs.argptr[8] = unsafe.Pointer(&setvectorpotentialArgs.argNy)
	setvectorpotentialArgs.argptr[9] = unsafe.Pointer(&setvectorpotentialArgs.argNz)
	setvectorpotentialArgs.argptr[10] = unsafe.Pointer(&setvectorpotentialArgs.argPBC)
	}

// Wrapper for setvectorpotential CUDA kernel, asynchronous.
func kSetvectorpotentialAsync(Ax unsafe.Pointer, Ay unsafe.Pointer, Az unsafe.Pointer, Fx unsafe.Pointer, Fy unsafe.Pointer, Fz unsafe.Pointer, cy float32, Nx int, Ny int, Nz int, PBC byte, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("setvectorpotential")
	}

	setvectorpotentialArgs.Lock()
	defer setvectorpotentialArgs.Unlock()

	if setvectorpotentialCode == 0 {
		setvectorpotentialCode = fatbinLoad(setvectorpotentialMap, "setvectorpotential")
	}

	setvectorpotentialArgs.argAx = Ax
	setvectorpotentialArgs.argAy = Ay
	setvectorpotentialArgs.argAz = Az
	setvectorpotentialArgs.argFx = Fx
	setvectorpotentialArgs.argFy = Fy
	setvectorpotentialArgs.argFz = Fz
	setvectorpotentialArgs.argCy = cy
	setvectorpotentialArgs.argNx = Nx
	setvectorpotentialArgs.argNy = Ny
	setvectorpotentialArgs.argNz = Nz
	setvectorpotentialArgs.argPBC = PBC
	
	args := setvectorpotentialArgs.argptr[:]
	cu.LaunchKernel(setvectorpotentialCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("setvectorpotential")
	}
}

// maps compute capability on PTX code for setvectorpotential kernel.
var setvectorpotentialMap = map[int]string{
	0: "",
	52: setvectorpotentialPtx52,
}

// setvectorpotential PTX code for various compute capabilities.
const (
	setvectorpotentialPtx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	setvectorpotential

.visible .entry setvectorpotential(
	.param .u64 setvectorpotential_param_0,
	.param .u64 setvectorpotential_param_1,
	.param .u64 setvectorpotential_param_2,
	.param .u64 setvectorpotential_param_3,
	.param .u64 setvectorpotential_param_4,
	.param .u64 setvectorpotential_param_5,
	.param .f32 setvectorpotential_param_6,
	.param .u32 setvectorpotential_param_7,
	.param .u32 setvectorpotential_param_8,
	.param .u32 setvectorpotential_param_9,
	.param .u8 setvectorpotential_param_10
)
{
	.reg .pred 	%p<12>;
	.reg .f32 	%f<66>;
	.reg .b32 	%r<96>;
	.reg .b64 	%rd<40>;


	ld.param.u64 	%rd3, [setvectorpotential_param_0];
	ld.param.u64 	%rd4, [setvectorpotential_param_1];
	ld.param.u64 	%rd5, [setvectorpotential_param_2];
	ld.param.u64 	%rd6, [setvectorpotential_param_3];
	ld.param.u64 	%rd7, [setvectorpotential_param_5];
	ld.param.f32 	%f19, [setvectorpotential_param_6];
	ld.param.u32 	%r16, [setvectorpotential_param_7];
	ld.param.u32 	%r17, [setvectorpotential_param_8];
	ld.param.u32 	%r18, [setvectorpotential_param_9];
	mov.u32 	%r19, %ctaid.x;
	mov.u32 	%r20, %ntid.x;
	mov.u32 	%r21, %tid.x;
	mad.lo.s32 	%r22, %r20, %r19, %r21;
	mov.u32 	%r23, %ntid.y;
	mov.u32 	%r24, %ctaid.y;
	mov.u32 	%r25, %tid.y;
	mad.lo.s32 	%r26, %r23, %r24, %r25;
	mov.u32 	%r27, %ntid.z;
	mov.u32 	%r28, %ctaid.z;
	mov.u32 	%r29, %tid.z;
	mad.lo.s32 	%r30, %r27, %r28, %r29;
	setp.ge.s32	%p1, %r26, %r17;
	setp.ge.s32	%p2, %r22, %r16;
	or.pred  	%p3, %p1, %p2;
	setp.ge.s32	%p4, %r30, %r18;
	or.pred  	%p5, %p3, %p4;
	@%p5 bra 	BB0_12;

	mul.lo.s32 	%r1, %r30, %r17;
	mov.f32 	%f64, 0f00000000;
	setp.lt.s32	%p6, %r26, 1;
	mov.f32 	%f65, %f64;
	@%p6 bra 	BB0_11;

	and.b32  	%r3, %r26, 3;
	setp.eq.s32	%p7, %r3, 0;
	mov.f32 	%f64, 0f00000000;
	mov.u32 	%r93, 0;
	mov.f32 	%f65, %f64;
	@%p7 bra 	BB0_8;

	setp.eq.s32	%p8, %r3, 1;
	mov.f32 	%f58, 0f00000000;
	mov.u32 	%r92, 0;
	mov.f32 	%f59, %f58;
	@%p8 bra 	BB0_7;

	setp.eq.s32	%p9, %r3, 2;
	mov.f32 	%f56, 0f00000000;
	mov.u32 	%r91, 0;
	mov.f32 	%f57, %f56;
	@%p9 bra 	BB0_6;

	mad.lo.s32 	%r50, %r1, %r16, %r22;
	cvta.to.global.u64 	%rd8, %rd7;
	mul.wide.s32 	%rd9, %r50, 4;
	add.s64 	%rd10, %rd8, %rd9;
	ld.global.nc.f32 	%f28, [%rd10];
	mul.f32 	%f29, %f28, %f19;
	mov.f32 	%f30, 0f00000000;
	sub.f32 	%f56, %f30, %f29;
	cvta.to.global.u64 	%rd11, %rd6;
	add.s64 	%rd12, %rd11, %rd9;
	ld.global.nc.f32 	%f31, [%rd12];
	fma.rn.f32 	%f57, %f31, %f19, 0f00000000;
	mov.u32 	%r91, 1;

BB0_6:
	add.s32 	%r51, %r91, %r1;
	mad.lo.s32 	%r56, %r51, %r16, %r22;
	cvta.to.global.u64 	%rd13, %rd7;
	mul.wide.s32 	%rd14, %r56, 4;
	add.s64 	%rd15, %rd13, %rd14;
	ld.global.nc.f32 	%f32, [%rd15];
	mul.f32 	%f33, %f32, %f19;
	sub.f32 	%f58, %f56, %f33;
	cvta.to.global.u64 	%rd16, %rd6;
	add.s64 	%rd17, %rd16, %rd14;
	ld.global.nc.f32 	%f34, [%rd17];
	fma.rn.f32 	%f59, %f34, %f19, %f57;
	add.s32 	%r92, %r91, 1;

BB0_7:
	add.s32 	%r57, %r92, %r1;
	mad.lo.s32 	%r62, %r57, %r16, %r22;
	cvta.to.global.u64 	%rd18, %rd7;
	mul.wide.s32 	%rd19, %r62, 4;
	add.s64 	%rd20, %rd18, %rd19;
	ld.global.nc.f32 	%f35, [%rd20];
	mul.f32 	%f36, %f35, %f19;
	sub.f32 	%f64, %f58, %f36;
	cvta.to.global.u64 	%rd21, %rd6;
	add.s64 	%rd22, %rd21, %rd19;
	ld.global.nc.f32 	%f37, [%rd22];
	fma.rn.f32 	%f65, %f37, %f19, %f59;
	add.s32 	%r93, %r92, 1;

BB0_8:
	setp.lt.u32	%p10, %r26, 4;
	@%p10 bra 	BB0_11;

	shl.b32 	%r9, %r16, 2;
	mad.lo.s32 	%r73, %r17, %r30, %r93;
	mad.lo.s32 	%r94, %r16, %r73, %r22;
	cvta.to.global.u64 	%rd1, %rd6;
	cvta.to.global.u64 	%rd2, %rd7;

BB0_10:
	mul.wide.s32 	%rd23, %r94, 4;
	add.s64 	%rd24, %rd2, %rd23;
	ld.global.nc.f32 	%f38, [%rd24];
	mul.f32 	%f39, %f38, %f19;
	sub.f32 	%f40, %f64, %f39;
	add.s64 	%rd25, %rd1, %rd23;
	ld.global.nc.f32 	%f41, [%rd25];
	fma.rn.f32 	%f42, %f41, %f19, %f65;
	cvt.s64.s32	%rd26, %r9;
	add.s64 	%rd27, %rd24, %rd26;
	ld.global.nc.f32 	%f43, [%rd27];
	mul.f32 	%f44, %f43, %f19;
	sub.f32 	%f45, %f40, %f44;
	add.s64 	%rd28, %rd25, %rd26;
	ld.global.nc.f32 	%f46, [%rd28];
	fma.rn.f32 	%f47, %f46, %f19, %f42;
	add.s64 	%rd29, %rd27, %rd26;
	ld.global.nc.f32 	%f48, [%rd29];
	mul.f32 	%f49, %f48, %f19;
	sub.f32 	%f50, %f45, %f49;
	add.s64 	%rd30, %rd28, %rd26;
	ld.global.nc.f32 	%f51, [%rd30];
	fma.rn.f32 	%f52, %f51, %f19, %f47;
	add.s64 	%rd31, %rd29, %rd26;
	ld.global.nc.f32 	%f53, [%rd31];
	mul.f32 	%f54, %f53, %f19;
	sub.f32 	%f64, %f50, %f54;
	add.s64 	%rd32, %rd30, %rd26;
	ld.global.nc.f32 	%f55, [%rd32];
	fma.rn.f32 	%f65, %f55, %f19, %f52;
	add.s32 	%r94, %r94, %r9;
	add.s32 	%r93, %r93, 4;
	setp.lt.s32	%p11, %r93, %r26;
	@%p11 bra 	BB0_10;

BB0_11:
	mad.lo.s32 	%r84, %r30, %r17, %r26;
	mad.lo.s32 	%r89, %r84, %r16, %r22;
	cvta.to.global.u64 	%rd33, %rd3;
	mul.wide.s32 	%rd34, %r89, 4;
	add.s64 	%rd35, %rd33, %rd34;
	st.global.f32 	[%rd35], %f64;
	cvta.to.global.u64 	%rd36, %rd4;
	add.s64 	%rd37, %rd36, %rd34;
	mov.u32 	%r90, 0;
	st.global.u32 	[%rd37], %r90;
	cvta.to.global.u64 	%rd38, %rd5;
	add.s64 	%rd39, %rd38, %rd34;
	st.global.f32 	[%rd39], %f65;

BB0_12:
	ret;
}


`
	)
