package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for lltorque2 kernel
var lltorque2Code cu.Function

// Stores the arguments for lltorque2 kernel invocation
type lltorque2ArgsT struct {
	argTx unsafe.Pointer
	argTy unsafe.Pointer
	argTz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argHx unsafe.Pointer
	argHy unsafe.Pointer
	argHz unsafe.Pointer
	argAlpha unsafe.Pointer
	argAlphaMul float32
	argSponge unsafe.Pointer
	argN int
	argptr [13]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for lltorque2 kernel invocation
var lltorque2Args lltorque2ArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	lltorque2Args.argptr[0] = unsafe.Pointer(&lltorque2Args.argTx)
	lltorque2Args.argptr[1] = unsafe.Pointer(&lltorque2Args.argTy)
	lltorque2Args.argptr[2] = unsafe.Pointer(&lltorque2Args.argTz)
	lltorque2Args.argptr[3] = unsafe.Pointer(&lltorque2Args.argMx)
	lltorque2Args.argptr[4] = unsafe.Pointer(&lltorque2Args.argMy)
	lltorque2Args.argptr[5] = unsafe.Pointer(&lltorque2Args.argMz)
	lltorque2Args.argptr[6] = unsafe.Pointer(&lltorque2Args.argHx)
	lltorque2Args.argptr[7] = unsafe.Pointer(&lltorque2Args.argHy)
	lltorque2Args.argptr[8] = unsafe.Pointer(&lltorque2Args.argHz)
	lltorque2Args.argptr[9] = unsafe.Pointer(&lltorque2Args.argAlpha)
	lltorque2Args.argptr[10] = unsafe.Pointer(&lltorque2Args.argAlphaMul)
	lltorque2Args.argptr[11] = unsafe.Pointer(&lltorque2Args.argSponge)
	lltorque2Args.argptr[12] = unsafe.Pointer(&lltorque2Args.argN)
	}

// Wrapper for lltorque2 CUDA kernel, asynchronous.
func kLltorque2Async(tx unsafe.Pointer, ty unsafe.Pointer, tz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, hx unsafe.Pointer, hy unsafe.Pointer, hz unsafe.Pointer, alpha_ unsafe.Pointer, alpha_mul float32, sponge_ unsafe.Pointer, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("lltorque2")
	}

	lltorque2Args.Lock()
	defer lltorque2Args.Unlock()

	if lltorque2Code == 0 {
		lltorque2Code = fatbinLoad(lltorque2Map, "lltorque2")
	}

	lltorque2Args.argTx = tx
	lltorque2Args.argTy = ty
	lltorque2Args.argTz = tz
	lltorque2Args.argMx = mx
	lltorque2Args.argMy = my
	lltorque2Args.argMz = mz
	lltorque2Args.argHx = hx
	lltorque2Args.argHy = hy
	lltorque2Args.argHz = hz
	lltorque2Args.argAlpha = alpha_
	lltorque2Args.argAlphaMul = alpha_mul
	lltorque2Args.argSponge = sponge_
	lltorque2Args.argN = N
	
	args := lltorque2Args.argptr[:]
	cu.LaunchKernel(lltorque2Code, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("lltorque2")
	}
}

// maps compute capability on PTX code for lltorque2 kernel.
var lltorque2Map = map[int]string{
	0: "",
	52: lltorque2Ptx52,
}

// lltorque2 PTX code for various compute capabilities.
const (
	lltorque2Ptx52 = `
.version 7.0
.target sm_52
.address_size 64

	// .globl	lltorque2

.visible .entry lltorque2(
	.param .u64 lltorque2_param_0,
	.param .u64 lltorque2_param_1,
	.param .u64 lltorque2_param_2,
	.param .u64 lltorque2_param_3,
	.param .u64 lltorque2_param_4,
	.param .u64 lltorque2_param_5,
	.param .u64 lltorque2_param_6,
	.param .u64 lltorque2_param_7,
	.param .u64 lltorque2_param_8,
	.param .u64 lltorque2_param_9,
	.param .f32 lltorque2_param_10,
	.param .u64 lltorque2_param_11,
	.param .u32 lltorque2_param_12
)
{
	.reg .pred 	%p<4>;
	.reg .f32 	%f<44>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<38>;


	ld.param.u64 	%rd1, [lltorque2_param_0];
	ld.param.u64 	%rd2, [lltorque2_param_1];
	ld.param.u64 	%rd3, [lltorque2_param_2];
	ld.param.u64 	%rd4, [lltorque2_param_3];
	ld.param.u64 	%rd5, [lltorque2_param_4];
	ld.param.u64 	%rd6, [lltorque2_param_5];
	ld.param.u64 	%rd7, [lltorque2_param_6];
	ld.param.u64 	%rd8, [lltorque2_param_7];
	ld.param.u64 	%rd9, [lltorque2_param_8];
	ld.param.u64 	%rd10, [lltorque2_param_9];
	ld.param.f32 	%f42, [lltorque2_param_10];
	ld.param.u64 	%rd11, [lltorque2_param_11];
	ld.param.u32 	%r2, [lltorque2_param_12];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r3, %r4, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32	%p1, %r1, %r2;
	@%p1 bra 	BB0_6;

	cvta.to.global.u64 	%rd12, %rd4;
	mul.wide.s32 	%rd13, %r1, 4;
	add.s64 	%rd14, %rd12, %rd13;
	ld.global.nc.f32 	%f1, [%rd14];
	cvta.to.global.u64 	%rd15, %rd5;
	add.s64 	%rd16, %rd15, %rd13;
	ld.global.nc.f32 	%f2, [%rd16];
	cvta.to.global.u64 	%rd17, %rd6;
	add.s64 	%rd18, %rd17, %rd13;
	ld.global.nc.f32 	%f3, [%rd18];
	cvta.to.global.u64 	%rd19, %rd7;
	add.s64 	%rd20, %rd19, %rd13;
	ld.global.nc.f32 	%f4, [%rd20];
	cvta.to.global.u64 	%rd21, %rd8;
	add.s64 	%rd22, %rd21, %rd13;
	ld.global.nc.f32 	%f5, [%rd22];
	cvta.to.global.u64 	%rd23, %rd9;
	add.s64 	%rd24, %rd23, %rd13;
	ld.global.nc.f32 	%f6, [%rd24];
	setp.eq.s64	%p2, %rd10, 0;
	@%p2 bra 	BB0_3;

	cvta.to.global.u64 	%rd25, %rd10;
	add.s64 	%rd27, %rd25, %rd13;
	ld.global.nc.f32 	%f12, [%rd27];
	mul.f32 	%f42, %f12, %f42;

BB0_3:
	setp.eq.s64	%p3, %rd11, 0;
	mov.f32 	%f43, 0f3F800000;
	@%p3 bra 	BB0_5;

	cvta.to.global.u64 	%rd28, %rd11;
	add.s64 	%rd30, %rd28, %rd13;
	ld.global.nc.f32 	%f43, [%rd30];

BB0_5:
	mul.f32 	%f14, %f3, %f5;
	mul.f32 	%f15, %f2, %f6;
	sub.f32 	%f16, %f15, %f14;
	mul.f32 	%f17, %f1, %f6;
	mul.f32 	%f18, %f3, %f4;
	sub.f32 	%f19, %f18, %f17;
	mul.f32 	%f20, %f2, %f4;
	mul.f32 	%f21, %f1, %f5;
	sub.f32 	%f22, %f21, %f20;
	add.f32 	%f23, %f42, %f43;
	fma.rn.f32 	%f24, %f23, %f23, 0f3F800000;
	mov.f32 	%f25, 0fBF800000;
	div.rn.f32 	%f26, %f25, %f24;
	mul.f32 	%f27, %f2, %f22;
	mul.f32 	%f28, %f3, %f19;
	sub.f32 	%f29, %f27, %f28;
	mul.f32 	%f30, %f3, %f16;
	mul.f32 	%f31, %f1, %f22;
	sub.f32 	%f32, %f30, %f31;
	mul.f32 	%f33, %f1, %f19;
	mul.f32 	%f34, %f2, %f16;
	sub.f32 	%f35, %f33, %f34;
	fma.rn.f32 	%f36, %f29, %f23, %f16;
	fma.rn.f32 	%f37, %f32, %f23, %f19;
	fma.rn.f32 	%f38, %f35, %f23, %f22;
	mul.f32 	%f39, %f26, %f36;
	mul.f32 	%f40, %f26, %f37;
	mul.f32 	%f41, %f26, %f38;
	cvta.to.global.u64 	%rd31, %rd1;
	add.s64 	%rd33, %rd31, %rd13;
	st.global.f32 	[%rd33], %f39;
	cvta.to.global.u64 	%rd34, %rd2;
	add.s64 	%rd35, %rd34, %rd13;
	st.global.f32 	[%rd35], %f40;
	cvta.to.global.u64 	%rd36, %rd3;
	add.s64 	%rd37, %rd36, %rd13;
	st.global.f32 	[%rd37], %f41;

BB0_6:
	ret;
}


`
	)
