package cuda

/*
 THIS FILE IS AUTO-GENERATED BY CUDA2GO.
 EDITING IS FUTILE.
*/

import (
	"sync"
	"unsafe"

	"github.com/MathieuMoalic/amumax/src/cuda/cu"
	"github.com/MathieuMoalic/amumax/src/timer"
)

// CUDA handle for addmagnetoelasticfield kernel
var addmagnetoelasticfieldCode cu.Function

// Stores the arguments for addmagnetoelasticfield kernel invocation
type addmagnetoelasticfieldArgsT struct {
	argBx unsafe.Pointer
	argBy unsafe.Pointer
	argBz unsafe.Pointer
	argMx unsafe.Pointer
	argMy unsafe.Pointer
	argMz unsafe.Pointer
	argExx unsafe.Pointer
	argExxMul float32
	argEyy unsafe.Pointer
	argEyyMul float32
	argEzz unsafe.Pointer
	argEzzMul float32
	argExy unsafe.Pointer
	argExyMul float32
	argExz unsafe.Pointer
	argExzMul float32
	argEyz unsafe.Pointer
	argEyzMul float32
	argB1 unsafe.Pointer
	argB1Mul float32
	argB2 unsafe.Pointer
	argB2Mul float32
	argMs unsafe.Pointer
	argMsMul float32
	argN int
	argptr [25]unsafe.Pointer
	sync.Mutex
}

// Stores the arguments for addmagnetoelasticfield kernel invocation
var addmagnetoelasticfieldArgs addmagnetoelasticfieldArgsT

func init() {
	// CUDA driver kernel call wants pointers to arguments, set them up once.
	addmagnetoelasticfieldArgs.argptr[0] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argBx)
	addmagnetoelasticfieldArgs.argptr[1] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argBy)
	addmagnetoelasticfieldArgs.argptr[2] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argBz)
	addmagnetoelasticfieldArgs.argptr[3] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argMx)
	addmagnetoelasticfieldArgs.argptr[4] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argMy)
	addmagnetoelasticfieldArgs.argptr[5] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argMz)
	addmagnetoelasticfieldArgs.argptr[6] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argExx)
	addmagnetoelasticfieldArgs.argptr[7] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argExxMul)
	addmagnetoelasticfieldArgs.argptr[8] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argEyy)
	addmagnetoelasticfieldArgs.argptr[9] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argEyyMul)
	addmagnetoelasticfieldArgs.argptr[10] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argEzz)
	addmagnetoelasticfieldArgs.argptr[11] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argEzzMul)
	addmagnetoelasticfieldArgs.argptr[12] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argExy)
	addmagnetoelasticfieldArgs.argptr[13] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argExyMul)
	addmagnetoelasticfieldArgs.argptr[14] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argExz)
	addmagnetoelasticfieldArgs.argptr[15] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argExzMul)
	addmagnetoelasticfieldArgs.argptr[16] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argEyz)
	addmagnetoelasticfieldArgs.argptr[17] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argEyzMul)
	addmagnetoelasticfieldArgs.argptr[18] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argB1)
	addmagnetoelasticfieldArgs.argptr[19] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argB1Mul)
	addmagnetoelasticfieldArgs.argptr[20] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argB2)
	addmagnetoelasticfieldArgs.argptr[21] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argB2Mul)
	addmagnetoelasticfieldArgs.argptr[22] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argMs)
	addmagnetoelasticfieldArgs.argptr[23] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argMsMul)
	addmagnetoelasticfieldArgs.argptr[24] = unsafe.Pointer(&addmagnetoelasticfieldArgs.argN)
	}

// Wrapper for addmagnetoelasticfield CUDA kernel, asynchronous.
func kAddmagnetoelasticfieldAsync(Bx unsafe.Pointer, By unsafe.Pointer, Bz unsafe.Pointer, mx unsafe.Pointer, my unsafe.Pointer, mz unsafe.Pointer, exx_ unsafe.Pointer, exx_mul float32, eyy_ unsafe.Pointer, eyy_mul float32, ezz_ unsafe.Pointer, ezz_mul float32, exy_ unsafe.Pointer, exy_mul float32, exz_ unsafe.Pointer, exz_mul float32, eyz_ unsafe.Pointer, eyz_mul float32, B1_ unsafe.Pointer, B1_mul float32, B2_ unsafe.Pointer, B2_mul float32, Ms_ unsafe.Pointer, Ms_mul float32, N int, cfg *config) {
	if Synchronous { // debug
		Sync()
		timer.Start("addmagnetoelasticfield")
	}

	addmagnetoelasticfieldArgs.Lock()
	defer addmagnetoelasticfieldArgs.Unlock()

	if addmagnetoelasticfieldCode == 0 {
		addmagnetoelasticfieldCode = fatbinLoad(addmagnetoelasticfieldMap, "addmagnetoelasticfield")
	}

	addmagnetoelasticfieldArgs.argBx = Bx
	addmagnetoelasticfieldArgs.argBy = By
	addmagnetoelasticfieldArgs.argBz = Bz
	addmagnetoelasticfieldArgs.argMx = mx
	addmagnetoelasticfieldArgs.argMy = my
	addmagnetoelasticfieldArgs.argMz = mz
	addmagnetoelasticfieldArgs.argExx = exx_
	addmagnetoelasticfieldArgs.argExxMul = exx_mul
	addmagnetoelasticfieldArgs.argEyy = eyy_
	addmagnetoelasticfieldArgs.argEyyMul = eyy_mul
	addmagnetoelasticfieldArgs.argEzz = ezz_
	addmagnetoelasticfieldArgs.argEzzMul = ezz_mul
	addmagnetoelasticfieldArgs.argExy = exy_
	addmagnetoelasticfieldArgs.argExyMul = exy_mul
	addmagnetoelasticfieldArgs.argExz = exz_
	addmagnetoelasticfieldArgs.argExzMul = exz_mul
	addmagnetoelasticfieldArgs.argEyz = eyz_
	addmagnetoelasticfieldArgs.argEyzMul = eyz_mul
	addmagnetoelasticfieldArgs.argB1 = B1_
	addmagnetoelasticfieldArgs.argB1Mul = B1_mul
	addmagnetoelasticfieldArgs.argB2 = B2_
	addmagnetoelasticfieldArgs.argB2Mul = B2_mul
	addmagnetoelasticfieldArgs.argMs = Ms_
	addmagnetoelasticfieldArgs.argMsMul = Ms_mul
	addmagnetoelasticfieldArgs.argN = N
	
	args := addmagnetoelasticfieldArgs.argptr[:]
	cu.LaunchKernel(addmagnetoelasticfieldCode, cfg.Grid.X, cfg.Grid.Y, cfg.Grid.Z, cfg.Block.X, cfg.Block.Y, cfg.Block.Z, 0, stream0, args)

	if Synchronous { // debug
		Sync()
		timer.Stop("addmagnetoelasticfield")
	}
}

// maps compute capability on PTX code for addmagnetoelasticfield kernel.
var addmagnetoelasticfieldMap = map[int]string{
	0: "",
	52: addmagnetoelasticfieldPtx52,
}

// addmagnetoelasticfield PTX code for various compute capabilities.
const (
	addmagnetoelasticfieldPtx52 = `
.version 8.4
.target sm_52
.address_size 64

	// .globl	addmagnetoelasticfield

.visible .entry addmagnetoelasticfield(
	.param .u64 addmagnetoelasticfield_param_0,
	.param .u64 addmagnetoelasticfield_param_1,
	.param .u64 addmagnetoelasticfield_param_2,
	.param .u64 addmagnetoelasticfield_param_3,
	.param .u64 addmagnetoelasticfield_param_4,
	.param .u64 addmagnetoelasticfield_param_5,
	.param .u64 addmagnetoelasticfield_param_6,
	.param .f32 addmagnetoelasticfield_param_7,
	.param .u64 addmagnetoelasticfield_param_8,
	.param .f32 addmagnetoelasticfield_param_9,
	.param .u64 addmagnetoelasticfield_param_10,
	.param .f32 addmagnetoelasticfield_param_11,
	.param .u64 addmagnetoelasticfield_param_12,
	.param .f32 addmagnetoelasticfield_param_13,
	.param .u64 addmagnetoelasticfield_param_14,
	.param .f32 addmagnetoelasticfield_param_15,
	.param .u64 addmagnetoelasticfield_param_16,
	.param .f32 addmagnetoelasticfield_param_17,
	.param .u64 addmagnetoelasticfield_param_18,
	.param .f32 addmagnetoelasticfield_param_19,
	.param .u64 addmagnetoelasticfield_param_20,
	.param .f32 addmagnetoelasticfield_param_21,
	.param .u64 addmagnetoelasticfield_param_22,
	.param .f32 addmagnetoelasticfield_param_23,
	.param .u32 addmagnetoelasticfield_param_24
)
{
	.reg .pred 	%p<12>;
	.reg .f32 	%f<79>;
	.reg .b32 	%r<9>;
	.reg .b64 	%rd<56>;


	ld.param.u64 	%rd1, [addmagnetoelasticfield_param_0];
	ld.param.u64 	%rd2, [addmagnetoelasticfield_param_1];
	ld.param.u64 	%rd3, [addmagnetoelasticfield_param_2];
	ld.param.u64 	%rd4, [addmagnetoelasticfield_param_3];
	ld.param.u64 	%rd5, [addmagnetoelasticfield_param_4];
	ld.param.u64 	%rd6, [addmagnetoelasticfield_param_5];
	ld.param.u64 	%rd7, [addmagnetoelasticfield_param_6];
	ld.param.f32 	%f69, [addmagnetoelasticfield_param_7];
	ld.param.u64 	%rd8, [addmagnetoelasticfield_param_8];
	ld.param.f32 	%f70, [addmagnetoelasticfield_param_9];
	ld.param.u64 	%rd9, [addmagnetoelasticfield_param_10];
	ld.param.f32 	%f71, [addmagnetoelasticfield_param_11];
	ld.param.u64 	%rd10, [addmagnetoelasticfield_param_12];
	ld.param.f32 	%f72, [addmagnetoelasticfield_param_13];
	ld.param.u64 	%rd11, [addmagnetoelasticfield_param_14];
	ld.param.f32 	%f73, [addmagnetoelasticfield_param_15];
	ld.param.u64 	%rd12, [addmagnetoelasticfield_param_16];
	ld.param.f32 	%f74, [addmagnetoelasticfield_param_17];
	ld.param.u64 	%rd13, [addmagnetoelasticfield_param_18];
	ld.param.f32 	%f77, [addmagnetoelasticfield_param_19];
	ld.param.u64 	%rd14, [addmagnetoelasticfield_param_20];
	ld.param.f32 	%f78, [addmagnetoelasticfield_param_21];
	ld.param.u64 	%rd15, [addmagnetoelasticfield_param_22];
	ld.param.f32 	%f75, [addmagnetoelasticfield_param_23];
	ld.param.u32 	%r2, [addmagnetoelasticfield_param_24];
	mov.u32 	%r3, %nctaid.x;
	mov.u32 	%r4, %ctaid.y;
	mov.u32 	%r5, %ctaid.x;
	mad.lo.s32 	%r6, %r4, %r3, %r5;
	mov.u32 	%r7, %ntid.x;
	mov.u32 	%r8, %tid.x;
	mad.lo.s32 	%r1, %r6, %r7, %r8;
	setp.ge.s32 	%p1, %r1, %r2;
	@%p1 bra 	$L__BB0_22;

	setp.eq.s64 	%p2, %rd7, 0;
	@%p2 bra 	$L__BB0_3;

	cvta.to.global.u64 	%rd16, %rd7;
	mul.wide.s32 	%rd17, %r1, 4;
	add.s64 	%rd18, %rd16, %rd17;
	ld.global.nc.f32 	%f30, [%rd18];
	mul.f32 	%f69, %f30, %f69;

$L__BB0_3:
	setp.eq.s64 	%p3, %rd8, 0;
	@%p3 bra 	$L__BB0_5;

	cvta.to.global.u64 	%rd19, %rd8;
	mul.wide.s32 	%rd20, %r1, 4;
	add.s64 	%rd21, %rd19, %rd20;
	ld.global.nc.f32 	%f31, [%rd21];
	mul.f32 	%f70, %f31, %f70;

$L__BB0_5:
	setp.eq.s64 	%p4, %rd9, 0;
	@%p4 bra 	$L__BB0_7;

	cvta.to.global.u64 	%rd22, %rd9;
	mul.wide.s32 	%rd23, %r1, 4;
	add.s64 	%rd24, %rd22, %rd23;
	ld.global.nc.f32 	%f32, [%rd24];
	mul.f32 	%f71, %f32, %f71;

$L__BB0_7:
	setp.eq.s64 	%p5, %rd10, 0;
	@%p5 bra 	$L__BB0_9;

	cvta.to.global.u64 	%rd25, %rd10;
	mul.wide.s32 	%rd26, %r1, 4;
	add.s64 	%rd27, %rd25, %rd26;
	ld.global.nc.f32 	%f33, [%rd27];
	mul.f32 	%f72, %f33, %f72;

$L__BB0_9:
	setp.eq.s64 	%p6, %rd11, 0;
	@%p6 bra 	$L__BB0_11;

	cvta.to.global.u64 	%rd28, %rd11;
	mul.wide.s32 	%rd29, %r1, 4;
	add.s64 	%rd30, %rd28, %rd29;
	ld.global.nc.f32 	%f34, [%rd30];
	mul.f32 	%f73, %f34, %f73;

$L__BB0_11:
	setp.eq.s64 	%p7, %rd12, 0;
	@%p7 bra 	$L__BB0_13;

	cvta.to.global.u64 	%rd31, %rd12;
	mul.wide.s32 	%rd32, %r1, 4;
	add.s64 	%rd33, %rd31, %rd32;
	ld.global.nc.f32 	%f35, [%rd33];
	mul.f32 	%f74, %f35, %f74;

$L__BB0_13:
	setp.eq.s64 	%p8, %rd15, 0;
	@%p8 bra 	$L__BB0_15;

	cvta.to.global.u64 	%rd34, %rd15;
	mul.wide.s32 	%rd35, %r1, 4;
	add.s64 	%rd36, %rd34, %rd35;
	ld.global.nc.f32 	%f36, [%rd36];
	mul.f32 	%f75, %f36, %f75;

$L__BB0_15:
	setp.eq.f32 	%p9, %f75, 0f00000000;
	mov.f32 	%f76, 0f00000000;
	@%p9 bra 	$L__BB0_17;

	rcp.rn.f32 	%f76, %f75;

$L__BB0_17:
	setp.eq.s64 	%p10, %rd13, 0;
	@%p10 bra 	$L__BB0_19;

	cvta.to.global.u64 	%rd37, %rd13;
	mul.wide.s32 	%rd38, %r1, 4;
	add.s64 	%rd39, %rd37, %rd38;
	ld.global.nc.f32 	%f38, [%rd39];
	mul.f32 	%f77, %f38, %f77;

$L__BB0_19:
	setp.eq.s64 	%p11, %rd14, 0;
	@%p11 bra 	$L__BB0_21;

	cvta.to.global.u64 	%rd40, %rd14;
	mul.wide.s32 	%rd41, %r1, 4;
	add.s64 	%rd42, %rd40, %rd41;
	ld.global.nc.f32 	%f39, [%rd42];
	mul.f32 	%f78, %f39, %f78;

$L__BB0_21:
	mul.f32 	%f40, %f76, %f77;
	cvta.to.global.u64 	%rd43, %rd4;
	mul.wide.s32 	%rd44, %r1, 4;
	add.s64 	%rd45, %rd43, %rd44;
	cvta.to.global.u64 	%rd46, %rd5;
	add.s64 	%rd47, %rd46, %rd44;
	cvta.to.global.u64 	%rd48, %rd6;
	add.s64 	%rd49, %rd48, %rd44;
	ld.global.nc.f32 	%f41, [%rd45];
	mul.f32 	%f42, %f40, %f41;
	ld.global.nc.f32 	%f43, [%rd47];
	ld.global.nc.f32 	%f44, [%rd49];
	mul.f32 	%f45, %f73, %f44;
	fma.rn.f32 	%f46, %f72, %f43, %f45;
	mul.f32 	%f47, %f76, %f78;
	mul.f32 	%f48, %f47, %f46;
	fma.rn.f32 	%f49, %f69, %f42, %f48;
	cvta.to.global.u64 	%rd50, %rd1;
	add.s64 	%rd51, %rd50, %rd44;
	ld.global.f32 	%f50, [%rd51];
	add.f32 	%f51, %f49, %f49;
	sub.f32 	%f52, %f50, %f51;
	st.global.f32 	[%rd51], %f52;
	mul.f32 	%f53, %f40, %f43;
	mul.f32 	%f54, %f74, %f44;
	fma.rn.f32 	%f55, %f72, %f41, %f54;
	mul.f32 	%f56, %f47, %f55;
	fma.rn.f32 	%f57, %f70, %f53, %f56;
	add.f32 	%f58, %f57, %f57;
	cvta.to.global.u64 	%rd52, %rd2;
	add.s64 	%rd53, %rd52, %rd44;
	ld.global.f32 	%f59, [%rd53];
	sub.f32 	%f60, %f59, %f58;
	st.global.f32 	[%rd53], %f60;
	mul.f32 	%f61, %f40, %f44;
	mul.f32 	%f62, %f74, %f43;
	fma.rn.f32 	%f63, %f73, %f41, %f62;
	mul.f32 	%f64, %f47, %f63;
	fma.rn.f32 	%f65, %f71, %f61, %f64;
	add.f32 	%f66, %f65, %f65;
	cvta.to.global.u64 	%rd54, %rd3;
	add.s64 	%rd55, %rd54, %rd44;
	ld.global.f32 	%f67, [%rd55];
	sub.f32 	%f68, %f67, %f66;
	st.global.f32 	[%rd55], %f68;

$L__BB0_22:
	ret;

}

`
	)
