package engine

func init() {
	DeclFunc("Flush", drainOutput, "Flush all pending output to disk.")
	DeclFunc("AutoSaveOvf", autoSaveOVF, "Auto save space-dependent quantity every period (s).")
	DeclFunc("AutoSnapshot", autoSnapshot, "Auto save image of quantity every period (s).")
	DeclFunc("Chunk", mx3chunks, "")
	DeclFunc("Uniform", uniform, "Uniform magnetization in given direction")
	DeclFunc("Vortex", vortex, "Vortex magnetization with given circulation and core polarization")
	DeclFunc("Antivortex", antiVortex, "Antivortex magnetization with given circulation and core polarization")
	DeclFunc("Radial", radial, "Radial magnetization with given charge and core polarization")
	DeclFunc("NeelSkyrmion", neelSkyrmion, "Néél skyrmion magnetization with given charge and core polarization")
	DeclFunc("BlochSkyrmion", blochSkyrmion, "Bloch skyrmion magnetization with given chirality and core polarization")
	DeclFunc("TwoDomain", twoDomain, "Twodomain magnetization with with given magnetization in left domain, wall, and right domain")
	DeclFunc("VortexWall", vortexWall, "Vortex wall magnetization with given mx in left and right domain and core circulation and polarization")
	DeclFunc("RandomMag", randomMag, "Random magnetization")
	DeclFunc("RandomMagSeed", randomMagSeed, "Random magnetization with given seed")
	DeclFunc("Conical", conical, "Conical state for given wave vector, cone direction, and cone angle")
	DeclFunc("Helical", helical, "Helical state for given wave vector")
	DeclFunc("Crop", crop, "Crops a quantity to cell ranges [x1,x2[, [y1,y2[, [z1,z2[")
	DeclFunc("CropX", cropX, "Crops a quantity to cell ranges [x1,x2[")
	DeclFunc("CropY", cropY, "Crops a quantity to cell ranges [y1,y2[")
	DeclFunc("CropZ", cropZ, "Crops a quantity to cell ranges [z1,z2[")
	DeclFunc("CropLayer", cropLayer, "Crops a quantity to a single layer")
	DeclFunc("CropRegion", cropRegion, "Crops a quantity to a region")

	DeclFunc("AddFieldTerm", addFieldTerm, "Add an expression to B_eff.")
	DeclFunc("AddEdensTerm", addEdensTerm, "Add an expression to Edens.")
	DeclFunc("Add", add, "Add two quantities")
	DeclFunc("Madd", madd, "Weighted addition: Madd(Q1,Q2,c1,c2) = c1*Q1 + c2*Q2")
	DeclFunc("Dot", dotProductFunc, "Dot product of two vector quantities")
	DeclFunc("Cross", cross, "Cross product of two vector quantities")
	DeclFunc("Mul", mul, "Point-wise product of two quantities")
	DeclFunc("MulMV", mulMV, "Matrix-Vector product: MulMV(AX, AY, AZ, m) = (AX·m, AY·m, AZ·m). "+
		"The arguments Ax, Ay, Az and m are quantities with 3 componets.")
	DeclFunc("Div", div, "Point-wise division of two quantities")
	DeclFunc("Const", constScalar, "Constant, uniform number")
	DeclFunc("ConstVector", constVector, "Constant, uniform vector")
	DeclFunc("Shifted", shiftedQuant, "Shifted quantity")
	DeclFunc("Masked", maskedQuant, "Mask quantity with shape")
	DeclFunc("Normalized", normalizedQuant, "Normalize quantity")
	DeclFunc("RemoveCustomFields", removeCustomFields, "Removes all custom fields again")

	DeclFunc("ext_ScaleExchange", scaleInterExchange, "Re-scales exchange coupling between two regions.")
	DeclFunc("ext_InterExchange", interExchange, "Sets exchange coupling between two regions.")
	DeclFunc("ext_ScaleDind", scaleInterDind, "Re-scales Dind coupling between two regions.")
	DeclFunc("ext_InterDind", interDind, "Sets Dind coupling between two regions.")
	DeclFunc("ext_centerBubble", centerBubble, "centerBubble shifts m after each step to keep the bubble position close to the center of the window")
	DeclFunc("ext_centerWall", centerWall, "centerWall(c) shifts m after each step to keep m_c close to zero")
	DeclFunc("ext_centerWallInRegion", centerWallInRegion, "centerWallInRegion(R, c) shifts m after each step to keep m_c in region R close to zero")
	DeclFunc("ext_centerWallInLayer", centerWallInLayer, "centerWallInLayer(L, c) shifts m after each step to keep m_c in layer L close to zero")
	DeclFunc("ext_make3dgrains", voronoi3d, "3D Voronoi tesselation over shape (grain size, starting region number, num regions, shape, seed)")
	DeclFunc("ext_makegrains", voronoi, "Voronoi tesselation (grain size, num regions)")
	DeclFunc("ext_rmSurfaceCharge", removeLRSurfaceCharge, "Compensate magnetic charges on the left and right sides of an in-plane magnetized wire. Arguments: region, mx on left and right side, resp.")
	DeclFunc("SetGeom", Geometry.setGeom, "Sets the geometry to a given shape")
	DeclFunc("Minimize", minimize, "Use steepest conjugate gradient method to minimize the total energy")
	DeclFunc("ext_EnableUnsafe", enableUnsafe, "Deprecated. Only here to ensure maximal backwards compatibility with mumax3.9c.")

	// DeclFunc("ReCreateMesh", ReCreateMesh, "")
	DeclFunc("SmoothMesh", SmoothMesh, "")
	DeclFunc("SetMesh", Mesh.SetMesh, "")
	DeclFunc("SetGridSize", Mesh.SetGridSize, "")
	DeclFunc("SetCellSize", Mesh.SetCellSize, "")
	DeclFunc("SetPBC", Mesh.SetPBC, "")
	DeclFunc("SetTotalSize", Mesh.SetTotalSize, "")

	DeclFunc("DefRegion", DefRegion, "Define a material region with given index (0-255) and shape")
	DeclFunc("RedefRegion", RedefRegion, "Reassign all cells with a given region (first argument) to a new region (second argument)")
	DeclFunc("ShapeFromRegion", ShapeFromRegion, "")
	DeclFunc("DefRegionCell", DefRegionCell, "Set a material region (first argument) in one cell "+
		"by the index of the cell (last three arguments)")
	DeclFunc("Relax", relax, "Try to minimize the total energy")
	DeclFunc("Run", run, "Run the simulation for a time in seconds")
	DeclFunc("RunWithoutPrecession", runWithoutPrecession, "Run the simulation for a time in seconds with precession disabled")
	DeclFunc("Steps", steps, "Run the simulation for a number of time steps")
	DeclFunc("RunWhile", runWhile, "Run while condition function is true")
	DeclFunc("SetSolver", setSolver, "Set solver type. 1:Euler, 2:Heun, 3:Bogaki-Shampine, 4: Runge-Kutta (RK45), 5: Dormand-Prince, 6: Fehlberg, -1: Backward Euler")
	DeclFunc("Exit", Exit, "Exit from the program")
	DeclFunc("ClearPostSteps", clearPostSteps, "Clear the postStep array, removing all functions executed after each solver step (centering routines, running averages, etc.)")
	DeclFunc("RunShell", runShell, "Run a shell command")

	DeclFunc("SaveOvf", saveOVF, "Save space-dependent quantity once, with auto filename")
	DeclFunc("SaveOvfAs", saveAsOVF, "Save space-dependent quantity with custom filename")
	DeclFunc("Snapshot", snapshot, "Save image of quantity")
	DeclFunc("SnapshotAs", snapshotAs, "Save image of quantity with custom filename")

	DeclFunc("Ellipsoid", ellipsoid, "3D Ellipsoid with axes in meter")
	DeclFunc("Superball", superball, "3D Superball with diameter in meter and shape parameter p. Interpolates between a cube (p=+∞), sphere (p=1), octahedron (p=0.5) and empty space (p≤0).")
	DeclFunc("Ellipse", ellipse, "2D Ellipse with axes in meter")
	DeclFunc("Cone", cone, "3D Cone with diameter and height in meter. The base is at z=0. If the height is positive, the tip points in the +z direction.")
	DeclFunc("Cylinder", cylinder, "3D Cylinder with diameter and height in meter")
	DeclFunc("Circle", circle, "2D Circle with diameter in meter")
	DeclFunc("Squircle", squircle, "2D Squircle with diameter in meter")
	DeclFunc("Cuboid", cuboid, "Cuboid with sides in meter")
	DeclFunc("Rect", rect, "2D rectangle with size in meter")
	DeclFunc("Wave", wave, "Wave with (Period, Min amplitude and Max amplitude) in meter")
	DeclFunc("SinWaveguide", sinWaveguide, "Legacy sinusoidal waveguide shortcut along x. Arguments: length, width, height, period, sinAmp (all in meter). Equivalent to SinWaveguideVertical(length, width, height, period, sinAmp, 0, 0). Thickness is measured vertically along z.")
	DeclFunc("SinWaveguideVertical", sinWaveguideVertical, "Sinusoidal waveguide along x with thickness measured vertically along z. Arguments: length, width, height, period, centerAmp, phase, z0 (all in meter/radians). Use this when the fabricated thickness is defined in the laboratory z direction.")
	DeclFunc("SinWaveguide2", sinWaveguide2, "Backwards-compatible alias for SinWaveguideVertical(length, width, height, period, centerAmp, phase, z0).")
	DeclFunc("SinWaveguideNormal", sinWaveguideNormal, "Sinusoidal waveguide with thickness measured orthogonally to the centerline in the x-z plane. Arguments: length, width, height, period, centerAmp, phase, z0 (all in meter/radians). Prefer this over SinWaveguideVertical when curvature-induced staircase artifacts matter.")
	DeclFunc("ArchWaveguide", archWaveguide, "Legacy half-sine arch waveguide shortcut with thickness measured vertically along z. Equivalent to ArchWaveguideVertical(length, width, height, archHeight, z0).")
	DeclFunc("ArchWaveguideVertical", archWaveguideVertical, "Half-sine arch waveguide along x with thickness measured vertically along z. Arguments: length, width, height, archHeight, z0 (all in meter).")
	DeclFunc("ArchWaveguideNormal", archWaveguideNormal, "Half-sine arch waveguide with thickness measured orthogonally to the centerline in the x-z plane. Arguments: length, width, height, archHeight, z0 (all in meter). Prefer this over ArchWaveguideVertical when curvature-induced staircase artifacts matter.")
	DeclFunc("Triangle", triangle, "2D triangle with vertices (x0, y0), (x1, y1) and (x2, y2)")
	DeclFunc("EqTriangle", eqTriangle, "Equilateral triangle with side in meter")
	DeclFunc("RTriangle", rTriangle, "Rounded Equilateral triangle with side in meter")
	DeclFunc("Diamond", diamond, "Diamond with side in meter")
	DeclFunc("Hexagon", hexagon, "Hexagon with side in meter")
	DeclFunc("Square", square, "2D square with size in meter")
	DeclFunc("XRange", xRange, "Part of space between x1 (inclusive) and x2 (exclusive), in meter")
	DeclFunc("YRange", yRange, "Part of space between y1 (inclusive) and y2 (exclusive), in meter")
	DeclFunc("ZRange", zRange, "Part of space between z1 (inclusive) and z2 (exclusive), in meter")
	DeclFunc("Layers", layers, "Part of space between cell layer1 (inclusive) and layer2 (exclusive), in integer indices")
	DeclFunc("Layer", layer, "Single layer (along z), by integer index starting from 0")
	DeclFunc("Universe", universe, "Entire space")
	DeclFunc("Cell", cell, "Single cell with given integer index (i, j, k)")
	DeclFunc("ImageShape", imageShape, "Use black/white image as shape")
	DeclFunc("GrainRoughness", grainRoughness, "Grainy surface with different heights per grain "+
		"with a typical grain size (first argument), minimal height (second argument), and maximal "+
		"height (third argument). The last argument is a seed for the random number generator.")
	DeclFunc("Shift", shift, "Shifts the simulation by +1/-1 cells along X")
	DeclFunc("ThermSeed", thermSeed, "Set a random seed for thermal noise")

	DeclFunc("Expect", expect, "Used for automated tests: checks if a value is close enough to the expected value")
	DeclFunc("ExpectV", expectV, "Used for automated tests: checks if a vector is close enough to the expected value")
	DeclFunc("Fprintln", fprintln, "Print to file")
	DeclFunc("Sign", sign, "Signum function")
	DeclFunc("Vector", vector, "Constructs a vector with given components")
	DeclFunc("Print", myprint, "Print to standard output")
	DeclFunc("LoadFile", loadFile, "Load a zarr data file")
	DeclFunc("LoadOvfFile", loadOvfFile, "Load an ovf data file")
	DeclFunc("Index2Coord", index2Coord, "Convert cell index to x,y,z coordinate in meter")
	DeclFunc("NewSlice", newSlice, "Makes a 4D array with a specified number of components (first argument) "+
		"and a specified size nx,ny,nz (remaining arguments)")
	DeclFunc("NewVectorMask", newVectorMask, "Makes a 3D array of vectors")
	DeclFunc("NewScalarMask", newScalarMask, "Makes a 3D array of scalars")
	DeclFunc("RegionFromCoordinate", regionFromCoordinate, "RegionFromCoordinate")

	DeclFunc("AutoSaveAs", savedQuantities.autoSaveAs, "Auto save space-dependent quantity every period (s) as the zarr standard.")
	DeclFunc("AutoSaveAsChunk", savedQuantities.autoSaveAsChunk, "Auto save space-dependent quantity every period (s) as the zarr standard.")
	DeclFunc("AutoSave", savedQuantities.autoSave, "Auto save space-dependent quantity every period (s) as the zarr standard.")
	DeclFunc("SaveAs", savedQuantities.saveAs, "Save space-dependent quantity as the zarr standard.")
	DeclFunc("SaveAsChunk", savedQuantities.saveAsChunk, "")
	DeclFunc("Save", savedQuantities.save, "Save space-dependent quantity as the zarr standard.")

	DeclFunc("TableSave", tableSave, "Save the data table right now.")
	DeclFunc("TablePrint", myprint, "Print anyting in the data table")
	DeclFunc("TableAdd", tableAdd, "Save the data table periodically.")
	DeclFunc("TableAddVar", tableAddVar, "Save the data table periodically.")
	DeclFunc("TableAddAs", tableAddAs, "Save the data table periodically.")
	DeclFunc("TableAutoSave", tableAutoSave, "Save the data table periodically.")

	DeclFunc("RemoveCustomEnergies", removeCustomEnergies, "Removes all custom energies")
	DeclFunc("RunningAverage", runningAverage, "Records the time-average of a quantity from the moment this function is called.\nNote: this may impact performance since the Quantity will be evaluated after every step.")
	DeclFunc("Sum", sumQuantity, "Sum of Quantity over all cells in the grid. For a vector Quantity, all components are added together.")
	DeclFunc("SumVector", sumVectorQuantity, "Sum of vector Quantity over all cells in the grid.")
}

// DeclFunc Add a function to the script world
func DeclFunc(name string, f any, doc string) {
	World.Func(name, f, doc)
}
